### ISSUE TITLE
konlpy .pos호출시에 

### ISSUE THREAD

**Issue by DoHyeong** [konlpy/konlpy#105]
연속해서 만번정도 호출하는데 
java.lang.OutOfMemoryErrorPyRaisable: java.lang.OutOfMemoryError: Java heap space
에러가 뜨네요...
방법이 없을까요?

**Comment by e9t** [comment]
안녕하세요. https://github.com/konlpy/konlpy/issues/93 를 확인해보시고, 제안된 방법으로 해결이 안되는 경우 이슈를 다시 열어주시기 바랍니다.
