### ISSUE TITLE
Unable to load DLL 문제 해결부탁드려요...

### ISSUE THREAD

**Issue by rlagur0516** [konlpy/konlpy#111]
<pre>Traceback (most recent call last):
  File "D:/smartdiarysystem/smart_diary_system/koNLPy.py", line 7, in <module>
    words = konlpy.tag.Twitter().pos(sentence)
  File "C:\Users\SEL-Student\Anaconda3\lib\site-packages\konlpy\tag\_twitter.py", line 72, in __init__
    jvm.init_jvm(jvmpath)
  File "C:\Users\SEL-Student\Anaconda3\lib\site-packages\konlpy\jvm.py", line 51, in init_jvm
    '-ea', '-Xmx768m')
  File "C:\Users\SEL-Student\Anaconda3\lib\site-packages\jpype\_core.py", line 50, in startJVM
    _jpype.startup(jvm, tuple(args), True)
RuntimeError: Unable to load DLL [C:\Program Files\Java\jre1.8.0_101\bin\client\jvm.dll], error = The specified module could not be found.
 at native\common\include\jp_platform_win32.h:58

Process finished with exit code 1
</pre>

**Comment by tahoar** [comment]
I get exactly the same error. I'm on Windows 10. I tried Java JRE 8, JDK8, JRE7 and JDK7. All have he same result. Despite the "could not be found" error, the DLL at that path actually exists. I set JAVA_HOME but it did not work. I added the java paths to my system %PATH% and it did not work.

**Comment by e9t** [comment]
Please check if the following tip helps: https://github.com/konlpy/konlpy/issues/115

**Comment by e9t** [comment]
bash에서 `echo $JAVA_HOME`을 입력해보면 뭐라고 뜨나요?
버젼 1.6이하가 설정되어 있거나 변수가 비어있을 수 있습니다.

해결법은:

<pre>
$ vi ~/.bashrc
</pre>

를 해서 .bashrc 파일을 연 후, `export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"`를 추가해주세요.
(1.8 버젼을 찾아서 JAVA_HOME이라는 환경변수로 설정해주라는 의미입니다.
그 후 bash로 나가서 .bashrc를 source 해주면 됩니다.

<pre>
$ source ~/.bashrc
</pre>
