### ISSUE TITLE
OSX  Unable to load DLL 에 대한 해결책공유

### ISSUE THREAD

**Issue by pizza12333** [konlpy/konlpy#115]
안녕하세요. 
저는 Konlpy를 자주 사용하고 있는 경영베이스의 대학생입니다. 
아무래도 저와같이 컴퓨터에 대해 생소한 사람들은 오류를 해결하는데 많이 어려움이 있습니다. 그래서 이번에 윈도우에서 OSX로 바꾸면서 konlpy 예제의 겪었던 아래 오류의 한가지 해결책을 공유하고 싶어서 이슈를 올렸습니다.

```
RuntimeError: Unable to load DLL [/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib], error = dlopen(/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib, 9): no suitable image found.  Did find:
    /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib: mach-o, but wrong architecture at native/common/include/jp_platform_linux.h:45
```

제 경우 최신버전의 Java SE 8와 팝업창으로 제시되는 JAVA SE 6를 설치했더라도, 이 문제가 해결되지 않았습니다.
최신버전의 JAVA를 설치했지만, 이 오류가 계속 뜨는 이유는 OSX의 기본 $JAVA_HOME 변수가 최신버전의 JAVA로  설정되지 않았기 때문인것을 발견했습니다. 

```
$ java -version
```

```
java version "1.6.0_065"
Java(TM) SE Runtime Environment (build .6.0_065-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-486, mixed mode)
```

만약 JAVA 최선버전을 설치했지만 위와 같이 뜬다면,   default java를 변경해야 합니다.

우선

```
$ /usr/libexec/java_home -V
```

를 터미널에 입력하여 현재 설치된 모든 JAVA를 확인합니다.

```
Matching Java Virtual Machines (3):
    1.8.0_101, x86_64:  "Java SE 8" /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home
    1.6.0_65-b14-468, x86_64:   "Java SE 6" /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
    1.6.0_65-b14-468, i386: "Java SE 6" /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
```

저 같은 경우는 기본 자바를 1.8.0_101 버전으로 아래 터미널 명령어를 통해 설정했습니다.

```
$ export JAVA_HOME=`/usr/libexec/java_home -v 1.8.0_101`
```

이후 다시 아래 명령어를 입력한다면

```
$ java -version
```

```
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

위와 같이 변경된 것을 발견 할 수 있고, 파이썬에서 konlpy unable to load dll 문제가 해결됐습니다. 
##

**Comment by e9t** [comment]
해결법 공유 감사합니다 :)

**Comment by e9t** [comment]
@pizza12333 님께서 제안해주신 방법은 해당 session에서만 유효한 경우여서, 문제를 계속 겪는 분들이 계시는 것 같습니다. 위 방법을 permanent 하게 적용하기 위해서는 다음과 같이 해보시기 바랍니다.

<pre>
$ vi ~/.bashrc
</pre>

를 해서 .bashrc 파일을 연 후, `export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"`를 추가해주세요.
(1.8 버젼을 찾아서 JAVA_HOME이라는 환경변수로 설정해주라는 의미입니다.

그 후 bash로 나가서 .bashrc를 source 해주면 됩니다.

<pre>
$ source ~/.bashrc
</pre>

이제 `echo $JAVA_HOME`을 입력했을 때 버젼 1.8이 설정된 것을 확인하실 수 있을 것입니다.
