### ISSUE TITLE
GC overhead limit exceeded Error 해결방법에 대해 궁금합니다.

### ISSUE THREAD

**Issue by jaejuning** [konlpy/konlpy#116]
꼬꼬마 인스턴스를 생성한 후 sentences module을 사용하였는데
jpype._jexception.OutOfMemoryErrorPyRaisable: java.lang.OutOfMemoryError: GC overhead limit exceeded
error 문구가 발생하면서 실행이 안됩니다.
다른 issues에는 없길래 글 남깁니다!

(참고로 data는 그렇게 크지 않은 데이터입니다.txt파일로 5MB)

**Comment by zzaebok** [comment]
문제를 해결하신 건가요??  저도 GC overhead limit 에러가 떠서요..
