### ISSUE TITLE
Hannanum morphs 문제

### ISSUE THREAD

**Issue by zsef123** [konlpy/konlpy#117]
python 3.5.2  32bit, VS 2015 PTSV , Java 32bit
konlpy(0.4.4)
JPypye1(0.6.1)
사용중입니다.

pandas를 이용해 엑셀 파일을 읽어 형태소 분석을 하고있는데 특정 String에서 문제가 생깁니다.
Hannanum morphs()를 사용하면 프리징이나 오류가 발생하지 않고 그대로 대기를 해버립니다.

Visual Studio에서 디버그를 통해 조사식 계산에서 임의로 hannanum morphs를 사용하면 식을 계산할수 없습니다.
라고만 뜹니다.

아래는 조사식에서 복사한 문제가 되는 글과 코드입니다.

 말기암 환자에게 진료 대신 완화의료를 약 12% 정도에게만 적용해도, 5년간 2,918억원에 달하는 재정을 절감할 수 있다는 주장이 나왔다.\r\n\r\n\r\n\r\n고령화 사회 전환 및 만성질환 급증 등으로 인한 진료비를 절감하기 위해서는 완화의료시설을 대폭 늘려야 하며, 이를 위해서는 정부 주도의 국민인식 개선, 암 이외의 적용대상 확대, 병원의 시설 구축 등이 필요하다는 제언이다.\r\n\r\n\r\n\r\n국민건강보험공단은 호스피스 완화의료 활성화 방안을 주제로 12일 오전 정책세미나를 개최, 주제발표를 맡은 서울의대 윤영호 교수가 이같이 밝혔다.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n말기암 환자의 1인당 진료비는 호스피스의 경우 상급종합병원은 일당수가 29만900원, 재원일수 22일로 합계 639만 9,809원, 종합병원은 28만 4,484원으로 총 625만 8,658원, 병원은 474만 1,091원, 의원 446만 5,598원 등이다.\r\n\r\n\r\n\r\n그러나 말기암환자가 호스피스를 하지 않고 일반 진료를 받게 되면, 상급종합병원의 경우 총 1,348만 5,444원의 진료비를 사용하게 되며, 종합병원 783만 6,893원, 병원 348만 7,201원, 의원 232만 8,810원의 진료비가 필요하다.\r\n\r\n\r\n\r\n이를 토대로 윤영호 교수는 호스피스를 현재 시행 중인 12.7%를 적용하면, 5년간 진료비를 약 2918억 6100만원 절감할 수 있다고 주장했다.\r\n\r\n\r\n\r\n실제 미국에서 실시한 연구에서는 임종 전 1개월 동안 호스피스 환자의 진료비가 비호스피스 환자에 비해 약 46.5% 감소했으며, 임종 전 1년동안의 전체 의료비 10.4%를 절감했다는 결과가 나왔다.\r\n\r\n\r\n\r\n대만에서도 호스피스 비용-효과를 분석한 결과, 전통적인 치료 보다 호스피스가 사망 1개월 전 의료비를 64.2% 줄이는 효과를 보였다.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n윤 교수는 고령화 사회로의 진입, 암을 비롯한 각종 만성질환 급증 등 진료비가 폭등하고 있다며 속히 우리나라도 호스피스 완화의료가 활성화돼야 하나, 인프라와 사회적 인식, 정책 등 모든 것이 부족한 실정이라고 지적했다.\r\n\r\n\r\n\r\n호스피스 완화의료기관 이용률은 한국의 경우 암 사망자의 13.8%, 전체 사망자의 약3%에 불과하다. 반면 미국의 경우 전체 사망자 44.6%가 호스피스 완화의료기관을 이용했다.\r\n\r\n\r\n\r\n◆ 해결책은? 병상 구축 행정 지원\r\n\r\n\r\n\r\n이에 윤 교수는 호스피스 완화의료를 활성화하기 위해 암 환자 이외의 모든 말기 환자로 대상을 확대해야 한다고 제안했다.\r\n\r\n\r\n\r\n\r\n\r\n또한 환자들이 자연스럽게 완화의료에 대한 의사결정을 할 수 있도록 연명의료계획을 마련해야 하며, 5개년 계획 수립 및 권역별 센터 운영 등 행정적인 지원을 이어가야 한다고 부연했다.\r\n\r\n\r\n\r\n윤 교수는 35개의 권역별 센터가 필요하며, 5년 내에 2500병상 정도를 구축해야 한다면서 선진국에서는 인구 100만명당 50병상을 구축하고 있다. 앞으로 말기암 이외의 다른 병으로까지 호스피스를 적용하면 더욱 많은 병상이 필요할 것이라고 말했다.\r\n\r\n\r\n\r\n이를 위해서는 장례식장 대신 병원들이 완화의료시설 마련하는 방안을 제안하기도 했다. 윤 교수는 운영을 제대로 하면, 적자는 나지 않을 것이다. 오히려 경영에 도움될 것이라고 주장했다.\r\n\r\n\r\n\r\n특히 건보공단이 말기환자 의료이용에 대해 대학 및 연구기관 등과 연구 실시한 후, 이를 바탕으로 의료계와의 협력을 통해 말기환자 진료 지침을 개발해야 한다고 강조했다.\r\n\r\n\r\n\r\n이어 공단과 정부는 말기환자 관리에 대한 정책과 제도를 개발하고, 아직까지 자리잡지 못한 웰다잉 개념을 퍼뜨리기 위해 시민단체와 대국민 캠페인 진행해야 한다고 제언했다.\r\n\r\n\r\n\r\n◆ 공단 만성질환으로의 확대 찬성..다만 인력조직 충원 필요\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n이 같은 정책 및 제도적 제안에 대해 건강보험정책연구원 최영순 연구위원은 동의하면서, 이제는 암을 넘어 만성질환 대상의 호스피스 완화의료 제도 도입을 위한 준비를 해야 한다고 언급했다.\r\n\r\n\r\n\r\n이를 위해서는 공단 내 역량있는 조직이 필요하다고 밝히면서, 행정직과 연구직이 연계한 호스피스관리실(가칭)을 구성해야 한다고 주장했다.\r\n\r\n\r\n\r\n또 최 연구위원은 전문가 조직을 구성해 만성질환을 정의하는 작업을 한 후 진료비 자료를 분석하고, 원가를 조사해 적정 수가를 만들어야 한다며 만성질환 대상 호스피스 완화의료 수가 시범사업을 시행해야 한다고 했다.\r\n\r\n\r\n\r\n이외에도 호스피스 완화의료 활성화를 위해 정책연구원에서 교육프로그램을 마련해 대국민 교육을 실시하고, 강사 양성, 보수 교육 및 평가 등을 시행해야 한다고 부연했다.\r\n\r\n\r\n\r\n뿐만 아니라 국민 인식 확대를 위해 윤 교수가 제안한 웰다잉 캠페인은 물론, 다양한 정보제공과 홍보활동 등을 구체적으로 진행해야 한다고 강조했다.\r\n\r\n

```
from konlpy.tag import Hannanum
t=" 말기암 환자에게 진료 대신 완화의료를 약 12% 정도에게만 적용해도, 5년간 2,918억원에 달하는 재정을 절감할 수 있다는 주장이 나왔다.\r\n\r\n\r\n\r\n고령화 사회 전환 및 만성질환 급증 등으로 인한 진료비를 절감하기 위해서는 완화의료시설을 대폭 늘려야 하며, 이를 위해서는 정부 주도의 국민인식 개선, 암 이외의 적용대상 확대, 병원의 시설 구축 등이 필요하다는 제언이다.\r\n\r\n\r\n\r\n국민건강보험공단은 호스피스 완화의료 활성화 방안을 주제로 12일 오전 정책세미나를 개최, 주제발표를 맡은 서울의대 윤영호 교수가 이같이 밝혔다.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n말기암 환자의 1인당 진료비는 호스피스의 경우 상급종합병원은 일당수가 29만900원, 재원일수 22일로 합계 639만 9,809원, 종합병원은 28만 4,484원으로 총 625만 8,658원, 병원은 474만 1,091원, 의원 446만 5,598원 등이다.\r\n\r\n\r\n\r\n그러나 말기암환자가 호스피스를 하지 않고 일반 진료를 받게 되면, 상급종합병원의 경우 총 1,348만 5,444원의 진료비를 사용하게 되며, 종합병원 783만 6,893원, 병원 348만 7,201원, 의원 232만 8,810원의 진료비가 필요하다.\r\n\r\n\r\n\r\n이를 토대로 윤영호 교수는 호스피스를 현재 시행 중인 12.7%를 적용하면, 5년간 진료비를 약 2918억 6100만원 절감할 수 있다고 주장했다.\r\n\r\n\r\n\r\n실제 미국에서 실시한 연구에서는 임종 전 1개월 동안 호스피스 환자의 진료비가 비호스피스 환자에 비해 약 46.5% 감소했으며, 임종 전 1년동안의 전체 의료비 10.4%를 절감했다는 결과가 나왔다.\r\n\r\n\r\n\r\n대만에서도 호스피스 비용-효과를 분석한 결과, 전통적인 치료 보다 호스피스가 사망 1개월 전 의료비를 64.2% 줄이는 효과를 보였다.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n윤 교수는 고령화 사회로의 진입, 암을 비롯한 각종 만성질환 급증 등 진료비가 폭등하고 있다며 속히 우리나라도 호스피스 완화의료가 활성화돼야 하나, 인프라와 사회적 인식, 정책 등 모든 것이 부족한 실정이라고 지적했다.\r\n\r\n\r\n\r\n호스피스 완화의료기관 이용률은 한국의 경우 암 사망자의 13.8%, 전체 사망자의 약3%에 불과하다. 반면 미국의 경우 전체 사망자 44.6%가 호스피스 완화의료기관을 이용했다.\r\n\r\n\r\n\r\n◆ 해결책은? 병상 구축 행정 지원\r\n\r\n\r\n\r\n이에 윤 교수는 호스피스 완화의료를 활성화하기 위해 암 환자 이외의 모든 말기 환자로 대상을 확대해야 한다고 제안했다.\r\n\r\n\r\n\r\n\r\n\r\n또한 환자들이 자연스럽게 완화의료에 대한 의사결정을 할 수 있도록 연명의료계획을 마련해야 하며, 5개년 계획 수립 및 권역별 센터 운영 등 행정적인 지원을 이어가야 한다고 부연했다.\r\n\r\n\r\n\r\n윤 교수는 35개의 권역별 센터가 필요하며, 5년 내에 2500병상 정도를 구축해야 한다면서 선진국에서는 인구 100만명당 50병상을 구축하고 있다. 앞으로 말기암 이외의 다른 병으로까지 호스피스를 적용하면 더욱 많은 병상이 필요할 것이라고 말했다.\r\n\r\n\r\n\r\n이를 위해서는 장례식장 대신 병원들이 완화의료시설 마련하는 방안을 제안하기도 했다. 윤 교수는 운영을 제대로 하면, 적자는 나지 않을 것이다. 오히려 경영에 도움될 것이라고 주장했다.\r\n\r\n\r\n\r\n특히 건보공단이 말기환자 의료이용에 대해 대학 및 연구기관 등과 연구 실시한 후, 이를 바탕으로 의료계와의 협력을 통해 말기환자 진료 지침을 개발해야 한다고 강조했다.\r\n\r\n\r\n\r\n이어 공단과 정부는 말기환자 관리에 대한 정책과 제도를 개발하고, 아직까지 자리잡지 못한 웰다잉 개념을 퍼뜨리기 위해 시민단체와 대국민 캠페인 진행해야 한다고 제언했다.\r\n\r\n\r\n\r\n◆ 공단 만성질환으로의 확대 찬성..다만 인력조직 충원 필요\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n이 같은 정책 및 제도적 제안에 대해 건강보험정책연구원 최영순 연구위원은 동의하면서, 이제는 암을 넘어 만성질환 대상의 호스피스 완화의료 제도 도입을 위한 준비를 해야 한다고 언급했다.\r\n\r\n\r\n\r\n이를 위해서는 공단 내 역량있는 조직이 필요하다고 밝히면서, 행정직과 연구직이 연계한 호스피스관리실(가칭)을 구성해야 한다고 주장했다.\r\n\r\n\r\n\r\n또 최 연구위원은 전문가 조직을 구성해 만성질환을 정의하는 작업을 한 후 진료비 자료를 분석하고, 원가를 조사해 적정 수가를 만들어야 한다며 만성질환 대상 호스피스 완화의료 수가 시범사업을 시행해야 한다고 했다.\r\n\r\n\r\n\r\n이외에도 호스피스 완화의료 활성화를 위해 정책연구원에서 교육프로그램을 마련해 대국민 교육을 실시하고, 강사 양성, 보수 교육 및 평가 등을 시행해야 한다고 부연했다.\r\n\r\n\r\n\r\n뿐만 아니라 국민 인식 확대를 위해 윤 교수가 제안한 웰다잉 캠페인은 물론, 다양한 정보제공과 홍보활동 등을 구체적으로 진행해야 한다고 강조했다.\r\n\r\n"
han=Hannanum()
print(han.morphs(t))
```

**Comment by Swalloow** [comment]
테스트 해보시면 마지막 "\r\n\r\n" 부분을 제외하면 잘 돌아갑니다.
앞에 있는 "\r\n\r\n뿐만" 같은 경우, 앞의 non-literal을 거르고 '뿐', '만'의 결과가 나오게 되지만
마지막 "\r\n\r\n"은 EOF ERROR가 나면서 멈추는듯 합니다.
정규표현식으로 특수문자를 거르시면 버그를 해결할 수 있습니다.
