### ISSUE TITLE
Jpype 설치 문제 관련 이슈

### ISSUE THREAD

**Issue by Jooong** [konlpy/konlpy#118]
안녕하세요, 
 **mac OS 10.12(16A323)** 와 **Python 3.5.2 :: Anaconda custom (x86_64)** 사용중인데,
document를 참고해서 Jpype를 다운로드 하던 중 문제가 발생했습니다.

>pip3 install JPype1-py3

터미널에서 위와같은 명령어를 실행했더니 아래와 같은 에러 메시지가 나왔습니다.

>Failed building wheel for JPype1-py3

>Command "//anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/4c/j0z4p99d02l_y4hqv4w0_25m0000gn/T/pip-build-k6meyp6c/JPype1-py3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/4c/j0z4p99d02l_y4hqv4w0_25m0000gn/T/pip-sc_k4pp6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/4c/j0z4p99d02l_y4hqv4w0_25m0000gn/T/pip-build-k6meyp6c/JPype1-py3/

혹시 어떻게 하면 해결할 수 있을까요?? 제가 코딩에 입문한 지 얼마 되지 않아 깃헙 이슈 생성 시 기본적인 매너에 대해 무지합니다ㅠㅠ 이슈 생성 시 기입해야 하는 기본 정보를 빼먹었다거나 다른 곳에서 충분히 해결 할 수 있는 문제인데 제기한 이슈라면 미리 사과드립니다 ㅠㅠ

**Comment by e9t** [comment]
안녕하세요. 컴파일러가 제대로 설치되지 않아서 생긴 문제인 것 같은데 아래 링크의 지시사항을 한 번 따라보시겠어요?
http://jpype.readthedocs.io/en/latest/install.html

일단 konlpy 관련 이슈는 아니니 이슈를 닫도록 하겠습니다.
혹시 추가적인 문제가 발생하는 경우 댓글을 달아주세요.

**Comment by blissray** [comment]
저 같은 경우는 

1) 직접 [jpype github 페이지](https://github.com/originell/jpype)에 가서 제 컴퓨터에 clone 하고 
2) python setup.py install 명령어 설치를 하였습니다.

전 conda 가상환경에서 실행하였는데, 문제없이 실행되었습니다.
