### ISSUE TITLE
java.lang.VirtualMachineErrorPyRaisable: java.lang.OutOfMemoryError: Java heap space 에러 발생

### ISSUE THREAD

**Issue by ghost** [konlpy/konlpy#127]
from konlpy.tag import Twitter; t = Twitter()
#tokens_ko = t.morphs(doc_ko)
tokens_ko = t.pos(doc_ko)

위의 명령을 실행했는데 아래와 같은 에러가 발생합니다. 형태소 분석하려는 파일의 크기가 커서 그런 것 같은데 어떻게 해결이 가능할까요?

https://github.com/konlpy/konlpy/issues/93
위의 링크가 유사한 문제인것 같은데, 정확히 어떻게 해결해야 할지 잘 모르겠습니다.

감사합니다.

java.lang.VirtualMachineErrorPyRaisableTraceback (most recent call last)
<ipython-input-8-d944b995bf10> in <module>()
      1 from konlpy.tag import Twitter; t = Twitter()
      2 #tokens_ko = t.morphs(doc_ko)
----> 3 tokens_ko = t.pos(doc_ko)

/usr/local/lib/python2.7/dist-packages/konlpy/tag/_twitter.pyc in pos(self, phrase, norm, stem)
     49                     phrase,
     50                     jpype.java.lang.Boolean(norm),
---> 51                     jpype.java.lang.Boolean(stem)).toArray()
     52         return [tuple(t.rsplit('/', 1)) for t in tokens]
     53 

java.lang.VirtualMachineErrorPyRaisable: java.lang.OutOfMemoryError: Java heap space

**Comment by minhoryang** [comment]
user accounts that have been deleted.
