### ISSUE TITLE
'Tagger' is not defined

### ISSUE THREAD

**Issue by pbzweihander** [konlpy/konlpy#131]
mecab.sh를 curl로 받아서 설치했는데 계속 mecab = Mecab() 부분에서 NameError이 납니다
파이썬 3.5.2이고 우분투입니다
Installation에 나와있는 내용 그대로 따라해도 문제가 발생합니다

**Comment by pbzweihander** [comment]
문제가 libmecab.so.2가 없어서 발생하는거 같네요
mecab-python3를 설치해봐도 똑같습니다

**Comment by pbzweihander** [comment]
http://searchtool.tistory.com/3
이 링크로 해결됬습니다
혹시 같은 문제 겪고 계신 분께 도움이 됬음 좋겠네요

**Comment by Terrorboy** [comment]
@pbzweihander  :+1:
