### ISSUE TITLE
MeCab 설치 도중 Error입니다.

### ISSUE THREAD

**Issue by waky80** [konlpy/konlpy#132]
안녕하세요, KoNLPy 패키지를 사용하기 위해서 다음과 같이 설치하던 중 발생한 에러를 해결하지 못하여 질문을 드립니다.

OS - Ubuntu 14.04

설치 과정
$ sudo apt-get install python-dev python3-dev
$ sudo pip install konlpy
$ sudo apt-get install curl
$ bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)

에러 메시지
copying build/lib.linux-x86_64-2.7/_MeCab.so -> /usr/local/lib/python2.7/dist-packages
error: [Errno 13] Permission denied: /usr/local/lib/python2.7/dist-packages/_MeCab.so
copying build/lib.linux-x86_64-3.4/_MeCab.cpython-34m.so -> /usr/local/lib/python3.4/dist-packages
error: could not create /usr/local/lib/python3.4/dist-packages/_MeCab.cpython-34m.so: Permission denied

**Comment by parkheegeun** [comment]
셀프 답변입니다~ ^^

1. https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh 파일을 다운로드
2. mecab.sh 파일 내의 마지막 부분 "# install mecab-python" 의 python, python3 명령 부분을 sudo로 실행하도록 추가

**Comment by SungHoAhn** [comment]
Thanks, very helpful
