### ISSUE TITLE
MeCab 오류 관련 질문입니다.

### ISSUE THREAD

**Issue by dlsrb6342** [konlpy/konlpy#133]
<img width="570" alt="2017-01-27 10 00 42" src="https://cloud.githubusercontent.com/assets/19386038/22371728/1690f096-e4dc-11e6-8bd2-0cf8c221a89e.png">
이런 식의 error가 나서 pip install tagger를 통해 설치하려 했는데 
<img width="572" alt="2017-01-27 10 01 44" src="https://cloud.githubusercontent.com/assets/19386038/22371750/38df89aa-e4dc-11e6-8eb6-ad62b84ac824.png">
이런 오류가 나옵니다... 
<img width="225" alt="2017-01-27 10 02 30" src="https://cloud.githubusercontent.com/assets/19386038/22371769/549b8a9a-e4dc-11e6-990f-f4cc7d6939d4.png">
pip list입니다. rdflib이 깔려 있는데도 저런 error가 나오네요ㅠㅠ 위의 error에 나오는 rdflib==2.3.1events를 설치하려 해도 똑같은 error가 출력됩니다.  어떻게 해결해야 하나요?

**Comment by clemmy** [comment]
:+1: Also having this issue for Mecab. Followed this instructions found [here](http://konlpy.org/en/v0.4.4/install/#centos) for CentOS, including the Mecab installation.

**Comment by dlsrb6342** [comment]
thanks for comments. I tried that in your comment. but i still have that issue.
I solved this issue add "/usr/local/lib" in "/etc/ld.so.conf" file.
