### ISSUE TITLE
jupyter notebook에서 jpype 에러가 뜨는 문제

### ISSUE THREAD

**Issue by rudvlf0413** [konlpy/konlpy#143]
간혹 jupyter notebook에서 konlpy 라이브러리 (Twitter 모듈 등)을 사용할 때
jpype가 설치가 되었는데도 불구하고 jpype undefined Error가 뜨는 경우가 많은데요
(저도 가끔 곤혹스러웠습니다. 삽질도...)

이 경우 from konlpy.tag import Twitter
이런 모듈 호출 코드를 jupyter notebook의 가장 첫번째 셀의 첫번째 줄로 옮기고
커널을 재시작해서 실행해보시길 바랍니다.
이러니 해결이 되더라구요.

왜 그런지는 잘 모르겠습니다. 원인이 뭘까요?

**Comment by kimyoungjin06** [comment]
저의 경우는 java path 문제였는데요

$ vi ~/.bashrc

#JAVA_PATH
export JAVA_HOME="/usr/lib/jvm/java-7-openjdk-amd64"
source ~/.bashrc

이렇게 자바 경로를 추가하니 되더군요
