### ISSUE TITLE
Mecab 객체 생성시 에러 (Tagger is not defined) 

### ISSUE THREAD

**Issue by rohjoon** [konlpy/konlpy#144]
tag/_mecab.py 에서, Tagger 를 import 할 때 에러가 발생하면 pass 하도록 되어있는데 (아마 MaCab이 없으면 pass 하겠죠?) 
102번째 줄 코드에서 Tagger로 객체를 생성하는 부분에는 예외처리가 되어있지 않아 Mecab 객체를 생성할 때 에러가 발생합니다. 
```
  File "/usr/local/lib/python3.6/site-packages/konlpy/tag/_mecab.py", line 102, in __init__
    self.tagger = Tagger('-d %s' % dicpath)
NameError: name 'Tagger' is not defined
```

**Comment by dlsrb6342** [comment]
_mecab.py의 [이 부분](https://github.com/konlpy/konlpy/blob/master/konlpy/tag/_mecab.py#L110~L111) 을 보시면 NameError 처리가 되어있는데 pypi에 업데이트가 안되어있는 것 같습니다.

**Comment by yoonsubKim** [comment]
konlpy 의 공식 문서에 따르면 mecab을 사용할 때, 아래와 같은 쉘 스크립트 하나를 실행시켜줘야 한다고 명시되어있습니다. 
`$ bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)`

refer to : http://konlpy.org/en/latest/install/

**Comment by ho9science** [comment]
http://searchtool.tistory.com/3 참고하시면 좋을 것 같습니다.

**Comment by ho9science** [comment]
konlpy를 가상환경에 설치할 때 오류가 발생한다면
직접 mecab-python을 직접 설치해보세요~
- (venv)git clone https://bitbucket.org/eunjeon/mecab-python-0.996.git
- (venv)cd mecab-python-0.996/
- (venv)python3 setup.py build
- (venv)python3 setup.py install

**Comment by lqez** [comment]
@ho9science 님의 방법으로 같은 문제를 해결했습니다. 감사합니다.

**Comment by minhoryang** [comment]
@rohjoon 여전히 문제를 겪으시는지 알고싶습니다.
