### ISSUE TITLE
Hannanum on Mac OS X: weird POS result

### ISSUE THREAD

**Issue by combacsa** [konlpy/konlpy#15]
```python
hannanum.pos(u"안녕하세요.", ntags=22)
[(u'\uc548\ub155\ud558\uc138\uc694', u'NC'), (u'.', u'SF')]
```

"안녕/NC+하/XS+세/EF+요/JX" 꼴로 분석되어야 하는데 "안녕하세요" 전체가 NC로 분석되고 있습니다. 사전 파일에 딱히 문제가 있지는 않습니다. 

OS X 터미널에서 HannanumInterface.main()을 직접 호출한 결과는 다음과 같습니다.
```
(rainist_env)Users-MacBook-Air:java user$ /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Commands/java -cp "jhannanum-0.8.4.jar:bin" kr.lucypark.jhannanum.comm.HannanumInterface
null

null
???????
	???????/NC

?????
	?????/NC

.
	./SF
```
따라서 이 문제는 Java로 디버깅을 해 봐야 할 것으로 생각됩니다. 어쩌면 좋은 아이디어가 떠오르지 않으면 Hannanum 소스코드 전체를 갖고 디버깅을 해야 할지도 ...

**Comment by e9t** [comment]
안녕하세요. 저도 Mac OS X 10.10.2에서 방금 돌려보니 아래와 같이 제대로 된 결과가 나왔습니다.
애초에 문제를 지적해주셨을 때는 미처 확인해보지 못했는데, 혹시 그 동안 모듈을 업그레이드 하는 과정에서 문제가 해결된 것일 수도 있다는 생각이 드네요.

- Python2
<pre>
In [1]: from konlpy.tag import Hannanum
In [2]: h = Hannanum()
In [3]: h.pos(u'안녕하세요.')
Out[3]: 
[(u'\uc548\ub155', u'N'),
 (u'\ud558', u'X'),
 (u'\uc138', u'E'),
 (u'\uc694', u'J'),
 (u'.', u'S')]
In [4]: 
</pre>

- Python3
<pre>
In [1]: from konlpy.tag import Hannanum
In [2]: h = Hannanum()
In [3]: h.pos('안녕하세요.')
Out[3]: [('안녕', 'N'), ('하', 'X'), ('세', 'E'), ('요', 'J'), ('.', 'S')]
In [4]: 
</pre>

일단 이슈를 닫겠습니다.
만일 문제가 재확인된다면 다시 이슈를 열어주시면 감사하겠습니다 :)
