### ISSUE TITLE
Tag 인스턴스 생성 시 세그멘테이션 오류발생

### ISSUE THREAD

**Issue by bhappy10** [konlpy/konlpy#150]
OS: Ubuntu 16.04 LTs
Python version: 3.5.3
Java version : 1.8.0_131
JAVA_HOME:  /usr/lib/jvm/java-8-openjdk-amd64/

JPype1와 konlpy 패키지를 설치 후 테스트를 위해 아래 코드를 작성했는데, 
from konlpy.tag import Twitter
twit = Twitter()

세그멘테이션 오류와 함께 파이썬이 종료됩니다.
원인을 찾지 못하겠네요....

![2017-06-28 18-07-42](https://user-images.githubusercontent.com/17981048/27629279-cd0688c8-5c2c-11e7-9e01-c78a1406fd82.png)

**Comment by DongjunLee** [comment]
저도 같은 증상입니다..!

**Comment by bhappy10** [comment]
커널 버전 수정 이후에 해결되었습니다. 제가 쓰는 커널 버전에서 JVM 관련 오류가 있었습니다.
