### ISSUE TITLE
python3에서 mecab 사용시 unicode 관련 문제가 있는 것 같습니다.

### ISSUE THREAD

**Issue by jeonggyu-huh** [konlpy/konlpy#152]
python3 사용시 아래처럼 flatten(어절 단위로 묶어주는 기능)을 사용하면 오류가 발생합니다.

python2 사용시는 별 문제가 없는 것으로 보입니다.
글자가 출력 안 되고 유니코드 매칭 문자(?)가 출력되는건 왜인지는 잘 모르겠지만요. ㅠ

`jk@jk-lab-mint ~/Dropbox/코드/2017/7/merge $ python2
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from konlpy.tag import Mecab
>>> mecab = Mecab()
>>> st=u'나는 배가 고프다.'
>>> mecab.pos(st,flatten=False)
[[(u'\ub098', u'NP'), (u'\ub294', u'JX')], [(u'\ubc30\uac00', u'NNG')], [(u'\uace0\ud504', u'VA'), (u'\ub2e4', u'EF'), (u'.', u'SF')]]
>>> exit()
jk@jk-lab-mint ~/Dropbox/코드/2017/7/merge $ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from konlpy.tag import Mecab
>>> mecab = Mecab()
>>> st=u'나는 배가 고프다.'
**>>> mecab.pos(st,flatten=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/konlpy/tag/_mecab.py", line 87, in pos
    for eojeol in phrase.split()]
  File "/usr/local/lib/python3.5/dist-packages/konlpy/tag/_mecab.py", line 87, in <listcomp>
    for eojeol in phrase.split()]
AttributeError: 'str' object has no attribute 'decode'**
>>> `

**Comment by hsleep** [comment]
저도 같은 문제를 겪고 있어서 소스를 살펴보니, python3 버전 대응 하는 코드에 문제가 있는거 같습니다.
PR #108 에서 해결 된거 같은데, 그 이후로 관리가 안되는거 같습니다.

**Comment by daewonyoon** [comment]
python3 환경에서 Mecab pos 함수 flatten=False 로 주었을 때, 에러가 발생.

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from konlpy.tag import Mecab
>>> m = Mecab()
>>> m.pos('그러니까 범죄사실을 인정하겠다는 겁니까 말겠다는 겁니까?', flatten=True)
[('그러니까', 'MAJ'), ('범죄', 'NNG'), ('사실', 'NNG'), ('을', 'JKO'), ('인정', 'NNG'), ('하', 'XSV'), ('겠', 'EP'), ('다는', 'ETM'), ('겁니까', 'NNB+VCP+EC'), ('말', 'VX'), ('겠', 'EP'), ('다는', 'ETM'), ('겁니까', 'NNB+VCP+EF'), ('?', 'SF')]
>>> m.pos('그러니까 범죄사실을 인정하겠다는 겁니까 말겠다는 겁니까?', flatten=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/proj19/env3664/lib/python3.6/site-packages/konlpy/tag/_mecab.py", line 92, in pos
    for eojeol in phrase.split()]
  File "/work/proj19/env3664/lib/python3.6/site-packages/konlpy/tag/_mecab.py", line 92, in <listcomp>
    for eojeol in phrase.split()]
AttributeError: 'str' object has no attribute 'decode'
>>> import konlpy
>>> konlpy.__version__
'0.5.1'
```

**Comment by minhoryang** [comment]
v0.5.2-rc.1에 #108이 포함되어 있는데, 아직 PyPi에 배포되진 않았습니다.

**Comment by minhoryang** [comment]
v0.5.2가 배포되었습니다! `pip install --upgrade konlpy`로 최신버전을 받으실 수 있습니다!
