### ISSUE TITLE
More POS Tagger support(e.g. KOMORAN / UMorpheme)

### ISSUE THREAD

**Issue by combacsa** [konlpy/konlpy#16]
좀더 다양한 POS Tagger를 Python에서 활용할 수 있도록, 더 많은 wrapper를 제공하는 것도 의미있겠습니다. konlpy 자체의 독립적인 Engine을 구성하기 전에는 좀더 폭넓은 wrapper를 제공하여 저변을 확대하는 것이 좋을지도?

**Comment by e9t** [comment]
최근 Mecab, Komoran, Twitter(twitter-korean-text), Kkma, Hannanum 등 다섯가지 POS tagger들이 포함되었습니다. 앞으로 @combacsa 님께서 제안해주신대로, 더 많은 POS tagger들을 포함시키는 것을 장기적인 KoNLPy 프로젝트의 목표 중 하나로 두면 좋을 것 같습니다 :) @combacsa 님, 중요한 철학을 제안해주셔서 감사합니다.

일단은 어느 정도의 목표 달성을 했다고 생각하고 본 이슈는 닫도록 하겠습니다.
앞으로 추가할만한 다른 POS tagger를 발견하시는 분은, 새로운 이슈를 열어주시면 감사하겠습니다.
