### ISSUE TITLE
RuntimeError: 오류

### ISSUE THREAD

**Issue by ghost** [konlpy/konlpy#163]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-b817489e93d1> in <module>()
----> 1 tagger=Twitter()

C:\Users\sana2\Anaconda3\lib\site-packages\konlpy\tag\_twitter.py in __init__(self, jvmpath)
     70     def __init__(self, jvmpath=None):
     71         if not jpype.isJVMStarted():
---> 72             jvm.init_jvm(jvmpath)
     73 
     74         tktJavaPackage = jpype.JPackage('kr.lucypark.tkt')

C:\Users\sana2\Anaconda3\lib\site-packages\konlpy\jvm.py in init_jvm(jvmpath)
     49         jpype.startJVM(jvmpath, '-Djava.class.path=%s' % classpath,
     50                                 '-Dfile.encoding=UTF8',
---> 51                                 '-ea', '-Xmx768m')
     52     else:
     53         raise ValueError("Please specify the JVM path.")

C:\Users\sana2\Anaconda3\lib\site-packages\jpype\_core.py in startJVM(jvm, *args)
     48     :param args: Arguments to give to the JVM
     49     """
---> 50     _jpype.startup(jvm, tuple(args), True)
     51     _jclass._initialize()
     52     _jarray._initialize()

RuntimeError:

**Comment by minhoryang** [comment]
user accounts that have been deleted.
