### ISSUE TITLE
konlpy 설치가 너무 오래 걸려요.

### ISSUE THREAD

**Issue by jiwonroy-lee** [konlpy/konlpy#167]
이전에 설치해서 테스트를 잘 했엇는데 학교 컴퓨터 다 보니 리셋이 되어서 그런지,, 자바 home설정도 완료하였는데 konlpy 설치가 다섯시간 걸린다고 뜨고, 설치도 10%정도 후에 에러가 납니다ㅜ 왜 그럴까요?

**Comment by weeklyky** [comment]
한번더해보세요 저도 아까 11시쯤 그랫는데 지금괜찮은거같아요
