### ISSUE TITLE
Ubuntu16.04에 anaconda3 사용시 konlpy 설치

### ISSUE THREAD

**Issue by kss530a** [konlpy/konlpy#168]
우분투 환경에서 설치가이드를 따라 설치하였는데
anaconda를 사용해서 그런지 바로 적용이 안되네요ㅠㅠ
어떻게 하면 anaconda interpreter에 konlpy를 적용시킬 수 있나요?

**Comment by kss530a** [comment]
자문자답이 되었네요~ 누군가에게는 도움이 되길 ㅠㅠ
설치 명령어가 pip3 install konlpy 으로 되어있는데
앞에 python -m을 붙여서 'python -m pip3 install konlpy' 으로  설치하면
현재 사용하고 있는 python interpreter(이 케이스에선 anaconda)에 설치가 됩니다

**Comment by blissray** [comment]
-m 이 중요한건 아니고, 아마, pip3 는 ubuntu 기본 인터프리터이고 ananconda 설치후에는 pip의 위치가 바꼈을거 같습니다. 

which pip3
which pip

로 각 명령어의 위치를 확인해보시기 바랍니다.
