### ISSUE TITLE
형태소 차트에 태그가 빠진 이슈

### ISSUE THREAD

**Issue by rudvlf0413** [konlpy/konlpy#169]
형태소 차트에 태그들 정리해 둔 구글 스프레드시트에
https://docs.google.com/spreadsheets/d/1OGAjUvalBuX-oZvZ_-9tEfYD2gQe7hTGsgUpiiBSXI8/edit?ts=5a0d65d6#gid=0

Twitter 모듈 경우 Email, URL 태그가 빠져 있습니다. 추가 부탁드립니다.
(제가 추가하려고 하니 권한이 없어서 깃헙 이슈에다 올립니다!)

**Comment by e9t** [comment]
안녕하세요, 공유 감사합니다.
덕분에 반영 완료했습니다 :)

박은정 드림

--
*박은정 (Lucy Park)*
"Give thanks"
lucypark.kr / @echojuliett <http://twitter.com/echojuliett>

2017-11-16 19:24 GMT+09:00 Kyeongpil Kang <notifications@github.com>:
