### ISSUE TITLE
TypeError: Package kr.lucypark.tkt.TktInterface is not Callable

### ISSUE THREAD

**Issue by SeungyounShin** [konlpy/konlpy#171]
우선 간단한 코드인데
from collections import Counter
from konlpy.tag import Twitter, Komoran
import pytagcloud
import jpype
jpype.startJVM(jpype.getDefaultJVMPath())
jpype.attachThreadToJVM()

text =  open('/Users/seungyoun/Desktop/unist_admission_analysis/unist_admission_data.txt').read()

nlp = Twitter()
nouns = nlp.nouns(text)
print(nouns)

제목과 같은 오류가 뜹니다.
다른 이슈들도 보고 

자바 버젼은
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed modseunseseusessssssss
컴퓨터는
MacBook Air (13-inch, Early 2015)
JPype 직접 빌드해서 JPype1-0.6.2 설치했습니다.

임포트할때는 오류가 안나는데 이 코드 부분에서 오류가 나내요 ㅠㅠ 
`nouns = nlp.nouns(text)`

**Comment by realmovestar** [comment]
자바 버전이 1.7 이상이어야 될거에요
