### ISSUE TITLE
Mecab "NameError: global name 'Taager' is not define.

### ISSUE THREAD

**Issue by YongwoonJang** [konlpy/konlpy#182]
안녕하세요.
아래와 같이 Mecap 설치를 완료하였습니다. 
직접 import하여 객체 생성을 하려고 하는데 제목과 같은 Error가 발생하네요. 

1. Mebcap 설치 완료. 
    wget https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
    tar -zxvf mecab-*-ko-*.tar.gz
    cd mecab-*-ko-*
    ./configure
    make
    make check
    sudo make install

2. macap dic 설치
    wget https://bitbucket.org/eunjeon/mecab-ko-dic/downloads/mecab-ko-dic-2.0.1-20150920.tar.gz
    tar -zxvf mecab-ko-dic-2.0.1-20150920.tar.gz
    cd mecab-ko-dic-2.0.1-20150920/
    ./autogen.sh
    ./configure
    make
    sudo make install

3. script 수행
    $ sudo yum install curl
    $ bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)

하였으나, 아래와 같은 에러가 발생합니다. 

 File "/usr/lib/python2.7/site-packages/konlpy/tag/_mecab.py", line 102, in __init
    self.tagger = Tagger('-d %s' % dicpath)
NameError: global name 'Tagger' is not defined

운영체제는 centos 7.3.1708을 사용하고 있습니다. 
이전 Issue로 처리한 것으로 알고 있는데, (#79 , #144 (2017년 5월 23일 reopen/by rohjoon), #11 (Closed 되었으나 Code에는 반영되지 않음.) 확인 부탁드립니다.

**Comment by ho9science** [comment]
#183 
운영체제 권한 문제인 것 같은데요 71,72에 sudo를 추가하고 ./mecab.sh 로 실행해보세요

**Comment by jo8937** [comment]
저도 같은 에러가 났었는데, 검색해보니 이하와같은 문서가 나와서 커맨드 쳐보니 해결되더군요.

https://qiita.com/sogawa@github/items/fd9bdaf8df27335f9a65

```
$ mecab-config --libs-only-L | sudo tee /etc/ld.so.conf.d/mecab.conf
$ sudo ldconfig
```

**Comment by YongwoonJang** [comment]
최초 CentOS 환경을 사용하지 않고 Ubuntu 환경에서 수행했습니다. 
OS의 package-manager의 영향으로 깔리는 프로그램과 깔리지 않는 프로그램이 발생하는 것 같습니다.
Document 문서에 Install 부분에 다양한 OS환경별로 설치하는 내용이 포함되면 좋을 것 같습니다.(#271 을 지지합니다.)

> apt-get install g++ openjdk-8-jdk python3-dev python3-pip curl
> apt-get install python3-bs4
> pip3 -m pip install konlpy
> bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)
