### ISSUE TITLE
NameError: name 'Tagger' is not defined

### ISSUE THREAD

**Issue by kwangje** [konlpy/konlpy#187]
I successfully installed module 'konlpy', but still cannot use mecab with the issue of 'Tagger'
Please let me know how to solve this problem.
And I'm trying to use this code in my colabatory.

`tagger = Mecab()`
`tagger = tagger.morphs`

`---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-44-c01a63aeedd6> in <module>()
----> 1 tagger = Mecab()
      2 tagger = tagger.morphs

/usr/local/lib/python3.6/dist-packages/konlpy/tag/_mecab.py in __init__(self, dicpath)
    100     def __init__(self, dicpath='/usr/local/lib/mecab/dic/mecab-ko-dic'):
    101         try:
--> 102             self.tagger = Tagger('-d %s' % dicpath)
    103             self.tagset = utils.read_json('%s/data/tagset/mecab.json' % utils.installpath)
    104         except RuntimeError:

NameError: name 'Tagger' is not defined`

**Comment by ho9science** [comment]
konlpy를 가상환경에 설치할 때 오류가 발생한다면
직접 mecab-python을 직접 설치해보세요~

(venv)git clone https://bitbucket.org/eunjeon/mecab-python-0.996.git
(venv)cd mecab-python-0.996/
(venv)python3 setup.py build
(venv)python3 setup.py install

**Comment by jo8937** [comment]
same issue #182

**Comment by JasonK94** [comment]
> konlpy를 가상환경에 설치할 때 오류가 발생한다면
> 직접 mecab-python을 직접 설치해보세요~
> 
> (venv)git clone https://bitbucket.org/eunjeon/mecab-python-0.996.git
> (venv)cd mecab-python-0.996/
> (venv)python3 setup.py build
> (venv)python3 setup.py install

드디어 됐습니다 정말 고마워요 ㅠㅠ 미치는줄알았다이거해결하느라......

**Comment by minhoryang** [comment]
Resolved at #188

**Comment by rumbarum** [comment]
FYI :
- pip install mecab-python3 하셔도 됩니다.
