### ISSUE TITLE
Mecab 객체 생성시 에러 in Colabatory

### ISSUE THREAD

**Issue by kwangje** [konlpy/konlpy#188]
Colabatory 에서 mecab 을 사용하려고 합니다.
(mac 을 사용하고 있습니다)

!pip3 install konlpy 
를 통해 Mecab 을 설치하였고,
from konlpy.tag import Mecab
다음과 같은 import 도 이상없이 실행되었습니다.

하지만 NameError: name 'Tagger' is not defined
라는 에러메시지와 함께 Mecab 객체 생성을 할수 없더라고요.

인터넷을 열심히 검색해서 git 으로 직접 다운로드 받고 setup.py 를 install 해봤으나
나오는 에러메시지가 어떤 의미인지 잘 모르겠습니다 ㅠㅠ
mecab-config 를 찾을 수 없다는게 무슨 의미이고 어떻게 해결할 수 있을까요 ㅠㅠ

mecab 을 꼭 사용해보고 싶은 초보 개발자에게 도움 부탁드릴게요 !!!

![image](https://user-images.githubusercontent.com/20301407/39095144-dda4d7e0-4676-11e8-9f4a-3a6035a164da.png)

**Comment by ho9science** [comment]
konlpy는 자연어처리를 위한 파이썬 패키지입니다.

mecab은 은전한닢에서 제공하는 형태소 분석기이고 별도로 설치해야 합니다.

mecab을 사용하기 위해 설치해야 되는 패키지는 mecab-ko, mecab-ko-dic, mecab-python 총 세가지로

konlpy 메뉴얼대로 진행하면 됩니다.

[http://konlpy-ko.readthedocs.io/ko/v0.4.4/install/#id1](http://konlpy-ko.readthedocs.io/ko/v0.4.4/install/#id1)


collaboratory에서 위 설치문서의 bash가 동작하지 않아서

**Colaboratory** 에서 mecab을 설치하여 konlpy에서 사용할 수 있도록 만들어 보았습니다.
[Install KoNLPy in colaboratory](https://github.com/ho9science/konlpy/blob/develop/install_konlpy.ipynb)

잘 사용하시길 바랍니다.

**Comment by kwangje** [comment]
정말 잘 작동합니다 ㅠㅠㅠㅠ 
의미있는 연구하는데 활용할 수 있도록 노력하겠습니다! 
감사합니다 :D

**Comment by InhyeokYoo** [comment]
저는 왜 작동 안하죠.. ㅠㅠ

**Comment by minhoryang** [comment]
@InhyeokYoo 한번 여기를 참고해 보시겠어요?
https://colab.research.google.com/drive/1HNhMdVjsdOMSCW21zcbMHSDNRLoWmml9#scrollTo=V3OjCAdORQaB&sandboxMode=true

**Comment by minhoryang** [comment]
@InhyeokYoo ping?

**Comment by saekomdalkom** [comment]
https://sanghyu.tistory.com/170
