### ISSUE TITLE
Unicode decode error 관련 문의드립니다.

### ISSUE THREAD

**Issue by mimic-kitsch** [konlpy/konlpy#195]
안녕하세요? anaconda python 2.7 환경에서 konlpy를 사용코자 하는데,
아래와 같은 에러가 돌아오는 이유가 무엇인지 확인 부탁드립니다.

from konlpy.tag import Kkma
text = '한글 텍스트 시험중'
print(Kkma().sentences(text))

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
C:\Users\USER\Anaconda2\lib\site-packages\IPython\core\interactiveshell.pyc in run_code(self, code_obj, result)
   2897             if result is not None:
   2898                 result.error_in_exec = sys.exc_info()[1]
-> 2899             self.showtraceback()
   2900         else:
   2901             outflag = 0

C:\Users\USER\Anaconda2\lib\site-packages\IPython\core\interactiveshell.pyc in showtraceback(self, exc_tuple, filename, tb_offset, exception_only)
   1824                     except Exception:
   1825                         stb = self.InteractiveTB.structured_traceback(etype,
-> 1826                                             value, tb, tb_offset=tb_offset)
   1827 
   1828                     self._showtraceback(etype, value, stb)

C:\Users\USER\Anaconda2\lib\site-packages\IPython\core\ultratb.pyc in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1410         self.tb = tb
   1411         return FormattedTB.structured_traceback(
-> 1412             self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1413 
   1414 

C:\Users\USER\Anaconda2\lib\site-packages\IPython\core\ultratb.pyc in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1318             # Verbose modes need a full traceback
   1319             return VerboseTB.structured_traceback(
-> 1320                 self, etype, value, tb, tb_offset, number_of_lines_of_context
   1321             )
   1322         else:

C:\Users\USER\Anaconda2\lib\site-packages\IPython\core\ultratb.pyc in structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1168 
   1169         formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
-> 1170                                                                tb_offset)
   1171 
   1172         colors = self.Colors  # just a shorthand + quicker name lookup

C:\Users\USER\Anaconda2\lib\site-packages\IPython\core\ultratb.pyc in format_exception_as_a_whole(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)
   1111             return ""
   1112 
-> 1113         last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
   1114 
   1115         frames = self.format_records(records, last_unique, recursion_repeat)

C:\Users\USER\Anaconda2\lib\site-packages\IPython\core\ultratb.pyc in find_recursion(etype, value, records)
    453     # quarter of the traceback (250 frames by default) is repeats, and find the
    454     # first frame (from in to out) that looks different.
--> 455     if not is_recursion_error(etype, value, records):
    456         return len(records), 0
    457 

C:\Users\USER\Anaconda2\lib\site-packages\IPython\core\ultratb.pyc in is_recursion_error(etype, value, records)
    439     # a recursion error.
    440     return (etype is recursion_error_type) \
--> 441            and "recursion" in str(value).lower() \
    442            and len(records) > 500
    443 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 73: ordinal not in range(128)

**Comment by daewonyoon** [comment]
```
text = u'한글 텍스트 시험중'

for sentence in Kkma().sentences(text):
    print sentence
```

**Comment by nyanye** [comment]
Python 2.* 버젼에서는 utf-8 인코딩이 선언되지 않은 경우 기본적으로 문자열을 ascii로 처리하기 때문에 UnicodeDecodeError등의 문제가 발생할 수 있습니다.
@daewonyoon님이 작성해주신 코드처럼 ```u'문자열'```을 이용하시거나 스크립트의 최상단에
```# -*- coding: utf-8 -*-```을 작성해주세요.
