### ISSUE TITLE
TypeError: Package kr.lucypark.tkt.TktInterface is not Callable

### ISSUE THREAD

**Issue by KangTeagyu** [konlpy/konlpy#196]
from konlpy.tag import Twitter
#import nltk
twitter = Twitter()

def read_data(filename):
    with open(filename,'r', encoding="UTF8") as f:
        data = [line.split() for line in f.read().splitlines()]
    return data

def tokenize(doc):
    return ['/'.join(t) for t in twitter.pos(doc, norm=True, stem=True)]

#영화 데이터 읽고 형태소 분류
train_data = read_data('어벤져스.txt')

#token=[]
print(len(train_data))#915줄이 나옴

for i in range(len(train_data)):#0~914까지 돌고
    for j in range(len(train_data[i])):
        token=tokenize(train_data[i][j])
        print(token)

**# 결과 값** 
Traceback (most recent call last):
  File "C:\Users\강태규\Desktop\형태소.py", line 3, in <module>
    twitter = Twitter()
  File "C:\Users\강태규\AppData\Local\Programs\Python\Python36\lib\site-packages\konlpy\tag\_twitter.py", line 76, in __init__
    self.jki = TktInterfaceJavaClass()
  File "C:\Users\강태규\AppData\Local\Programs\Python\Python36\lib\site-packages\jpype\_jpackage.py", line 62, in __call__
    raise TypeError("Package {0} is not Callable".format(self.__name))
TypeError: Package kr.lucypark.tkt.TktInterface is not Callable

라고 나옵니다. 

Kkma도 같은 오류가 나옵니다.

window10 education 64bit
Python 3.6 64bit 
JPype1-0.6.3-cp36-cp36m-win_amd64 설치
konlpy 0.4.4 설치
jdk 1.8.0_171설치 

환경변수 
JAVA_HOME C:\Program Files\Java\jdk1.8.0_171 설정 완료
Path 도 설정완료

했는데도 저런 에러가 뜨는데 어떻게 해결해야할까요 ㅠㅠ
파이썬 입문자라 쉽게 설명해주시면 감사하겠습니다.ㅠㅠ

**Comment by dkQkdhkgkaRpfhfdmf** [comment]
저도 완전히 같은 환경에서 path 설정하고 비슷한 오류로
보이는 이슈에서 나온 솔루션 전부 시도해 봐도 같은 오류가 뜹니다.

**Comment by KangTeagyu** [comment]
저는 컴푸터 사용자 이름 영어로 바꾸고 모두다(파이썬 자바등) 32비트로 맞춰서 해결했습니다 ㅎㅎㅎ
