### ISSUE TITLE
JVM heap memory 제약

### ISSUE THREAD

**Issue by lovit** [konlpy/konlpy#199]
- jpype 로 JVM 을 구동할 때, heap memory 최대값을 설정하지 않으면 KoNLPy 사용 중 메모리가 계속 증가하는 현상이 있습니다.
  - 최대값 설정을 하지 않으면 64 bit 기준 32 gb, 32 bit 기준 1 gb 을 기본값으로 설정합니다.
  - 메모리가 부족하기 전까지 gc 가 작동하지 않아 불필요하게 메모리를 쌓아두는 것으로 추정됩니다.
- konlpy.tag 안의 각 Tagger 들의 __init__ 에 heap memory 를 설정할 수 있도록 argument 를 받도록 하면 각자의 상황에 맞게 메모리를 조절할 수 있을 것이라 생각됩니다.

**Comment by e9t** [comment]
Related: https://github.com/konlpy/konlpy/issues/178
