### ISSUE TITLE
koshort ♥ konlpy 

### ISSUE THREAD

**Issue by nyanye** [konlpy/konlpy#202]
# [Koshort](https://koshort.github.io/) :purple_heart: KoNLPy

안녕하세요. koshort/konlpy의  개발자 nyanye입니다 :cat:
koshort은 konlpy의 철학을 공유하는 한국어 NLP를 위한 high-level API 프로젝트로, 다음과 같은 하위 프로젝트를 포함합니다.

> ## [Koshort (코숏): 파이썬 한국어 온라인 트렌드 스트리밍](http://koshort.readthedocs.io/ko/latest/)
> 
> `pip install koshort`
> 
> 네이버 실시간 검색어, 트위터 실시간 트윗에 대한 비동기 스트리밍 API와 데이터 파이프라인을 제공하는 패키지.
> 
> ## [Pyeunjeon (파이은전): 은전한닢 프로젝트와 mecab 기반의 한국어 형태소 분석기의 독립형 python 인터페이스](https://github.com/koshort/peunjeon)
> 
> `pip install eunjeon`
> 
> 한국어 형태소 분석 프로젝트인 은전한닢 프로젝트의 독립형 python 인터페이스.  API는 KoNLPy 스타일을 따르며 이제 누구나 어느 OS(Windows, Mac, Linux)에서나 손쉽게 형태소 분석을 시작할 수 있습니다.
> 
> ## [Goorm (구름): 한국어를 위한 wordcloud wrapper](https://github.com/koshort/goorm)
> 
> `pip install goorm`
> 
> 파이썬으로 손쉽게 wordcloud를 그려주는 패키지. wordcloud를 이용하여 이제 누구나 한국어 단어만으로도 wordcloud를 만들 수 있습니다. (2017년에 작업했었으나 당시에는 못 써먹을 물건이었기에 업데이트)

지난 8월 9일, lucypark(@e9t) 님과 함께 konlpy와 koshort 프로젝트의 통합(koshort이 konlpy 패키지 / 저장소 속으로 통합될 예정)에 대한 의견을 얘기했으며 통합의 구체적인 방법을 설정하고 있습니다.  

통합을 통해서 예상되는 기대되는 점은 다음과 같습니다.

* 더 큰 커뮤니티에서 더 많은 피드백과 contribution 받기  
* 더 많은 사용자에게 사용되기  
* 한국어 NLP 사용자들에게 도구들의 접근성 높이기

통합이 진행되더라도 기존의 koshort 프로젝트의 github 저장소와 pip 패키지는 보존되며, 추후에 이뤄지는 업데이트는 konlpy에서 진행할 예정입니다.

제가 생각한 통합의 순서는 다음과 같습니다.

```
koshort / pyeunjeon -> goorm
```

아래는 각 패키지들의 통합에 필요한 대략적인 TODO들입니다. 

## TODO: Koshort

* 📦 dependency / system 요구사항 설정 및 setup.py 변경
    * 현재 koshort의 일부 API는 python 2.x 버젼과 완전히 호환되지 않습니다.
* Python API 통합  
    * 방법 1) konlpy의 subpackage로 통합 i.e) `konlpy.koshort`  
    * 방법 2) konlpy와 겹치지 않는 기능만을 통합 i.e) `koshort.stream -> konlpy.stream`
* Command-line API 통합
    * koshort에서는 command-line API를 통한 크롤링을 지원합니다.
```
# command-line API example
$ stream_naver
display_rank = False
filename = trends.txt
interval = 60
n_limits = 10
verbose = True
정성종
버닝
나의 아저씨
이소윤
국가장학금
```
* Readthedocs 문서 통합
* Coding convention 통합 (필요한 경우)
    * 현재 koshort은 numpy & google style docstring 주석을 사용하고 있습니다. 
* unit-test 통합

## TODO: pyeunjeon (Windows 호환가능 mecab wrapper)

pyeunjeon의 경우, konlpy와 동일한 style의 python API를 채택하였기 때문에 실제 konlpy 사용상의 변화는 없으나, Windows에서도 mecab tagger를 사용할 수 있도록 변경할 생각입니다.

* 📦 dependency / system 요구사항 설정 및 setup.py 변경

## TODO: goorm 

* 📦 dependency / system 요구사항 설정 및 setup.py 변경
* 📦 subpackage로 통합

---

konlpy와 koshort 프로젝트의 통합과 방법론에 대한 다양한 피드백을 기다리고 있으며, 추후 pull request를 통해 지속적인 통합을 진행할 예정입니다. 감사합니다 😆

**Comment by jimin030** [comment]
eunjeon에서 mecab을 사용하려고 하는데 사용자 사전은 어떻게 추가할 수 있을까요??

**Comment by minhoryang** [comment]
@jimin030 안녕하세요. 해당 문의를 새 이슈로 만들어서 올려주시면 감사하겠습니다! 이미 닫힌 이슈이기에 원작자나 도움을 주실 수 있는 분들이 찾아보기 힘든 위치에 있습니다.
