### ISSUE TITLE
품사를 변경하는 것이 가능한가요?

### ISSUE THREAD

**Issue by x2ever** [konlpy/konlpy#203]
형용사 :  아름다운  => 명사형 : 아름다움  or  동사형 :  아름답다

위와 같이 특정 품사를 다른 포맷으로 재구성할 수 있는지 궁금합니다. 감사합니다.

**Comment by nyanye** [comment]
질문해주신 변형은 품사의 변경보단 어미의 변경이 맞겠네요!  아쉽게도 KoNLPy의 현재 기능은 품사의 분류에 중점을 두고 있어 어미의 변경은 지원하지 않으나, 품사 분류와 유사하게 사전(dictionary) 기반 변환, 머신러닝 등 알고리즘을 통해서 직접 구현하실 수 있습니다 😸
