### ISSUE TITLE
not worked on Multiprocess

### ISSUE THREAD

**Issue by Ronal92** [konlpy/konlpy#212]
I installed konlpy(kkma) on my ubuntu server.

In python, multiprocess condition

kkma.nouns('detail_text') was not worked!

**Comment by 97dawn** [comment]
I tried multithreading and it worked

**Comment by minhoryang** [comment]
#285
Load konlpy taggers at the process initializer stage (specially `initializer` parameter in [multiprocessing.Pool](https://docs.python.org/ko/3/library/multiprocessing.html#multiprocessing.pool.Pool))
