### ISSUE TITLE
konlpy 실행오류

### ISSUE THREAD

**Issue by colers** [konlpy/konlpy#225]
from konlpy.tag import Kkma
kkma = Kkma()
위에 문장을 쥬피터에서 실행하고나면 아래처럼 애러가 나오네요

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-30-8f53bdc3fe0a> in <module>
      1 from konlpy.tag import Kkma
----> 2 kkma = Kkma()

/opt/conda/lib/python3.6/site-packages/konlpy/tag/_kkma.py in __init__(self, jvmpath, max_heap_size)
     93     def __init__(self, jvmpath=None, max_heap_size=1024):
     94         if not jpype.isJVMStarted():
---> 95             jvm.init_jvm(jvmpath, max_heap_size)
     96 
     97         kkmaJavaPackage = jpype.JPackage('kr.lucypark.kkma')

/opt/conda/lib/python3.6/site-packages/konlpy/jvm.py in init_jvm(jvmpath, max_heap_size)
     53     classpath = os.pathsep.join(f.format(*args) for f in folder_suffix)
     54 
---> 55     jvmpath = jvmpath or jpype.getDefaultJVMPath()
     56 
     57     # NOTE: Temporary patch for Issue #76. Erase when possible.

/opt/conda/lib/python3.6/site-packages/jpype/_core.py in get_default_jvm_path()
    119         finder = LinuxJVMFinder()
    120 
--> 121     return finder.get_jvm_path()
    122 
    123 # Naming compatibility

/opt/conda/lib/python3.6/site-packages/jpype/_jvmfinder.py in get_jvm_path(self)
    129         for method in self._methods:
    130             try:
--> 131                 jvm = method()
    132 
    133                 # If found check the architecture

/opt/conda/lib/python3.6/site-packages/jpype/_jvmfinder.py in _get_from_known_locations(self)
    182         :return: The path to the JVM library, or None
    183         """
--> 184         for home in self.find_possible_homes(self._locations):
    185             jvm = self.find_libjvm(home)
    186             if jvm is not None:

/opt/conda/lib/python3.6/site-packages/jpype/_jvmfinder.py in find_possible_homes(self, parents)
     95 
     96         for parent in parents:
---> 97             for childname in sorted(os.listdir(parent)):
     98                 # Compute the real path
     99                 path = os.path.realpath(os.path.join(parent, childname))

FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/jvm'

폴더가 없다는데... 어떻게 해결해야할지를 모르겠습니다. 도움부탁 드려요 ㅜㅜ
KONLPY 0.5.1 JPYPE 0.6.3 이 설치뙤어있습니다

**Comment by spikeekips** [comment]
java home path를 지정하시면 될 거 같은데요, 
https://github.com/konlpy/konlpy/blob/59c8688ad2fc53a3bc59610694b7a19e058fb5af/test/test_hannanum.py#L9-L12

에서처럼 `init_jvm()`에 `jvm_path`를 지정해주면 될 거 같아요.

```python
from konlpy import init_jvm
from konlpy.tag import Kkma

init_jvm("<JAVA_HOME>")
kkma = Kkma()
```

**Comment by minhoryang** [comment]
@colers JDK가 깔려있는지부터 확인해 봐야 할 것 같습니다. 아직도 같은 문제를 겪고 계신지 알려주시겠습니까?

**Comment by e9t** [comment]
이슈가 오래되어 닫습니다. 문제가 다시 발생하면 이슈를 다시 열어주시기 바랍니다.
