### ISSUE TITLE
import error : hannanum 

### ISSUE THREAD

**Issue by internetian** [konlpy/konlpy#226]
konlpy 설치 후 워드클라우드를 해보려고 실행하는데 아래와 같은 메세지가 뜹니다.
JAVA 설정도 했는데 무엇이 문제인지 도움 부탁드립니다.

Traceback (most recent call last):
  File "D:\PY4E\ABC.py", line 1, in <module>
    from konlpy.tag import hannanum
ImportError: cannot import name 'hannanum' from 'konlpy.tag' (C:\Users\XXX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\konlpy\tag\__init__.py)

**Comment by e9t** [comment]
Hannanum은 클래스이기 때문에 대문자로 표기해주셔야 합니다:

```
from konlpy.tag import Hannanum  # h -> H
```
