### ISSUE TITLE
non-jvm konlpy (possibility?)

### ISSUE THREAD

**Issue by achimkoh** [konlpy/konlpy#231]
안녕하세요! 장기적인 개발 방향(개발 철학?)에 관한 질문입니다.

JVM에 의존하지 않는 방식, 예컨대 순수 파이썬으로 konlpy를 리팩토링한다면 어떤 장단점이 있을지 사용자/개발자분들의 의견을 여쭤보고 싶습니다.

konlpy가 jpype를 사용하는 이유는 태거들이 자바로 만들어져서인 것으로 이해하고 있습니다. 그러므로 코엔엘파이 코드만 수정해서 되는 게 아니라 자바로 구현된 Hannanum, Kkma, Komoran, Okt 또한 파이썬으로 포팅하고 각각 유지관리를 해야 한다(품이 많이 든다)는 게 가장 먼저 생각나는 단점이고요. 퍼포먼스 차이가 어떻게 될지도 고려해볼 문제인 것 같습니다.

장점은 ([jvm OR jpype로 단순 검색했을 때](https://github.com/konlpy/konlpy/issues?q=jvm+OR+jpype&utf8=%E2%9C%93)) 이슈의 약 1/3과 연관되어 보이는 가상 머신 관련 이슈를 근본적으로 다뤄볼 수 있지 않을까? + 나아가 OS설정에 익숙하지 않은 사용자에게 접근성을 넓힐 수 있지 않을까 하는 생각입니다.

개인적으로 파이썬 공부하면서 장기적으로 천천히 도전해보고 싶은 마음이 드는 과업인데, 멋모르고 덤볐다가 괜히 쓸모없는 코드만 생산하게 되는 게 아닐까 하는 걱정도 들어서요. 이런 데 경험이나 관심이 있으신 분들께서 의견을 주시면 감사하겠습니다. 혹시 기존의 기여자분들 사이에서 이런 이야기가 오간 적이 있다면 그 맥락을 알려주시는 것도 좋습니다.

**Comment by minhoryang** [comment]
@achimkoh 안녕하세요. 저도 해당 문제(설치의 어려움으로 인한 진입장벽, multiprocessing, 분산처리, 구버전의 태거를 사용...)에 공감하여 KoNLPy에서 jvm을 걷어내는 프로젝트를 진행해보고 있습니다. https://github.com/minhoryang/konlpy-gRPC
궁극적으로는 사용자들이 (JVM 신경 안쓰고) 클라이언트 라이브러리만 설치하여, 외부에 있는 무료API서버에서 바로 형태소 분석을 경험할 수 있게 해보려합니다. (속도가 느리거나, 많은 양을 처리해야할 경우 물론 서버도 직접 띄울 수 있을 겁니다.)
이 Issue에 Subscribe 눌러놓았으니, 궁금하시거나 관심이 있으시다면 댓글 남겨주시면 감사하겠습니다!
