### ISSUE TITLE
morphs() missing 1 required positional argument: 'phrase'

### ISSUE THREAD

**Issue by HenryYoon** [konlpy/konlpy#237]
형태소 분석을 위해 파이썬에서
from konlpy.corpus import kolaw
c = kolaw.open('constitution.txt').read()
tokens_c = km.morphs(c)
이 코드를 돌렸는데
morphs() missing 1 required positional argument: 'phrase'
이 에러가 자꾸 떠서 어떻게 해결해야 할지 모르겠습니다...
다른 글들 보면 잘 분석되는 것 같은데... 제꺼에선 왜 이러는지 알 길이 없네요...
어떻게 하면 이 에러와 작별할 수 있을까요...?

**Comment by e9t** [comment]
혹시 `km.morphs`에서 `km`은 뭔가요?
아래와 같이 실행해주신건가요?

```
from konlpy.tag import Kkma
km = Kkma()
```

말씀하신대로 이상이 없어야 할 것 같은데, 실행 환경(파이썬 버전, KoNLPy 버전, OS 등)을 좀 더 알려주시면 저 또는 다른 분들이 도와주실 수 있을 것 같습니다. 혹시 문제가 지속되고 있는 경우 이슈를 다시 열어주시면 감사하겠습니다.

**Comment by hccho2** [comment]
```
from konlpy.tag import Kkma
kkma = Kkma()
kkma ('안녕하세요')
```
이런 식으로 하시면 됩니다.

**Comment by HenryYoon** [comment]
> ```
> from konlpy.tag import Kkma
> Kkma('안녕하세요')
> ```
> 
> 
> 이렇게 했을 때 발생하는 error입니다.
> 
> 
> ```
> from konlpy.tag import Kkma
> kkma = Kkma()
> kkma ('안녕하세요')
> ```
> 
> 
> 이런 식으로 하시면 됩니다.

아 감사합니다! 
제가 1년 전에 올린 이슈에 답해주시다니 ㅎㅎ
덕분에 해결된 것 같습니다!
