### ISSUE TITLE
Komoran, Twitter를 scikit-learn의 TruncatedSVD와 함께 사용시 139 메모리 에러

### ISSUE THREAD

**Issue by kangbok** [konlpy/konlpy#238]
안녕하세요. konlpy와 scikit-learn을 함께 사용하는 도중에 메모리 segmentation 에러 코드인 139 에러가 발생하여 이슈 올립니다.
조금 더 자세히 설명드리면 konlpy의 형태소 분석기 중 Komoran, Twitter 객체를 선언한 후 scikit-learn의 TruncatedSVD 클래스의 fit 메소드를 호출시 발생합니다. (Mecab을 이용할 시에는 발생하지 않습니다.)

아래 코드를 바로 복사-붙여넣기 하여 테스트 가능하시니 참고하세요.

========================================================
```python
import random

from konlpy.tag import Komoran
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

### 코모란 객체 생성
a = Komoran()

### 임의 텍스트 데이터 만들기
X = []
for _ in range(200):
    X.append(str(random.randrange(0, 300)))

### TF-IDF matrix 만들기
tv = TfidfVectorizer()
tfidf_model = tv.fit(X)
tfidf_matrix = tfidf_model.transform(X)

### LSA 수행
tsvd = TruncatedSVD(n_components=100)
lsa_model = tsvd.fit(tfidf_matrix)
```

========================================================
실행시 콘솔에 나오는 메시지

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

========================================================

개발 환경
- OS : ubuntu 16.04
- python 3.5
- konlpy 0.5.1
- scikit-learn 0.21.2
- IDE : pycharm community edition 2019.1.2

**Comment by minhoryang** [comment]
해당 코드를 MacOS에서 실행하였을 때는 잘 수행이 되었는데, Linux(Docker)에서 실행하였을 때는 똑같이 139가 떳습니다. 재현되었으니 더 확인해보겠습니다.

**Comment by minhoryang** [comment]
gdb로 확인해 본 결과 scikit이 openblas를 쓰는데, 이것과 충돌이 있는것 같습니다.
아래 명령으로 openblas가 사용하는 스레드를 제한하니 jpype와 충돌하지 않는 것을 확인하였습니다.
```bash
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export OMP_NUM_THREADS=1
```

**Comment by kangbok** [comment]
감사합니다.
