### ISSUE TITLE
startJVM 호출 실패

### ISSUE THREAD

**Issue by limited107** [konlpy/konlpy#24]
jpype.startJVM 호출이 안됩니다.
### 실행환경
- Ubuntu 12.04, x64
- OpenJDK 1.7
- Python 2.7
### 패키지 설치

```
$ pip install JPype1
$ pip install konlpy
```
### Python console

```
 >>> import jpype
 >>> p = jpype.getDefaultJVMPath()
 >>> jpype.startJVM( p )
```
### 오류코드

<pre>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/jpype/_core.py", line 45, in startJVM
    _jclass._initialize()
  File "/usr/local/lib/python2.7/dist-packages/jpype/_jclass.py", line 43, in _initialize
    _JAVAOBJECT = JClass("java.lang.Object")
  File "/usr/local/lib/python2.7/dist-packages/jpype/_jclass.py", line 58, in JClass
    raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
AttributeError: 'NoneType' object has no attribute 'PYEXC'
</pre>

**Comment by lkiung** [comment]
이거 같은 이유로 윈도우에서 고생하다가 이유를 찾았습니다
초기에 JAVA_HOME이 정의되지 않은 상태에서 설치하면 이후에 JAVA_HOME을 설정해도 안되는거더군요

**Comment by NamsooCho** [comment]
Ubuntu 16.04 (64bit), JDK8(64bit), Python3.5(64bit), Jpype rebuild
상황입니다.
JAVA_HOME도 설정되어 있습니다.
이 상황이 몇일 전까지는 잘 동작하던게 오늘부터 이런 현상이 나타납니다.
원인을 모르겠습니다.

**Comment by chihoonj** [comment]
예전에 제가 같은 문제에 봉착했을 때 코드를 분석해봤을때는 java_home찾는 로직에 문제가 있었습니다. 제 경우 직접 소스단에서 java_home을 설정해주는 것으로 임시로 해결했습니다. 급하게 쓰셔야되는 상황이면 소스 내부의 java_home 찾는 로직 부분에서 본인의 java sdk 설치 경로를 입력해보세요.

**Comment by NamsooCho** [comment]
네에 조언 감사합니다.

setup.py의 java_home 변수에 직접 값을 대입하고 rebuild도 해보았습니다.

**Comment by chihoonj** [comment]
예전 소스 찾아보니

kkma = Kkma("C:/Program Files (x86)/Java/jre6/bin/client/jvm.dll")

이런식으로 했었네요. 당시에 윈도우즈, 리눅스, 맥 다 사양했어야돼서 이부분은 윈도우즈 부분이었네요. 혹시 도움이 된다면 좋겠습니다. 그리고 jvm_path를 찾는 JPype관련 부분에서 직접 소스를 고쳤던 것 같기도 하네요.

**Comment by NamsooCho** [comment]
Please use "ulimit -c unlimited", then run gdb on the core. I believe that
ubuntu linux-image-4.10.0 has a bug that is preventing multiple JDKs from
starting properly.

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1699772

2017년 6월 28일 오후 3:04, chihoonj <notifications@github.com>님이 작성:

**Comment by chihoonj** [comment]
위에 내용을 보니 저도 다른 라이브러리에서 jvm을 따로 시작하는 것이 문제였습니다. 위 커맨트는 그런 부분 제한을 없애는 방법인 것으로 보이네요.
