### ISSUE TITLE
_core.py 파일 경고

### ISSUE THREAD

**Issue by JungHoon99** [konlpy/konlpy#240]
![image](https://user-images.githubusercontent.com/44799091/60894744-40f76b80-a29e-11e9-8f30-953aad29a50a.png)
konlpy 를 실행 시킬 때마다 이런 경고문이 나오는 이유가 뭘까요??

**Comment by waitonme** [comment]
JPype1 버전이 업데이트 되면서 기존 라이브러리와 맞지 않아 생기는 문제같습니다.
``` 
pip3 uninstall JPype1
pip3 install JPype1==0.6.3
```
으로 버전 낮춰서 해결가능합니다

**Comment by JungHoon99** [comment]
closed #240
