### ISSUE TITLE
파이썬으로 konlpy 실행하는데 에러가떠서 미치겠네요

### ISSUE THREAD

**Issue by hangari123** [konlpy/konlpy#254]
며칠째 해결이 안납니다.. 제발 도와주세요..

from konlpy.tag import Okt

okt = Okt()
malist = okt.pos("아버지 가방에 들어가신다.", norm= True, stem=True)
print(malist)

이렇게 입력을 했을 때 아래와 같이 에러가 뜹니다.

raise TypeError("Package {0} is not Callable".format(self._name))
TypeError: Package <Java package kr.lucypark.okt.OktInterface._name> is not Callable

설정은 http://konlpy.org/en/latest/install/ 여기 참고해서 그대로 진행했는데 왜 안되는건가요?
jvm 패스를 지정하라는 얘기도 있어서 이렇게 하는게 맞는지는 모르겠지만 아래와 같이 진행을 해봤는데요

from konlpy.tag import Okt

okt = Okt("C:\Program Files\Java\jdk-12.0.2\bin\server\jvm.dll")
malist = okt.pos("아버지 가방에 들어가신다.", norm= True, stem=True)
print(malist)

OSError: [WinError 126] JVM DLL not found: C:\Program Files\Java\jdk-12.0.in\server\jvm.dll
	at Win32PlatformAdapter::loadLibrary(D:\Build\Jpype\JPype1-0.7.0\native\common\include\jp_platform_win32.h:57)
	at JPEnv::loadJVM(native\common\jp_env.cpp:179)
	at PyJPModule::startup(native\python\pyjp_module.cpp:159)

이런 에러를 내더라고요.. 이건 근데 C:\Program Files\Java\jdk-12.0.2\bin\server\jvm.dll
이부분에 있는 \bin 에서 \b 이 부분 때문에 경로가 이상하게 들어간거 같아요.. 그렇게 생각한 이유는 C:\Program Files\Java\jdk-12.0.in\server\jvm.dll 이 부분 때문이고요..

아무튼 지금 설정하라는대로 했는데 왜 안되는지 이해가 전혀 안가는 상황이고.. 검색을 해도 이거에 대한 해답이 없더라고요.. 제발 좀 도와주세요..

제 컴퓨터는
윈도우 10 - 64비트
파이썬 - 3.7
pip - 19.2.3
jdk - 12.0.2
jpype - JPype1-0.7.0-cp37-cp37m-win_amd64
java_home 패스 제대로 지정했고요.. 전부 64비트로 설치했습니다.

도대체 왜 안되는걸까요?

**Comment by hangari123** [comment]
from konlpy.tag import Okt
from konlpy import init_jvm

init_jvm("C:\Program Files\Java\jdk-12.0.2\bin\server")

okt = Okt()
malist = okt.pos("아버지 가방에 들어가신다.", norm= True, stem=True)
print(malist)

답변을 살펴보다가 jvm 패스를 이렇게 하는거라고 하셔서 해봤는데 똑같은 에러르 뱉습니다.. 근데 
2\bin 이부분에서 \b 이게 인식이 안되는건가요?.. 이거때매 경로가 잘 안들어가는거 같아서요

**Comment by JeongMyeong** [comment]
해결하셨나요 ? 
같은 부분에서 오류가 납니다.
1달 전에 다른 컴퓨터에서 똑같이 설치 했는데 그때는 오류 한 번 없이 잘 설치했는데 새로운 데스크탑에 설치하다가 오류가 나네요

**Comment by minhoryang** [comment]
추측입니다만 자바버전을 12에서 11로 낮춰보시겠어요? “Package is not callable”의 문제를 해결할 수 있을 것으로 보입니다.

**Comment by JeongMyeong** [comment]
> 추측입니다만 자바버전을 12에서 11로 낮춰보시겠어요? “Package is not callable”의 문제를 해결할 수 있을 것으로 보입니다.

어쩌다 해결 하긴 했는데 어떻게 해결했는지 기록을 못했네요 ㅠㅠ
이것저것 다시 설치하고 해결했습니다. !

**Comment by minhoryang** [comment]
@JeongMyeong 안녕하세요. 해당 이슈를 클로즈 해도 될까요? 나중에 재현된 이후 다시 열어주시면 감사하겠습니다.
