### ISSUE TITLE
현재 konlpy/java 폴더 안의 라이브러리들의 버전을 알고싶습니다.

### ISSUE THREAD

**Issue by minhoryang** [konlpy/konlpy#257]
현재 konlpy/java 폴더 안에 있는 파일들이 개발 가능한 상태인지 확인하고 싶습니다. @e9t 

~~1. `ant compile`명령으로 java파일들을 class로 새로 컴파일하고, jar와 함께 돌려보려 하였으나, 컴파일에 실패하였습니다. (현재 komoran만 시도해 봄)~~

2. @lovit 님이 [Update JAR for Komoran3](https://github.com/konlpy/konlpy/commit/d4bb551efc472bb99053f017d78bab9187fe3f0e) 커밋을 통하여, `Komoran-3.0.jar`파일을 브랜치에 넣어주셨습니다. 해당 파일의 실제 버전이나 [Komoran3 리포](https://github.com/shin285/KOMORAN/releases)에서의 commit hash가 궁금합니다. 

~~3. [Komoran2](https://github.com/shineware/komoran-2.0/blob/master/src/main/java/kr/co/shineware/nlp/komoran/core/analyzer/Komoran.java)에서 [Komoran3](https://github.com/shin285/KOMORAN/blob/master/src/main/java/kr/co/shineware/nlp/komoran/core/Komoran.java)으로 넘어올 때, API의 변화가 있는 것으로 확인되었습니다만, 이게 [KomonanInterface.java](https://github.com/konlpy/konlpy/commits/master/konlpy/java/src/kr/lucypark/komoran/KomoranInterface.java)에 반영되지 않았습니다.~~

제 실력이 부족해서 현재 왜 동작하고 있는지를 이해를 못하고 있는 상황입니다. 도움주시면 감사하겠습니다.

**Comment by minhoryang** [comment]
4. Komoran3에 대해서는 @lovit 님의 [Update Komoran 2.4 -> 3](https://github.com/konlpy/konlpy/commit/f67cf325a02ac99192d425d61a4125b262ef32b0#diff-a70f7a91ddaaf92a96be836838ec43bf) 커밋을 통해 KomoranInterface.java를 쓰지 않는다는 것을 확인하였습니다.

**Comment by minhoryang** [comment]
5. Java 파일들을 빌드할 때, `java.class.version`이 55.0를 넘지 않도록 해야 하네요. 해당하는 Java버전은 11이하입니다. 
```
jpype._jclass.java.lang.UnsupportedClassVersionError: kr/lucypark/okt/OktInterface has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

**Comment by e9t** [comment]
안녕하세요 @minhoryang 님. 질문 답변 드립니다:

1 혹시 컴파일에 실패했을 때 에러메세지가 출력되었을까요?
2. [v3.0.1](https://github.com/shin285/KOMORAN/releases/tag/3.0.1)이 아닐지 추측해봅니다만 정확한것은 기여하신 분께서 답변해주실 수 있을 것 같네요. @lovit 님 혹시 답변 부탁드려도 될까요?
3, 4. 확인 감사합니다. [아래 댓글](https://github.com/konlpy/konlpy/issues/257#issuecomment-540445904)에서 확인해주신대로 `KomoranInterface.java`가 사용되고 않고 있으니 삭제해도 될 것 같네요 :)
5. 확인 감사합니다! 제가 해당 PR을 머지할 때 제대로 확인하지 못한 것 같습니다. [컴파일 할 때 Java의 target 버전을 고정](https://stackoverflow.com/a/16742344/1054939)하는게 좋을 것 같네요.

**Comment by minhoryang** [comment]
@e9t 안녕하세요. `KomoranInterface.java`를 제외하니 빌드는 성공하였습니다. 감사합니다 :)
