### ISSUE TITLE
http://konlpy.org/ko/latest/ 의 문서가 업데이트가 안된것인가요?

### ISSUE THREAD

**Issue by gandol2** [konlpy/konlpy#270]
우선 코드를 공유 해주신것에 감사 드립니다.

http://konlpy.org/ko/latest/ 의 문서에 따라서 설치와 예제 실행을 해보고 있습니다.

설치부터 몇가지가 막혀서 해결하였는데.. (jdk7 설치 이슈) 
실행에서도 계속 막히네요 ㅠㅠ  (import 안되는 등 이슈..)

konlpy.org의 문서가 현재 코드의 버전과 다른것인지요..?

**Comment by minhoryang** [comment]
@gandol2 OS를 말해주시면 한번 재현해보겠습니다. 실행이 안될때의 출력 화면도 적어주시면 감사하겠습니다!

**Comment by minhoryang** [comment]
@gandol2 설치시에도 jdk7관련 이슈를 해결하셨다고 하셨는데, 이 방법도 공유해주신다면 문서에 같이 반영하겠습니다.

**Comment by gandol2** [comment]
클라우드 환경(vultr)의 인스턴스(ubuntu)에서 가볍게 예제를 돌려보다가 생긴 이슈 입니다. 

https://askubuntu.com/questions/761127/how-do-i-install-openjdk-7-on-ubuntu-16-04-or-higher

위 링크를 보니 openjdk-7이 ubuntu에서 지원이 되지 않는다고 하는것 같아서요,

repository를 강제로 추가하고 설치를 하였는데도 정상적으로 설치가 안되서 결국 jdk8버전을 설치하고 해결 하였습니다.

**Comment by minhoryang** [comment]
@gandol2 확인되었습니다! 설치관련해서는 #271 에서 한번에 업데이트 하도록 하겠습니다. 
혹시 실행도 안되시나요?

**Comment by minhoryang** [comment]
@gandol2 문서가 업데이트 되었습니다! 감사합니다!
http://konlpy.org/en/latest/install/
http://konlpy.org/ko/latest/install/
