### ISSUE TITLE
NotFound client\jvm.dll

### ISSUE THREAD

**Issue by jaehyunup** [konlpy/konlpy#278]
# 문제상황
 Okt 외 Hannanum등 모든 분석기에서 'nonus' 메서드만 인식을 못하는 상황

# 문제 발생 코드
```python
from konlpy.tag import Okt
okt=Okt()
print(okt.nonus(u'롯데마트의 흑마늘 양념 치킨이 논란이 되고 있다.'))  
```

# 결과
<module> AttributeError: 'Okt' object has no attribute 'nonus'

**Comment by minhoryang** [comment]
@jaehyunup 안녕하세요. nouns로 다시 시도해주시겠어요?
https://github.com/konlpy/konlpy/search?l=Python&q=nouns

**Comment by jaehyunup** [comment]
@minhoryang 헉 말도안되는실수를했네요..급하게하다보니.. 
감사합니다

**Comment by jaehyunup** [comment]
@minhoryang 혹시 한가지 더 질문드려도 될까요? 
 문제 해결하려고 java 버전 바꾸고 pip uninstall Jpype, konlpy 하고 재설치 하니
not found  C:\\Program Files\\Java\\jre1.8.0_221\\bin\\client\\jvm.dll  에러가 뜨는데요.
client디렉토리가 원래 없어서, 새폴더로 만들어주고 server 디렉토리의 jvm.dll을 붙혀넣으니 정상작동하긴 하는데 어떤 문제가 있는건가요? uninstall이 제대로 안된걸까요?

**Comment by minhoryang** [comment]
@jaehyunup 오... 기존에 설치한 java와 새로 설치한 java의 버전명과 다운로드한 사이트명을 알 수 있을까요?
`not found에러`는 konlpy 재설치 중에 뜬 것이 아니라, 설치 후 사용하는 도중에 뜬 것 아닌가요?
그럴경우 아래 코드로 해결이 될 것 같은데요. 한번 해보시겠어요?
```python3
from konlpy.tag import *
k = Komoran(jvmpath=r"C:\Program Files\Java\jre1.8.0_221\bin\server\jvm.dll")
# Konlpy Tagger의 생성자에 jvmpath를 넣기.
```
