### ISSUE TITLE
TypeError: Package kr.lucypark.okt.OktInterface is not Callable

### ISSUE THREAD

**Issue by whcdmk** [konlpy/konlpy#280]
Kkma, Okt, Hannanum 전부 다 안 되네요.
`from konlpy.tag import Okt` 는 되지만 
`okt = Okt()` 할시에는 
`TypeError: Package kr.lucypark.okt.OktInterface is not Callable` 에러가 뜹니다. 

설치 버젼 
`Windows == Windows Version 10.0.18362.476  x64`
`Python == 3.7.4` (`3.6.5`도 사용)
`java version "1.8.0_231"`
`jpype == 0.7.0` (`0.6.3`도 사용) 
`konlpy == 0.5.1`
`pip/pip3 install Jpype1/Jpype1-py3` 전부 다 사용했습니다. 
`Conda` 와 `PyInstaller`는 둘 다 사용하지 않습니다. 
`Java`도 13.0.1, 12.0.2,1.8.0_191 등 다 깔아보았습니다. 

사용자 환경 변수 
`JAVA_HOME == C:\Program Files\Java\jdk1.8.0_231`
(실제 `jvm.dll`이 들어있는 `C:\Program Files\Java\jdk1.8.0_231\jre\bin\server` 도 사용해봄)
`PATH`에도 `C:\Program Files\Java\jdk1.8.0_231\jre\bin` 포함

재부팅도 여러 번 해보았고요. 
```Python
from konlpy import jvm
jvm.init_jvm()
```
이렇게 할 때는 에러는 나지 않습니다만 
```
C:\Users\홍길동\AppData\Local\Programs\Python\Python37\lib\site-packages\jpype\_core.py:210: UserWarning:
-------------------------------------------------------------------------------
Deprecated: convertStrings was not specified when starting the JVM. The default
behavior in JPype will be False starting in JPype 0.8. The recommended setting
for new code is convertStrings=False.  The legacy value of True was assumed for
this session. If you are a user of an application that reported this warning,
please file a ticket with the developer.
-------------------------------------------------------------------------------
```
이런 경고가 뜨기는 하네요. 

계속 찾아보는데 다른 깃헙 이슈에서도 아직 미해결인 것 같아서 다시 올립니다.

**Comment by whcdmk** [comment]
결국 제 이슈는 파이썬 설치경로가 한글이어서 벌어진 문제였네요. 다른 라이브러리에서는 따로 문제가 없긴 했었는데... 여튼 파이썬을 한글이 없는 경로에 재설치하니 문제가 해결되었습니다.

**Comment by minhoryang** [comment]
@whcdmk 확인해주셔서 감사합니다!
