### ISSUE TITLE
Documentation의 Build Status Badge가 깨집니다.

### ISSUE THREAD

**Issue by minhoryang** [konlpy/konlpy#281]
<img width="600" alt="스크린샷 2019-12-03 오후 5 48 50" src="https://user-images.githubusercontent.com/1270855/70034864-3d6dd380-15f5-11ea-9236-c7f3df370bbc.png">
<img width="544" alt="스크린샷 2019-12-03 오후 5 48 46" src="https://user-images.githubusercontent.com/1270855/70034865-3d6dd380-15f5-11ea-9b1c-761e6f429314.png">

- README.rst: 
https://github.com/konlpy/konlpy/blame/v0.5.2/README.rst#L8
`https://img.shields.io/travis/konlpy/konlpy.svg`

- docs/index.rst:
https://github.com/konlpy/konlpy/blame/v0.5.2/docs/index.rst#L4
`https://travis-ci.org/konlpy/konlpy.svg?branch=master`

TODO:
- [x] 모든사람에게 안보이는지 확인
- [ ] docs/index.rst를 README.rst와 같이 바꿈

**Comment by ujuc** [comment]
## README.rst
![Screen Shot 2019-12-04 at 15 11 57](https://user-images.githubusercontent.com/624975/70117324-85016780-16a8-11ea-9bc7-1fe90c8933cc.png)

## docs/index.rst
![Screen Shot 2019-12-04 at 15 12 11](https://user-images.githubusercontent.com/624975/70117345-93e81a00-16a8-11ea-9be4-e0a8f945e247.png)

둘다 안깨집니다.

**Comment by minhoryang** [comment]
@ujuc 앗! 그렇담 제 DNS서버의 문제인 것 같습니다! 감사합니다!!
