### ISSUE TITLE
Java Index 에러.

### ISSUE THREAD

**Issue by ImKeon** [konlpy/konlpy#286]
java.lang.ArrayIndexOutOfBoundsException: 5000
문장을 토크나이징 시 해당 에러가 출력됩니다.
Java 코드의 인덱싱 문제 같은데. 패키지 어디를 수정해야될지를 모르겠네요..

트랙킹 부탁드릴게요..

**Comment by minhoryang** [comment]
@ImKeon 실행하신 함수랑 해당하는 문장을 알려주시면 감사하겠습니다.

**Comment by ImKeon** [comment]
@minhoryang  

doc_ko = kobill.open('orderDaily_product_name_by_quantity_' + str(x) +'.txt').read()
tokens_ko = hannanum.morphs(doc_ko)

토크나이즈 하는 부분에서 에러가 발생하고 있습니다 (hannanum.morphs)

**Comment by minhoryang** [comment]
@ImKeon “orderDaily_product_name_by_quantity_.txt” 이 파일 전체를 한번에 넣으시는 것으로 보여요
한 문장 한 문장 씩 나눠서 보내야 합니다.
.read()가 아니라 .readlines()로 해서
For문을 돌며 hannanum.morphs()를 호출해주시겠어요?

**Comment by ImKeon** [comment]
@minhoryang 넵 확인했습니다. For문 돌려 함수 호출하도록 할게요. 감사합니다!
