### ISSUE TITLE
konlpy에서 다음과 같은 에러가 나옵니다. TypeError: No matching overloads found for kr.lucypark.okt.OktInterface.tokenize(list,java.lang.Boolean,java.lang.Boolean), options are: 	public java.util.List kr.lucypark.okt.OktInterface.tokenize(java.lang.String,java.lang.Boolean,java.lang.Boolean)

### ISSUE THREAD

**Issue by sophiaanderic** [konlpy/konlpy#288]
안녕하세요 처음 글 써보는거라 이렇게 쓰는게 맞는지 모르겠습니다. 

저는 워드클라우드 연습을 위해 파이썬에서 다음과 같은 코드를 쳤습니다. 

`from konlpy.tag import Okt
from konlpy import jvm
from konlpy.corpus import kolaw
import nltk
from collections import Counter

twitter=Okt()

file = open("d:/study/test.txt", 'r')
data = file.readlines()
file.close()
data

news_word=twitter.nouns(data)`

konlpy는 홈페이지에 나온 순서대로 깔았으며, java는 1.8버전으로 JAVA_HOME 지정까지 홈페이지에 나온대로 설정해 두었습니다. 

그런데 

news_word=twitter.nouns(data)

이 부분에서 자꾸 에러가 나는데요. 
다음과 같은 에러가 뜹니다 ㅠㅠ 

TypeError: No matching overloads found for kr.lucypark.okt.OktInterface.tokenize(list,java.lang.Boolean,java.lang.Boolean), options are:
	public java.util.List kr.lucypark.okt.OktInterface.tokenize(java.lang.String,java.lang.Boolean,java.lang.Boolean)

	at JPMethod::findOverload(native\common\jp_method.cpp:242)
	at JPMethod::findOverload(native\common\jp_method.cpp:245)
	at JPMethod::invoke(native\common\jp_method.cpp:253)
	at PyJPMethod::__call__(native\python\pyjp_method.cpp:167)

자바도 버전별로 몇번이나 지웠다 깔아봤고, konlpy관련된 것들도 파이썬 버젼에 맞게 깔았습니다.
왜 이런 현상이 발생하는 지 모르겠습니다 ㅠㅠ 혹시 아시는 분 계시다면 완전 초보라 자세한 설명 부탁드리겠습니다.

**Comment by minhoryang** [comment]
@sophiaanderic
현재 data는 test.txt의 각 줄을 원소로 하는 문자열 배열입니다.

Konlpy의 함수는 배열을 인자로 받지 않고, 보통 문자열을 받습니다.
이 경우에는 data를 for문을 돌면서 사용하셔야 합니다.
```python
for data in line:
    news_word = twitter.nouns(line)
```
이렇게 얻은 news_word를 적절히 활용하시면 됩니다.

**Comment by aeddung** [comment]
저도 똑같은 문제가 발생하네요.. ㅠㅠ
![image](https://user-images.githubusercontent.com/48937254/73124292-1cb27080-3fdd-11ea-9a47-8284f8cdfc4a.png)

**Comment by minhoryang** [comment]
@aeddung 해당문제는 다른 문제입니다. #291 에서 이어서 이야기하겠습니다.

**Comment by JeongyoonWi** [comment]
tokenized_content = []

for x in data:
    aa = tokenizer(x)
    tokenized_contents.append(aa)
    print(aa)

**_data 예시 : ['Repost', '니아', '키즈', '베이비', '소르니', '키즈', '책장', '아이', '책장', '아이방', '키즈', '가구', '하우스', '책장', '스타', '그램']_**
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-154-ea298caa1f59> in <module>
      2 
      3 for x in data:
----> 4     aa = tokenizer(x)
      5     tokenized_contents.append(aa)
      6     print(aa)

<ipython-input-10-f179ff092e0a> in tokenizer(raw, pos, stopword)
      4             raw,
      5             norm = True,
----> 6             stem = True
      7         )
      8         if len(word) > 1 and tag in pos and word not in stopword

~/opt/anaconda3/lib/python3.7/site-packages/konlpy/tag/_okt.py in pos(self, phrase, norm, stem, join)
     61                     phrase,
     62                     jpype.java.lang.Boolean(norm),
---> 63                     jpype.java.lang.Boolean(stem)).toArray()
     64         if join:
     65             return [t for t in tokens]

TypeError: No matching overloads found for kr.lucypark.okt.OktInterface.tokenize(float,java.lang.Boolean,java.lang.Boolean), options are:
	public java.util.List kr.lucypark.okt.OktInterface.tokenize(java.lang.String,java.lang.Boolean,java.lang.Boolean)

	at findOverload(native/common/jp_method.cpp:242)
	at findOverload(native/common/jp_method.cpp:245)
	at invoke(native/common/jp_method.cpp:253)
	at __call__(native/python/pyjp_method.cpp:167)

이렇게 오류가 발생합니다.

**Comment by JeongyoonWi** [comment]
tokenized_content = []

for x in hashtag:
    aa = tokenizer(x)
    tokenized_contents.append(aa)
    print(aa)


TypeError: No matching overloads found for kr.lucypark.okt.OktInterface.tokenize(float,java.lang.Boolean,java.lang.Boolean), options are:
	public java.util.List kr.lucypark.okt.OktInterface.tokenize(java.lang.String,java.lang.Boolean,java.lang.Boolean)

	at findOverload(native/common/jp_method.cpp:242)
	at findOverload(native/common/jp_method.cpp:245)
	at invoke(native/common/jp_method.cpp:253)
	at __call__(native/python/pyjp_method.cpp:167)

**Comment by HaeyoonJo** [comment]
혹시 도움될까싶어서 저같은 경우엔, 데이터프레임 두개의 컬럼을 합친 후 토큰화하는 과정에서 값이 NaN일 경우 이 오류가 떳었습니다 :)

**Comment by jiyeong1006** [comment]
TypeError: No matching overloads found for kr.lucypark.okt.OktInterface.tokenize(float,java.lang.Boolean,java.lang.Boolean), options are:
	public java.util.List kr.lucypark.okt.OktInterface.tokenize(java.lang.String,java.lang.Boolean,java.lang.Boolean)

저는 용량이 크면 이런문구가 나오고 20줄 이하로 쓰면 잘되는데 이유가 있을까요?

**Comment by minhoryang** [comment]
@jiyeong1006 type mismatch로 보이는데요. 입력하는 데이터에 float type이 껴있지 않은지요.

**Comment by DrumDong** [comment]
TypeError: No matching overloads found for kr.lucypark.kkma.KkmaInterface.extractNoun(float), options are:
public org.snu.ids.ha.index.KeywordList kr.lucypark.kkma.KkmaInterface.extractNoun(java.lang.String)

혹시 이것도 특정 문자열에 숫자로 되어있어서 그런가요?

**Comment by DrumDong** [comment]
> TypeError: No matching overloads found for kr.lucypark.kkma.KkmaInterface.extractNoun(float), options are:
> public org.snu.ids.ha.index.KeywordList kr.lucypark.kkma.KkmaInterface.extractNoun(java.lang.String)
> 
> 혹시 이것도 특정 문자열에 숫자로 되어있어서 그런가요?

NaN값 떄문에 그렇군요.

**Comment by hale-in** [comment]
TypeError: No matching overloads found for kr.lucypark.okt.OktInterface.tokenize(list,java.lang.Boolean,java.lang.Boolean), options are:public java.util.List kr.lucypark.okt.OktInterface.tokenize(java.lang.String,java.lang.Boolean,java.lang.Boolean)

안녕하세요? 현재 저도 같은 에러메시지가 떠서 여쭤봅니다.

from konlpy.utils import pprint
from konlpy.tag import Okt
import pandas as pd
import csv

okt = Okt()
tokenset = []

with open('/content/dataset - data_set_raw.tsv') as f:
tr = csv.reader(f, delimiter='\t')
for row in tr:
token =okt.morphs(row) <----여기서 에러 발생
tokenset.append(token)

---------------------------------------------------------
for문을 통해 배열을 문자열로 바꿔주는데도 이런 문제가 생깁니다
