### ISSUE TITLE
Type error : No matching overloads found for kr.lucypark.jhannanum.comm.HannanumInterface.simplePos09(str)

### ISSUE THREAD

**Issue by rkdqus2006** [konlpy/konlpy#289]
I have installed KoNLPY and taught it's perfect but errors occured

version - Python 3.7 , jdk 13.0.1

Jpype - 0.7.1

OS - window 10, 64bit

IDE - JupyterNotebook
////////////////////////////////////////////////////////////////////
hannanum = Hannanum()
print(hannanum.morphs("난 고래다"))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-b4e931dc697d> in <module>
----> 1 print(hannanum.morphs("난 고래다"))

C:\anaconda\lib\site-packages\konlpy\tag\_hannanum.py in morphs(self, phrase)
    102         """Parse phrase to morphemes."""
    103 
--> 104         return [s for s, t in self.pos(phrase)]
    105 
    106     def __init__(self, jvmpath=None, max_heap_size=1024):

C:\anaconda\lib\site-packages\konlpy\tag\_hannanum.py in pos(self, phrase, ntags, flatten, join)
     86 
     87         if ntags == 9:
---> 88             result = self.jhi.simplePos09(phrase)
     89         elif ntags == 22:
     90             result = self.jhi.simplePos22(phrase)

TypeError: No matching overloads found for kr.lucypark.jhannanum.comm.HannanumInterface.simplePos09(str), options are:
	public java.lang.String kr.lucypark.jhannanum.comm.HannanumInterface.simplePos09(java.lang.String)

	at JPMethod::findOverload(native\common\jp_method.cpp:242)
	at JPMethod::findOverload(native\common\jp_method.cpp:245)
	at JPMethod::invoke(native\common\jp_method.cpp:253)
	at PyJPMethod::__call__(native\python\pyjp_method.cpp:167)

​

**Comment by rkdqus2006** [comment]
I can resolve this problem to make another Anaconda Envir for python 3.6 ver I think the problem has been occured from python version incompatibility

**Comment by heytotoma** [comment]
> I can resolve this problem to make another Anaconda Envir for python 3.6 ver I think the problem has been occured from python version incompatibility

정말 감사합니다. 하루종일 씨름하다가 이제 성공했어요 ㅜㅜ 새벽 3시에
