### ISSUE TITLE
konlpy.about 오류 

### ISSUE THREAD

**Issue by araneeee** [konlpy/konlpy#292]
안녕하세요 konlpy import 관련 오류때문에 질문 드립니다.
konlpy설치 방법에 따라서 자바설치후 자바홈 환경설정을 하였고 그 다음  pip install konlpy하여 성공적으로 설치가 되었습니다. 
그런데 import konlpy를 하는 경우 보지 못한 오류가 발생해서 이렇게 올립니다.

![image](https://user-images.githubusercontent.com/60424901/73342448-ef5a1100-42c1-11ea-9843-441c6f52ee47.png)
![image](https://user-images.githubusercontent.com/60424901/73342505-1284c080-42c2-11ea-99f2-051dc56be6c1.png)

No module named 'konlpy.about' 오류가 발생합니다. 
파일은 잘 설치된 것 같은데 이유를 잘 모르겠습니다.

**Comment by minhoryang** [comment]
큰문제가 없어야하는데요. 저도 처음 보는 문제라 당황스럽습니다.
Jupyter Notebook을 재시작하여도 해당 문제가 안고쳐지는지요?

**Comment by minhoryang** [comment]
@araneeee 저는 Jupyter Notebook 안에서도 잘 실행이 되는데요.
한번 다시 확인해주시겠어요?
https://colab.research.google.com/drive/1HNhMdVjsdOMSCW21zcbMHSDNRLoWmml9#scrollTo=V3OjCAdORQaB&sandboxMode=true

**Comment by araneeee** [comment]
> 안녕하세요 konlpy import 관련 오류때문에 질문 드립니다.
> konlpy설치 방법에 따라서 자바설치후 자바홈 환경설정을 하였고 그 다음 pip install konlpy하여 성공적으로 설치가 되었습니다.
> 그런데 import konlpy를 하는 경우 보지 못한 오류가 발생해서 이렇게 올립니다.
> 
> ![image](https://user-images.githubusercontent.com/60424901/73342448-ef5a1100-42c1-11ea-9843-441c6f52ee47.png)
> ![image](https://user-images.githubusercontent.com/60424901/73342505-1284c080-42c2-11ea-99f2-051dc56be6c1.png)
> 
> No module named 'konlpy.about' 오류가 발생합니다.
> 파일은 잘 설치된 것 같은데 이유를 잘 모르겠습니다.

**Comment by araneeee** [comment]
java 환경변수 설정때문에 문제가 있었던 것 같습니다 해결됐습니다!
