### ISSUE TITLE
konlpy.tag의 Okt 클래스 null 값 처리 개선요청

### ISSUE THREAD

**Issue by ghost** [konlpy/konlpy#295]
처음으로 konlpy를 사용해보는 거라 처음부터 에러가 나와서 좀 당황했었습니다..

코드는 간단히 여러 리뷰가 있는 파일을 가져와서 태그들 뽑아보는 거였는데요;
```
from konlpy.tag import Okt
import pandas as pd

okt = Okt()
data = pd.read_csv('파일경로', columns=['id', 'document', 'label'])

for doc in data['document']:
    print(okt.pos(doc))
```

okt.pos(doc)을 구현하다 보니 다음과 같은 TypeError 에러가 나왔습니다;
```
TypeError: No matching overloads found for kr.lucypark.okt.OktInterface.tokenize(list,java.lang.Boolean,java.lang.Boolean), options are:
	public java.util.List kr.lucypark.okt.OktInterface.tokenize(java.lang.String,java.lang.Boolean,java.lang.Boolean)

	at JPMethod::findOverload(native\common\jp_method.cpp:242)
	at JPMethod::findOverload(native\common\jp_method.cpp:245)
	at JPMethod::invoke(native\common\jp_method.cpp:253)
	at PyJPMethod::__call__(native\python\pyjp_method.cpp:167)
```

처음엔 정확히 무슨 에러인지 몰라서 문서도 찾아보고 구글신에게 문의하고 여기 konlpy 이슈들도 읽어봤는데요,
버전 확인, jpype 재설치 등등의 답변들 밖에 없길래 정확히 어떤 값이 저 에러를 일으키는지 확인해보니,
null값이 들어가면 에러가 나오더라고요.. (제 잘못이긴 한데..)

`okt.pos()`하고 그냥 빈 값으로 진행하면
`TypeError: pos() missing 1 required positional argument: 'phrase'`
이라고 착하게 나오는데
`okt.pos([])`하면은 저 위 에러 '노 매칭 오버로드' 뜨는겁니다.

굳이 심한 이슈가 아니지만 괜한 삽질 안하게쯤
null 값에 대한 exception 처리 좀 개선해주셨으면 합니다~

**Comment by nyanye** [comment]
안녕하세요 :)
KoNLPy의 tagger 클래스들의 pos method들은 공통적으로 str 형식의 입력을 예상하여 동작하고 있는데요,
이 때 ghost님이 확인해주신 문제는 정확히는 'null 값이 들어온 것' 이라기 보다는 str 형식이 아닌 형식의 입력이 들어온 것이라고 할 수 있겠네요!
사용자분들이 이에 대해 인지하고 올바른 입력을 넣을 수 있도록 pos method에서 type을 확인하는 구문을 적용하도록 하겠습니다 :)
https://github.com/konlpy/konlpy/pull/320
