### ISSUE TITLE
반복문에서 세션 다운 현상

### ISSUE THREAD

**Issue by GyuhoonK** [konlpy/konlpy#297]
`hn = Hannanum(max_heap_size = 1024 * 4)`
`data = []`
`for text in tqdm(text_data) :`
`  result = hn.pos(text, n_tags = 22)`
`  data.append(result)`
를 수행했을 때, for 반복문이 6500이 넘어가면 항상 작업이 중지됩니다.
혹시 이런 현상이 발생하는 이유를 알 수 있을까요?

**Comment by minhoryang** [comment]
메모리 부족일 것 같네요.
혹시 그정도 즈음에서 메모리를 얼마나 사용하는지 알 수 있을까요?
그리고 에러메세지도요?

**Comment by GyuhoonK** [comment]
@minhoryang 
에러 메시지를 출력하지 않고, 메모리는 1.8gb 정도 사용한 뒤에 그 상태를 계속 유지합니다.
코랩에서도 똑같은 현상을 보이는데, 데이터셋 자체에 문제가 있는걸까요?

**Comment by minhoryang** [comment]
@gyuhoonk 작업이 중지된다가 프로세스가 종료되는게 아니면 데이터셋의 문제로 보입니다. 어떻게 중지되었음을 알게되셨는지 알 수 있을까요?

**Comment by GyuhoonK** [comment]
@minhoryang
답변 늦어서 죄송합니다.
데이터셋에 문제가 있었습니다. 아마 무한루프였나봐요, progress bar가 진행되지 않고 멈춰있었습니다.
분석기에 sentence = ' '처럼 공백만 존재하는 값이 인풋되었을 때 진행이 되지 않고 멈춰있었습니다.

도움주셔서 감사합니다.
