### ISSUE TITLE
Anaconda python2.7ver SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by argon1025** [konlpy/konlpy#311]
![KakaoTalk_20200704_212122186](https://user-images.githubusercontent.com/55491354/86512392-f8d14180-be3c-11ea-8159-b18af6ed33ad.png)
----
MAC,Window,Linux에서 동일한문제가 발생하여 설치가 되지 않습니다 혹시 도움을 받을 수 있을까요?
구글링해봐도 계속 안되네요 여러대의 컴퓨터에서 시도하였습니다
설치환경은 anaconda python2.7버전입니다
감사합니다.

**Comment by minhoryang** [comment]
python2를 쓰신다면, 아래 문구를 참고하여 konlpy v0.5.2 버전을 설치해보시는게 어떨까요?
```
Warning
Python 2 End of Life Announced as January 1st 2020.

This page covers Python 3 only. The last-known version for Python 2 is v0.5.2, install it via pip install konlpy==v0.5.2.
```
([link](https://konlpy.org/ko/v0.5.2/install/))

**Comment by minhoryang** [comment]
`JPype1==0.6.3` 을 설치해보세요.

**Comment by argon1025** [comment]
![error](https://user-images.githubusercontent.com/55491354/86721497-0109c680-c061-11ea-86a8-4c22dbf4218d.png)


`JPype1==0.6.3`
`konlpy==v0.5.2`
`konlpy==v0.5.1`

차례대로 설치를 시도해 보았는데 위와같은 현상이 지속됩니다
동일한 환경에서 아나콘다 가상환경 python 3.+ 부터는 설치가 잘 됩니다

**Comment by hexists** [comment]
@argon1025 
안녕하세요~
혹시 해결가능한지 이슈 확인해봤습니다.

**결론부터 이야기드리면, jpype를 conda-forge로 설치하고, konlpy를 설치하면 됩니다.**
jpype 문서에 보면 아래와 같은 내용이 있습니다. [link](https://jpype.readthedocs.io/en/latest/install.html#binary-install)

```
JPype can be installed as pre-compiled binary if you are using the Anaconda Python stack. Binaries are available for Linux, OSX, and windows on conda-forge.

Ensure you have installed Anaconda/Miniconda. Instructions can be found here.

Install from the conda-forge software channel:

conda install -c conda-forge jpype1
```

이 내용을 보고, conda-forge로 jpype를 설치하고, konlpy를 pip install을 통해 설치하니 잘 설치됩니다.
이상입니다.

**Comment by argon1025** [comment]
@hexists 감사합니다 조언해주신 방법으로 시도하니 python2.7에서 설치가 되었습니다.

root에서 실행
````
#conda install -c conda-forge jpype1
#pip install konlpy
````
