### ISSUE TITLE
konlpy 설치 오류..?

### ISSUE THREAD

**Issue by GMS80175064** [konlpy/konlpy#316]
안녕하세요. konlpy 설치와 8시간 정도 싸우다가 상황이 악화만 되서 질문을 여기저기 하고 있는 컴알못입니다! 깃허브도 알게 된지 얼마 안 됐고 그냥 질문을 올려도 되는 곳인지 잘 모르겠네요..? 문제되면 삭제하겠습니다. 자연어 처리를 위해 konlpy를 anaconda(window)로 설치하고 싶은데 계속 실패해서 질문드립니다 ㅠ.

konlpy 설치 방법대로 JAVA 설치 -> JAVA HOME 환경변수 설정 -> JPype 파이썬 버전에 맞게 설치 -> pip 업그레이드 -> pip install konlpy를 했는데, 그 결과가 아래입니다.
from konlpy.tag import Kkma => **"ModuleNotFoundError: No module named 'konlpy'"**
konlpy가 제대로 설치가 안된 것 같습니다. ..

cmd에서 pip install konlpy를 작성하면 아래와 같이 오류가 뜨는데, 이것이 문제가 아닌가 합니다.
Collecting konlpy
  Using cached konlpy-0.5.2-py2.py3-none-any.whl (19.4 MB)
Requirement already satisfied: beautifulsoup4==4.6.0 in c:\anaconda3\lib\site-packages (from konlpy) (4.6.0)
Requirement already satisfied: numpy>=1.6 in c:\anaconda3\lib\site-packages (from konlpy) (1.18.1)
Requirement already satisfied: lxml>=4.1.0 in c:\anaconda3\lib\site-packages (from konlpy) (4.5.0)
Requirement already satisfied: JPype1>=0.7.0 in c:\anaconda3\lib\site-packages (from konlpy) (1.0.1)
WARNING: No metadata found in c:\anaconda3\lib\site-packages
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'c:\\anaconda3\\lib\\site-packages\\JPype1-1.0.1.dist-info\\METADATA'

도대체 뭐가 문제인건지, 어떻게 해결해야하는지 감이 잡히질 않습니다. 혹시 왜 konlpy가 설치가 안되는지 아시나요?
아니면 다 삭제하고 다시 깔기라도 해보고 싶은데, 뭘 어떻게 삭제해야하는지도 모르겠습니다. 그냥 pip uninstall JPype1 이런 식으로 하는건지... 혹기 대책 방안 아시는 것 있으면 쉽게 알려주시면 정말정말 감사하겠습니다...

**Comment by keighrim** [comment]
jpype 설치가 제대로 안된거 같네요. 삭제하시고 공식 파이파이 버전으로 설치해보세요. 

* 삭제 
``` 
pip uninstall jpype1   # OR 
pip install jpype1
```

**Comment by GMS80175064** [comment]
그것도 해봤지만 안되더라고요.. 그래도 해외 사이트에서 답을 찾아서, 저같은 다른 컴린이를 위해 답을 남깁니다.
그래도 시간내어 답변 주셔서 정말 감사합니다!!!

site-packages 파일에서 jpype1-1.0.1.dist-info 파일 안에 Metadata라는 파일이 없더라고요. 그 파일을 직접 삭제하고 install jpype 하니까 되었습니다.

**Comment by nyanye** [comment]
해결책 제시 감사합니다 👍 
Issue를 close할게요!
