### ISSUE TITLE
twitter.pos 함수에서 object가 없다고 뜹니다 

### ISSUE THREAD

**Issue by ShimJuan** [konlpy/konlpy#322]
def get_noun(comment_txt):
    twitter = Twitter()
    noun = []
    
    if len(comment_txt)>0:
        tw = Twitter.pos(comment_txt)
        for i,j in tw:
            if j == 'Noun':
                noun.append(i)
    return noun
 
comment_result['token'] = comment_result['Comment'].apply(lambda x: get_noun(x))

를 실행시키면

AttributeError: 'function' object has no attribute 'pos' 가 뜹니다 어떻게 해결해야 할까요?

**Comment by nyanye** [comment]
단순한 구문오류입니다! 
```python
from konlpy.tag import Twitter


def get_noun(comment_txt):
    twitter = Twitter()
    noun = []

    if len(comment_txt)>0:
        tw = Twitter.pos(comment_txt)
        for i,j in tw:
            if j == 'Noun':
                noun.append(i)
    return noun
```
작성하신 코드를 잘 보시면, twitter 객체에서 pos method를 호출해야 작성자분이 원하신 동작이 가능할 것으로 보이는데요, 작성자님은 Twitter (서로 다른 객체죠)에서 pos method를 찾으셔서 문제가 발생한 것으로 보이네요.
또한 Twitter tagger는 'Okt'로 공식 명칭이 변경되어 KoNLPy의 최신 버젼에서는 다음과 같은 코딩 스타일을 권장합니다.

```python
from konlpy.tag import Okt


def get_noun(comment_txt):
    tagger = Okt()
    noun = []

    if len(comment_txt)>0:
        tw = tagger.pos(comment_txt)
        for i,j in tw:
            if j == 'Noun':
                noun.append(i)
    return noun
```

감사합니다 :)
