### ISSUE TITLE
Java package 'kr.lucypark.kkma' is not valid 오류

### ISSUE THREAD

**Issue by Joo-SangWon** [konlpy/konlpy#324]
jupyter notebook에서 실수로 환경변수들을 날려서
python을 재설치하고 konlpy를 재설치 하였더니 

from konlpy.tag import Kkma
Kkma().pos('설치여부확인법')

를 실행하면 

>> AttributeError: Java package 'kr.lucypark.kkma' is not valid

에러가 뜹니다 JPype / JAVA_HOME / jdk설정을 다시 다 확인해주었는데도 해결이 안되네요
해결방법 알려주시면 감사하겠습니다
재설치 이전에는 잘 실행되었습니다

**Comment by hexists** [comment]
@Joo-SangWon 

안녕하세요.
제 생각에는 jupyter에서 konlpy가 잘 설치되어 있는지 확인해보는 것이 좋을 것 같습니다.

### 확인 순서

```
#jupyter에서 사용하는 python3 path 확인
!which python3
/path/to/bin/python3

#python3 path를 base로 konlpy의 kkma가 잘 있는지 확인
!ls /path/to/lib/python3.7/site-packages/konlpy
__init__.py   constants.py  data          internals.py  stream
__pycache__   corpus.py     data.py       java          tag
about.py      csvutils.py   downloader.py jvm.py        utils.py

!ls /path/to/lib/python3.7/site-packages/konlpy/java/bin/kr/lucypark/kkma
KkmaInterface$1.class KkmaInterface$3.class KkmaInterface.class
KkmaInterface$2.class KkmaInterface$4.class
```
이렇게 확인한 경로와 python을 재설치하고 konlpy를 설치한 경로와 다르다면, **jupyter 상에서 konlpy를 다시 설치**하거나,
**python, konlpy를 재설치한 경로에서 jupyter를 다시 실행**하는 것을 추천드립니다.

- jupyter에서 konlpy 설치
```
!pip install konlpy
```

### 전체 과정

<img width="1159" alt="스크린샷 2020-08-05 오후 10 06 01" src="https://user-images.githubusercontent.com/6520567/89416271-f62d7900-d767-11ea-8baf-7b82ec999a92.png">


도움이 되었으면 좋겠습니다.

**Comment by Joo-SangWon** [comment]
감사합니다 많은 참고되었습니다
