### ISSUE TITLE
TypeError: startJVM() got an unexpected keyword argument 'convertStrings'

### ISSUE THREAD

**Issue by snoop2head** [konlpy/konlpy#329]
### Situation
* Mac OS Cattalina 10.15.3 
* pyenv virtual environment
* python 3.8.3
* JPype1 0.6.3

### Problem

```
~/.pyenv/versions/nlpkor2/lib/python3.8/site-packages/konlpy/tag/_okt.py in __init__(self, jvmpath, max_heap_size)
     89     def __init__(self, jvmpath=None, max_heap_size=1024):
     90         if not jpype.isJVMStarted():
---> 91             jvm.init_jvm(jvmpath, max_heap_size)
     92 
     93         oktJavaPackage = jpype.JPackage('kr.lucypark.okt')

~/.pyenv/versions/nlpkor2/lib/python3.8/site-packages/konlpy/jvm.py in init_jvm(jvmpath, max_heap_size)
     62 
     63     if jvmpath:
---> 64         jpype.startJVM(jvmpath, '-Djava.class.path=%s' % classpath,
     65                                 '-Dfile.encoding=UTF8',
     66                                 '-ea', '-Xmx{}m'.format(max_heap_size),

TypeError: startJVM() got an unexpected keyword argument 'convertStrings'
```

**Comment by coding-Benny** [comment]
Hello. You can solve this problem by following these steps:
1. Open `jvm.py` file.
It depends on the user and environment, but you can check the location of `jvm.py` in the log.
In your case, `jvm.py` is located `~/.pyenv/versions/nlpkor2/lib/python3.8/site-packages/konlpy/jvm.py`.

2. Modify lines 66-67 as follows:
    ```diff
    ~/.pyenv/versions/nlpkor2/lib/python3.8/site-packages/konlpy/jvm.py in init_jvm(jvmpath, max_heap_size)
      62 
      63     if jvmpath:
      64         jpype.startJVM(jvmpath, '-Djava.class.path=%s' % classpath,
      65                                 '-Dfile.encoding=UTF8',
    - 66                                 '-ea', '-Xmx{}m'.format(max_heap_size),
    - 67                                  convertString=True)
    + 66                                 '-ea', '-Xmx{}m'.format(max_heap_size))
    ```
    > `convertStrings` (*bool*) – Option to force Java strings to cast to Python strings. This option is to support legacy code for which conversion of Python strings was the default. This will globally change the behavior of all calls using strings, and a value of True is NOT recommended for newly developed code.

You can see more information about `convertString` and `TypeError` from [JPype User Guide](https://jpype.readthedocs.io/en/latest/userguide.html#string-conversions) and [API Reference](https://jpype.readthedocs.io/en/latest/api.html#jpype.startJVM).

**Comment by snoop2head** [comment]
Seems like the issue has been resolved within a year...!
The recent version works fine on my local dev environment.
Thanks for the walk through!
