### ISSUE TITLE
multi-threading 시 hannanum/kkma의 jvm 문제

### ISSUE THREAD

**Issue by dykang** [konlpy/konlpy#34]
좋은 소프트웨어 잘 쓰고 있습니다 :)

처리 데이터가 많은 경우, python의 threading을 이용해서 동시에 tagging을 하려고 합니다. 그런데 hannanum과 kkma같은 경우는 jvm를 하나만 생성하기에 python의 threading과 충동하는 문제가 jpype에서 발생합니다. http://stackoverflow.com/questions/7861299/jpype-doesnt-work-inside-thread

jvm을 여러개 loading하지 않고 해결할수 있는 방법이 있을까요? mecab은 mult-threading으로 잘 동작합니다.

**Comment by ipari** [comment]
같은 문제로 삽질하고 있었는데 덕분에 해결 되었습니다!
