### ISSUE TITLE
\t 사용시 tab 적용 안됨 문제

### ISSUE THREAD

**Issue by templas3324** [konlpy/konlpy#355]
def  profile(name,age,main_lang):
     print("이름:{0}\t나이:{1}\t주사용언어:{2}"\
         .format(name,age,main_lang)) 

profile("유재석", 20, "파이썬")
profile("김태호", 25, "자바")

실행시 
이름:유재석    나이:20 주사용언어:파이썬
이름:김태호    나이:25 주사용언어:자바
-> 두번째 \t 에서 tab 적용 안됨 오류 발생

**Comment by hexists** [comment]
> def profile(name,age,main_lang):
> print("이름:{0}\t나이:{1}\t주사용언어:{2}"
> .format(name,age,main_lang))
> 
> profile("유재석", 20, "파이썬")
> profile("김태호", 25, "자바")
> 
> 실행시
> 이름:유재석 나이:20 주사용언어:파이썬
> 이름:김태호 나이:25 주사용언어:자바
> -> 두번째 \t 에서 tab 적용 안됨 오류 발생

@templas3324 
안녕하세요~
위에 올려주신 내용만으로는 konlpy에서 발생하는 문제인지 파악이 어렵습니다.
실행했을 때 코드와 상황을 좀 더 설명해주시면 좋을 것 같습니다.

**Comment by combacsa** [comment]
@templas3324 님, 안녕하세요. 아마 질문의 의도는 이런 내용이셨던 것으로 생각됩니다.

올려주신 파이썬 코드를 실행했을 때, 대략 아래와 같은 느낌의 결과를 기대하셨을 텐데,

```
이름:유재석        나이:20        주사용언어:파이썬
이름:김태호        나이:25        주사용언어:자바
```

실제로 화면에는 아래와 같이 나왔는데 왜 그런지를 궁금해하신 것으로 보입니다.
```
이름:유재석        나이:20 주사용언어:파이썬
이름:김태호        나이:25 주사용언어:자바
```

이에 대한 부분은 '탭'(tab)이라는 개념에 대해 조사해보시는 것이 좋을 것 같습니다. 올려주신 코드에서 `나이:{1}` 부분을 `나이: {1}` 로만 고치셔도 기대하셨던 것과 같은 동작이 이뤄질 텐데요, 이곳은 KoNLPy 관련 issue 를 다루는 곳이어서 다소 관련이 없는 내용 같습니다.

KoNLPy 관련 질문이 맞는지 다시 한 번 확인 부탁드립니다.
