### ISSUE TITLE
Okt pos 관형사 

### ISSUE THREAD

**Issue by aprilykang** [konlpy/konlpy#357]
안녕하세요, 
okt 관형사 분류에 대해 문의드립니다.
공식 문서에 Modifier는 소개되어 있지 않아 이전 issue을 찾아보니 관형사라고 답변이 달려 있었습니다. 
하지만 Determiner 또한 관형사로 분류가 되어 있어서 두 가지의 차이점이 있을까 해서 문의드립니다.

**Comment by combacsa** [comment]
@aprilykang 님, 안녕하세요. 관련 내용은 https://github.com/open-korean-text/open-korean-text 프로젝트 쪽에 문의를 남기시면 더 정확한 답변을 얻으실 수 있을 것으로 생각됩니다. 다음 코드도 참고해 주세요.

https://github.com/open-korean-text/open-korean-text/blob/master/src/main/scala/org/openkoreantext/processor/phrase_extractor/KoreanPhraseExtractor.scala

**Comment by combacsa** [comment]
다음과 같은 예시들을 보시면 Determiner 와 Modifier 를 Okt 에서 구분하는 기준이 상당히 애매함을 확인하실 수 있습니다.

```python3
In [41]: okt.pos('아홉살')
Out[41]: [('아홉', 'Determiner'), ('살', 'Noun')]

In [43]: okt.pos('세살')
Out[43]: [('세', 'Modifier'), ('살', 'Noun')]
```

Okt 소스코드에서 `Determiner`로 분류될 수 있는 것은 12개( 그, 내, 네, 다섯, 두, 아홉, 여덟, 여섯, 이, 일곱, 저, 한 )이고 `Modifier`로 분류될 수 있는 것은 454개인 것으로 보입니다. 

* [determiner 목록](https://github.com/open-korean-text/open-korean-text/blob/master/src/main/resources/org/openkoreantext/processor/util/auxiliary/determiner.txt)
* [modifier 목록](https://github.com/open-korean-text/open-korean-text/blob/master/src/main/resources/org/openkoreantext/processor/util/substantives/modifier.txt)

여러 앞뒤 정황으로 볼 때 Dterminer 도 Modifier 도 Okt 내에서는 관형사를 뜻하는 것으로 보입니다. 학교문법에서는 Modifier 가 수식언이고 Determiner 가 관형사로 5언9품사 체계상 서로 다른 층위에 있지만, Okt 에서 그런 체계를 따르는 것으로는 보이지 않습니다.

@aprilykang 님께서 궁금하셨던 부분에 도움이 되기를 바랍니다. 이 이상의 내용은 [Okt 프로젝트쪽 Issues](https://github.com/open-korean-text/open-korean-text/issues)에 남겨주시거나 [Okt 사용자 포럼](https://groups.google.com/g/open-korean-text)에 남겨주시면 찾으실 수 있을 것으로 생각됩니다. 이슈는 닫아 두도록 하겠습니다. 필요하시면 새로 이슈를 열어 주시면 감사하겠습니다. :)
