### ISSUE TITLE
SystemError: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by lyg0108** [konlpy/konlpy#361]
안녕하세요 .
우선 konlpy 모듈을 올려주셔서 감사합니다. 
덕분에 다양한 프로젝트를 성공적으로 진행할 수 있었습니다. 

본론으로 들어가자면 6개월 전에 돌아가던 코드가 현재는 돌아가지 않아 이에 대해 문의하고자 합니다. 
okt = Okt()
에러는 이 코드에서 발생합니다. Okt()를 불러올 때 생기는 에러 같은데 어떻게 해결할 수 있을까요? 
하단에 에러 전체를 첨부하겠습니다. 

SystemError                               Traceback (most recent call last)
<ipython-input-9-4addc4273d9e> in <module>
     11 from collections import Counter
     12 
---> 13 okt = Okt()
     14 
     15 # 크롬 드라이버 설치한 경로 지정해주기

C:\ProgramData\Anaconda3\lib\site-packages\konlpy\tag\_okt.py in __init__(self, jvmpath, max_heap_size)
     89     def __init__(self, jvmpath=None, max_heap_size=1024):
     90         if not jpype.isJVMStarted():
---> 91             jvm.init_jvm(jvmpath, max_heap_size)
     92 
     93         oktJavaPackage = jpype.JPackage('kr.lucypark.okt')

C:\ProgramData\Anaconda3\lib\site-packages\konlpy\jvm.py in init_jvm(jvmpath, max_heap_size)
     62 
     63     if jvmpath:
---> 64         jpype.startJVM(jvmpath, '-Djava.class.path=%s' % classpath,
     65                                 '-Dfile.encoding=UTF8',
     66                                 '-ea', '-Xmx{}m'.format(max_heap_size),

C:\ProgramData\Anaconda3\lib\site-packages\jpype\_core.py in startJVM(*args, **kwargs)
    224 
    225     try:
--> 226         _jpype.startup(jvmpath, tuple(args),
    227                        ignoreUnrecognized, convertStrings, interrupt)
    228         initializeResources()

SystemError: java.lang.UnsatisfiedLinkError: Native Library C:\ProgramData\Anaconda3\Lib\site-packages\_jpype.cp38-win_amd64.pyd already loaded in another classloader

**Comment by coding-Benny** [comment]
안녕하세요.
시간이 좀 지나서 지금은 해결하셨을지 모르겠지만, 아직 해결이 안 되셨다면 혹시 **환경 변수가 중복 설정**되었는지 한번 확인해보시겠어요?
예를 들면, Path에 `%JAVA_HOME%\bin`과 `C:\Program Files\Java\jdk-버전\bin`이 중복되어 등록되어 있는 경우 유사한 문제가 발생할 수 있는 것 같습니다.
제가 참고한 [포스팅](https://byeon-sg.tistory.com/entry/%EC%9E%90%EC%97%B0%EC%96%B4-%EC%B2%98%EB%A6%AC-konlpy-%EC%84%A4%EC%B9%98-%EC%98%A4%EB%A5%98-okt%EC%97%90%EB%9F%AC-already-loaded-in-another-classloader-SystemErro-1)의 4번 항목 확인해보시면 도움이 될 것 같습니다 :)
