### ISSUE TITLE
tweepy 버전 이슈 문제

### ISSUE THREAD

**Issue by devsungmin** [konlpy/konlpy#371]
# 주제
- 2021년 10월 6일 기준 진행 시 tweepy 버전 이슈 문제가 존재합니다.

# 문제점
- ` $ pip install konlpy`을 진행하여 `import tweepy`을 진행하는 경우 `tweepy module`관련 에러가 발생함
- 해당 에러는  `tweepy`가 4.0버전으로 업그레이드 하는 과정에서 발생한 이슈로 판단됨
- `tweepy`의 경우 [해당 링크](https://github.com/tweepy/tweepy/releases)에서 버전을 확인이 가능함
- 10월 6일 기준 `tweepy`는 `4.0.1버전`으로 배포 된 상태임

# 현재 해결 방법
1. konlpy을 설치함
```shell
$ pip install konlpy
```
2. tweepy 버전을 4.0버전 이하로 설치 진행
```shell
$ pip install tweepy==3.10.0
```

**Comment by hexists** [comment]
@devsungmin 

같은 이슈가 정리된 글이 있어 남겨놓습니다.
요약하면 master branch에는 tweepy가 이미 제거된 상황입니다.
새로운 버전의 release가 필요합니다.

https://github.com/konlpy/konlpy/issues/368#issuecomment-930233628

**Comment by dleunji** [comment]
@devsungmin

2번 command에 tweepy가 konlpy로 적힌 사소한 오타가 있어서 issue 남깁니다.
유용한 해결방안 감사합니다 :)
```
$ pip install tweepy==3.10.0
```

**Comment by combacsa** [comment]
안녕하세요, @devsungmin 님. #374 를 거쳐 `0.6.0` 버전 릴리즈가 되었는데요, 겪고 계셨던 문제가 해결되셨는지 혹 확인 부탁드려도 괜찮을까요? 

* https://pypi.org/project/konlpy/0.6.0/

**Comment by devsungmin** [comment]
안녕하세요 @combacsa 님 확인해보니 2022년 1월 3일 오전 12시 32분기준으로 3시간전 새로운 버전인 `0.6.0`버전이 업데이트 되었다는 것을 확인 하였습니다!!

해당 문제는 0.6.0 버전을 설치해보고 바로 해당 이슈 페이지를 통해 전달해 드리겠습니다.

감사합니다.

**Comment by devsungmin** [comment]
안녕하세요 @combacsa 님 말씀해주신 사항 확인해보니 `0.6.0`버전 이후 해결된 것으로 보입니다.

테스트 환경은 다음과 같습니다.

``` text
OS: macOS Monterey 12.1
CPU: Apple M1
Python Version: 3.8.11
Konlpy Version: 0.6.0
```
![스크린샷 2022-01-03 오전 9 41 37](https://user-images.githubusercontent.com/37958836/147893493-e7521ff8-4541-4574-9837-a68dc122b8f2.png)

감사합니다 :)

**Comment by combacsa** [comment]
@devsungmin 확인 감사합니다. issue close 하겠습니다. 👏
