### ISSUE TITLE
master release 요청

### ISSUE THREAD

**Issue by hexists** [konlpy/konlpy#374]
안녕하세요.
최근 올라오는 이슈들을 보면 이미 master에서 해결된 이슈들에 대해 같은 내용이 자주 올라옵니다.
아마도 주로 사용하는 분들이 릴리즈 된 버전을 사용하면서 어려움을 겪고 있는 것 같습니다.
많이 바쁘시겠지만, **master release를 해주시면 더 많은 사용자들이 손쉽게 konlpy를 사용할 수 있을 것 같습니다.**

주로 활동하시는 메인테이너 분 멘션 남깁니다.
konlpy를 배포해주시고 관리해주셔서 항상 감사합니다.

cc. @minhoryang

**Comment by combacsa** [comment]
안녕하세요.

오늘 오랜만에, 교육에 사용하려고 `pip install konlpy` 를 가볍게 했다가 몇 가지 트러블슈팅을 하면서 이슈들을 쭉 보게 되었습니다. 혹 릴리즈 프로세스 진행에 기여할 수 있는 방법이 있다면 돕고 싶습니다. 

#365 에서도 같은 질문이 있었네요.

조심스럽게 가장 최근에 릴리즈 진행해주셨던 분들 조금 더 멘션해봅니다. @e9t

**Comment by minhoryang** [comment]
@combacsa @hexists 늦게 확인하여 죄송합니다.
우선 github org 에 초대하였습니다.
추가로 test.pypi.org 에도 초대하고, 릴리즈 성공시, pypi.org에도 초대하여, 실제로 다음버전 릴리즈가 가능하도록 진행하겠습니다.

**Comment by minhoryang** [comment]
@combacsa @hexists pypi를 확인해보니 제가 배포권한만 가지고 있을 뿐, 초대권한이 없는 것으로 확인되었습니다.
배포를 제가 진행해드릴 수 있습니다. 안심하고 배포를 진행할 수 있도록 최대한 많은 환경에서 동작할 수 있게 테스트해주시면 감사하겠습니다. (tox)

**Comment by minhoryang** [comment]
CC: https://github.com/konlpy/konlpy/issues/267#issuecomment-997396166

**Comment by combacsa** [comment]
@minhoryang commit 아이디 고정하고 그러면 좋을 거 같은데요, 기존 릴리즈 프로세스 관련 정보 및 관련 소통방식에 대한 레퍼런스를 조금 주시면 공부하면서 해볼 만한 환경들에서 테스트해 보겠습니다. 일단 AMD CPU 쓰는 우분투 리눅스, 라즈베리 파이, 인텔 CPU 쓰는 윈도우, 인텔 CPU 쓰는 맥 OS 정도는 갖고 있으니..

**Comment by minhoryang** [comment]
@combacsa 기존 릴리즈 프로세스는, 필요한 변경을 master브랜치에 추가한 후, 최대한 여러 환경에서의 테스트, version numbering, make testpypi로 배포, make pypi로 배포였습니다.
깨진 테스트를 고치고, api를 크게 해치지 않는 선에서의 변경을 적용하고 (호출의 결과값이 변경되지 않았음 좋겠습니다.), 테스트가 통과한다면, 배포를 바로 진행해도 될 것 같습니다.

**Comment by hexists** [comment]
@minhoryang 
답변 감사합니다.
어서 테스트를 진행해서 새로운 버전이 릴리즈 될 수 있었으면 좋겠네요^^
감사합니다!

**Comment by e9t** [comment]
@minhoryang @combacsa @hexists 이슈를 뒤늦게 확인했습니다. 많은 분들이 합심해서 릴리즈를 진행하는 모습을 보니 그간 챙기지 못해서 죄송하면서도 진정한 오픈소스를 보는 것 같아 가슴이 웅장해지네요. 저도 이번 릴리즈에 기여하진 못하더라도 이슈 팔로업해서 사용성 개선에 기여하도록 하겠습니다. 애써주신 분들, 정말 감사드립니다.

**Comment by e9t** [comment]
많은 분들의 노고 덕에 방금 0.6.0 릴리즈 했습니다! 
https://pypi.org/project/konlpy/0.6.0/

간만에 릴리즈 하는지라 문제가 생겼을까봐 우려되는데요. 혹시 이슈 있으면 새 이슈 생성 부탁드립니다.
그리고 새해 복 많이 받으세요 :)

**Comment by devsungmin** [comment]
@minhoryang M1 맥 테스트가 필요하시면 제가 진행 해보겠습니다!!

**Comment by minhoryang** [comment]
@devsungmin 감사합니다! 기억하고있겠습니다!!!
