### ISSUE TITLE
m1 실행시 FileNotFoundError: [Errno 2] JVM DLL not found 에러 발생 

### ISSUE THREAD

**Issue by SukyC** [konlpy/konlpy#375]
안녕하세요 저는 m1 맥북 유저입니다. 
이미 올려져 있던 다른 이슈들( #353 , #354 , #369 )들을 참고하여 
순차 설치도 하고, 환경변수도 설정했습니다. 

그 이후  실행하려는데 하기와 같은 에러가 지속적으로 발생합니다. 

콘다 가상환경에서 실행중이고  
Mac os: bigsur
python :   3.8.0 64bit 
konlpy==0.5.2
JPype1==1.3.0
자바는 jdk-17.0.1.jdk 

입니다. 

해당 위치에 jvm 파일이 없다는 의미인데 
제가 뭘 놓치고 있을까요? 
라이브러리나 자바를 삭제후 순서대로 재설치 하고 재부팅도 해보고 하는데 
해결할 방법을 찾을 수가 없습니다.  도움 부탁드립니다 

Traceback (most recent call last):
  File "/Users/sk.c/urclass_git/ds-cp02/testcode.py", line 2, in <module>
    okt = Okt()
  File "/Users/sk.c/opt/anaconda3/envs/ds-cp-02/lib/python3.8/site-packages/konlpy/tag/_okt.py", line 91, in __init__
    jvm.init_jvm(jvmpath, max_heap_size)
  File "/Users/sk.c/opt/anaconda3/envs/ds-cp-02/lib/python3.8/site-packages/konlpy/jvm.py", line 64, in init_jvm
    jpype.startJVM(jvmpath, '-Djava.class.path=%s' % classpath,
  File "/Users/sk.c/opt/anaconda3/envs/ds-cp-02/lib/python3.8/site-packages/jpype/_core.py", line 226, in startJVM
    _jpype.startup(jvmpath, tuple(args),
FileNotFoundError: [Errno 2] JVM DLL not found: /Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home/lib/libjli.dylib

**Comment by mglee815** [comment]
같은 문제를 겪고 있습니다.
자바는 17.0.1과 zulu 15.0.5 모두 시도해봤습니다.

**Comment by hexists** [comment]
@SukyC @mglee815 

혹시 아래 링크에 있는 jdk를 사용했을 때 잘 안되시는걸까요?
https://www.oracle.com/java/technologies/downloads/#jdk17-mac

https://github.com/konlpy/konlpy/issues/369 여기 남겨 놓은대로 jdk를 사용했을 때 잘 됐습니다만, 
conda python을 사용했을 때 잘 안되더라고요. mac에서 기본으로 제공하는 python으로 해보시면 좋을 것 같습니다.
https://github.com/hexists/konlpy/issues/4#issuecomment-937307393

**Comment by SukyC** [comment]
네. 해당 링크에서 jdk 를 설치했지만 오류가 반복적으로 발생합니다. 
그래서 포기하고 구글 코랩에서 실행했습니다. 어쩔수가 없네요... 도움 감사드립니다.
