### ISSUE TITLE
import _jpype 문제 

### ISSUE THREAD

**Issue by imji0319** [konlpy/konlpy#377]
pip 로 konlpy 는 잘 설치했는데 import 할 때 문제가 발생합니다. 
konlpy 를 설치하면서 jpype 도 설치되었습니다. 
그렇게 자동으로 설치된 jpype 임에도 불구하고 import _jpype 문제가 발생하고 있고 실제 파일을 열어 확인해본 결과 _jpype 파일이 존재하지 않았습니다. 이럴 경우 어떻게 해야 하나요?? 
<img width="478" alt="스크린샷 2021-11-02 오후 1 24 16" src="https://user-images.githubusercontent.com/34160245/139787752-f702b30d-1a90-467d-afd1-a761b5dcde48.png">

<img width="919" alt="스크린샷 2021-11-02 오전 9 47 40" src="https://user-images.githubusercontent.com/34160245/139787724-232cf594-7ec2-4f7b-97b1-71268857675a.png">

**Comment by hexists** [comment]
@imji0319 
같은 내용 남기신 것 같아서 답변 링크 남겨놓습니다.
https://github.com/hexists/konlpy/issues/6

**Comment by combacsa** [comment]
안녕하세요, @imji0319 님. 오늘(2022년 1월 2일) `0.6.0` 버전이 릴리즈되었는데 혹시 이 버전에서도 여전히 같은 현상을 겪고 계신지 확인 부탁드립니다. ( `pip uninstall JPype1 konlpy && pip install konlpy==0.6.0` 처럼 하시면 될 거 같습니다.) 제 Local(M1) 에서는 Monterey / miniforge conda 4.11.0 / Python 3.10.1 / JDK 17 조합에서 작동되는 것으로 보입니다. 

* JDK 버전을 #369 에서 실험된 것과 같이 17 로 맞추실 수 있을까요?

**Comment by imji0319** [comment]
아 문의를 남기고 나서 이후 해결을 해서 활용을 하고 있었어요... 답변 감사드립니다!!

**Comment by combacsa** [comment]
@imji0319 확인 감사합니다. Issue 는 Close 하겠습니다.
