### ISSUE TITLE
m1 silicon mac 에서 JDK 문제

### ISSUE THREAD

**Issue by wikidipia** [konlpy/konlpy#383]
```
[0.005s][warning][os,thread] Attempt to protect stack guard pages failed (0x000000016d980000-0x000000016d98c000).
[1]    28885 killed
```

다른 이슈글 참고해서 jula 15 랑 oracle 17 사용해봤는데
둘 다 같은 오류로 결과 뱉기 전에 죽어버립니다.
파이썬 버전은 3.8.9 인데 파이썬 문제일까요?

**Comment by combacsa** [comment]
https://github.com/konlpy/konlpy/issues/369#issuecomment-1003723016 를 보면서 따라해 보니, Monterey 에서 Zulu 17 로 되는 것으로 보입니다. `JAVA_HOME` 등 환경 변수 설정은 잘 되어 있으실까요?

**Comment by wikidipia** [comment]
> [#369 (comment)](https://github.com/konlpy/konlpy/issues/369#issuecomment-1003723016) 를 보면서 따라해 보니, Monterey 에서 Zulu 17 로 되는 것으로 보입니다. `JAVA_HOME` 등 환경 변수 설정은 잘 되어 있으실까요?

`JAVA_HOME` 이 Zulu 15로 되있었네요! 
Zulu17은 안되고 oracle 17 로 변경했을때 워닝 메세지 없이 해결했습니다! 
감사합니다~

**Comment by e4m98** [comment]
m1 mac , ventura 13.5.1 
JDK 17 로 에러 없이 정상 작동합니다.
 [anaconda venv python==3.8.6, konlpy==0.6.0 , JPype1==1.4.1 ]
아나콘다 가상환경 쓰시는 분은
conda install -c conda-forge JPype1
설치 후에 pip install konlpy 진행 하시면 됩니다~
