### ISSUE TITLE
Hannanum `node alloc: no space` 오류

### ISSUE THREAD

**Issue by hank110** [konlpy/konlpy#39]
`Hannanum()` 클래스의 메소드를 사용하면 `node alloc: no space` 및 `node_free: wrong parameter` 오류가 발생합니다.
스크린샷에 보이듯이 `Hannanum()`에 `jvmpath`를 설정해도 똑같은 오류가 발생합니다.

![han1](https://cloud.githubusercontent.com/assets/9034249/5660372/d21b5ff0-9762-11e4-8bae-e8fc99cb8803.JPG)
![han2](https://cloud.githubusercontent.com/assets/9034249/5660378/da70b01a-9762-11e4-83f1-5518b1feedeb.PNG)

**Comment by e9t** [comment]
1. 사용하신 OS가 윈도우인가요?
1. 혹시 콘솔에 출력된 에러 메세지는 캡쳐해주신 것이 전부인가요?
2. 실행하신 줄 중에서 몇 번째 줄에서 오류가 났는지도 아시나요?

제가 사용하는 윈도우 7에서는 #7 의 문제가 발생해서 한나눔이 import와 instance 생성은 되지만 메소도는 실행이 되지 않는데, 혹시 @hank110 님의 머신은 어떤가요? 위 오류가 import 하다가 생긴 문제인지, hannanum instance를 생성할 때 발생했는지, 메소드를 실행할 때 발생했는지 알 수 있다면 보다 문제를 해결하는데 도움이 될 것 같습니다.

한편, 위 코드는

**Comment by hank110** [comment]
1. 사용하는 윈도우는 윈도우 7을 사용하고 있습니다.
2, 3. 출력된 오류는 캡쳐해드린게 전부이며 특정 라인에서 오류가 발생했는지는 나오지 않습니다.
제 경우에도 import와 hannanum instance는 생성되지만 메소드 실행이 되지 않습니다.
언제나 빠른 답변 감사드립니다.

**Comment by typicalkorean** [comment]
형태소분석기가 톰캣 위에서 구동해야 하므로 conf와 data 경로를 아래와 같이 servlet context 경로로 재정의하여 구현했습니다.

String path = request.getSession().getServletContext().getRealPath("");

Workflow workflow = new Workflow(path);
workflow.setMorphAnalyzer(new ChartMorphAnalyzer(), "conf/plugin/MajorPlugin/MorphAnalyzer/ChartMorphAnalyzer.json");
workflow.setPosTagger(new HMMTagger(), "conf/plugin/MajorPlugin/PosTagger/HmmPosTagger.json");

디버깅을 해보면 workflow.activateWorkflow(true); 에서 상당시간이 지체된 후 아래 로그를 뿌리는데요

node alloc: no space
node alloc: no space
node alloc: no space
node_free: wrong parameter

마찬가지로 환경은 윈도우 7, eclipse juno, java 1.8 이며, external library로 jar 등록해서 sts 위에 올려져 있습니다.

혹시 답변이 가능하시다면 확인 좀 부탁드려봅니다. (__)

감사합니다.

**Comment by e9t** [comment]
안녕하세요. 조금 더 조사가 필요할 것 같긴 하지만, 일단 해당 문제는 hannanum 내부에서 trie를 구축하는 과정에서 트리거 된 듯 합니다:

https://github.com/haven-jeon/HanNanum-Analyzer/blob/master/src/kr/ac/kaist/swrc/jhannanum/plugin/MajorPlugin/MorphAnalyzer/ChartMorphAnalyzer/Trie.java#L232

막상 코드를 보니 윈도우 등 소프트웨어 환경의 특성인지는 모르겠네요. 혹시 해당 컴퓨터에 메모리 등 하드웨어 리소스가 충분한지 확인해보는게 어떨까 싶습니다. 일단 konlpy 자체의 문제가 아니니 이슈는 닫겠습니다만, hannanum에 대한 논의를 할 곳이 마땅하지 않다면 이곳에서 계속 논의를 이어나가도 될 것 같습니다.

**Comment by lhm7877** [comment]
프로젝트 Properties 에서 Text file encoding을 UTF-8로 바꿔보셨나요?

**Comment by cocoparm** [comment]
저도 같은 오류가 발생하네요. 저는 그냥 extractNoun 사용합니다.

**Comment by JihyeLee-kr** [comment]
안녕하세요. Windows 뿐만 아니라 Ubuntu 환경에서도 해당 오류가 발생합니다.
NIADic을 파이썬에서 사용하려고 dic_user.txt를 추가하였는데 그 파일의 사이즈 제한이 있나요?
