### ISSUE TITLE
Announce 0.6.0 Release 공지 (as-is: pre-release)

### ISSUE THREAD

**Issue by combacsa** [konlpy/konlpy#390]
현재 pypi 에는 0.6.0 이 정식 릴리즈로 등록되어 있고, github 에는 0.6.0 이 Pre-release 로 등록되어 있어 약간 불일치가 있습니다.

이미 공식 문서(latest) 등이 모두 0.6.0 으로 업데이트되었으니, github 에도 0.6.0 을 정식 릴리즈로 소개하는 작업을 진행하는 게 좋을 거 같아요. Github 프로젝트 페이지에 딱 들어오는 순간, 여전히 '2년 전'에 마지막 릴리즈 이후로 릴리즈가 없는 것처럼 보이는 상황에 변화를 주면 좋을 듯합니다.

다른 매인테이너 분들 혹은 KoNLPy 커뮤니티 구성원 여러분께서는 어떻게 생각하시는지 의견 주시면 감사하겠습니다 :)

**Comment by hexists** [comment]
@combacsa (cc. @minhoryang)
안녕하세요~
저도 같은 생각입니다. 
이슈들을 좀 정리해보면 좋겠네요.

추가로 project에 있는 작업들도 한번 정리하면 좋겠네요^^
project에 0.6.0, 0.7.0을 봤던 것 같은데, 지금은 없네요^^;

**Comment by combacsa** [comment]
@hexists 해당 내용은  milestone 에 들어있는 듯합니다.

**Comment by combacsa** [comment]
`0.6.0` 자체는 `0.6.0` 자체로 stable release 로 볼 수 있을 거 같습니다. (이후 들어온 PR / issue 는 `0.6.0` 릴리즈 자체보다는 그 외의 사안들과 관련된 것으로 보입니다) 1주일 가량 지났으니 Release 탭에 정식 릴리즈로 노출해도 괜찮지 않을까 생각해봅니다.

**Comment by hexists** [comment]
@combacsa 
네 저도 같은 생각입니다.

**Comment by combacsa** [comment]
![marked_as_release](https://user-images.githubusercontent.com/1102736/149551588-d521db9b-50c0-4a98-ae69-e460910197ef.PNG)

진행한 작업: 기존에 @e9t 님께서 작성해 두신 0.6.0 Release 에 대해 Edit 으로 들어가서 `This is a pre-release` `We’ll point out that this release is identified as non-production ready.` 라고 적혀 있는 부분에 Checkbox 에 Check 되어 있던 걸 Check 해제하였습니다.

**Comment by minhoryang** [comment]
감사합니다!
