### ISSUE TITLE
코랩 환경에서 mecab 실행에 오류가 발생합니다. 

### ISSUE THREAD

**Issue by hopebii** [konlpy/konlpy#393]
안녕하세요.

https://somjang.tistory.com/entry/Google-Colab%EC%97%90%EC%84%9C-mecab-ko-dic-%EC%82%AC%EC%9A%A9%EC%9E%90-%EC%82%AC%EC%A0%84-%EC%B6%94%EA%B0%80%ED%95%98%EA%B8%B0 

mecab 사용자 사전 추가 작업을 하고자, 코랩 환경에서 해당 블로그를 참고해서 mecab을 잘 사용하고 있었는데

22.01.09 일자로 실행할 때, 갑자기 Mecab() 을 불러올 때 

NameError: name 'Tagger' is not defined 오류가 발생하였습니다. 

다른 방식으로 mecab을 설치해도 계속 저런 오류가 발생하네요. 

구글링을 해도 도저히 해답이 나오지 않아서..ㅠㅠ (제가.. 컴공과가 아니라 역량 부족인 건지 모르겠습니다...) 
이렇게라도 댓글 남겨 봅니다!

**Comment by combacsa** [comment]
안녕하세요, @hopebil 님. 이슈 생성 감사합니다. 해당 블로그 게시물의 작성자분도 방법을 찾고 계신 것 같습니다. [링크](https://somjang.tistory.com/538#comment6318586)를 보면서 저도 원인이 될 만한 것을 몇 개 찾아보고 있습니다. MeCab 설치 관련해서는 최근에 (1월 9일) 아래와 같은 변경사항( #391 과 # 392 )이 있었는데, 이 변경사항들이 원인이 될만한지는 좀더 살펴봐야 할 거 같습니다. #392 는 아마도 무관할 거 같고 #391 이 아주 조금 의심되긴 하는데, 한번 살펴보겠습니다.

**Comment by combacsa** [comment]
임시방편으로는 `!bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/d9206305195583c08400cb2237c837cc42df2e65/scripts/mecab.sh)` 를 `from konlpy.tag import Mecab` cell 바로 앞에 삽입하시면 작동은 되게 하실 수 있습니다.

**Comment by hopebii** [comment]
블로그 작성자 분께서 해당 이슈를 보시고, @combacsa 도움을 주신 덕분에 업데이트 반영해주셔서, 방금 정상적으로 실행 되는 걸 확인했습니다!! 정말 감사드립니다!
