### ISSUE TITLE
mecab 설치시 최신 릴리즈 버전을 참조하도록 변경

### ISSUE THREAD

**Issue by hexists** [konlpy/konlpy#395]
mecab 설치시 최신 릴리즈 버전을 참조하도록 변경
-----
- #394 
- master branch의 script를 사용할 때, 예상치 못한 오류가 발생할 수 있음
- master의 파일 대신 최신 릴리즈의 파일을 사용하도록 변경 필요

https://konlpy.org/ko/latest/install
```
asis
$ bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)

tobe
$ bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/v0.6.0/scripts/mecab.sh)
```

**Comment by combacsa** [comment]
Release 할 때 [docs/install.rst](../blob/master/docs/install.rst) 파일에 변경이 가해지는 구조가 되어야 하겠군요. readthedocs 동작 방식을 정확히 몰라서, tag 별로 문서 수정이 필요할까요?

**Comment by hexists** [comment]
@combacsa 
저도 readthedocs 동작 방식을 잘 몰라서 공부해보고 다시 답변 남기겠습니다^^
tag별로 수정되지 않도록 했으면 좋을 것 같은데, 방법을 찾아봐야 할 것 같아요.

**Comment by minhoryang** [comment]
latest-stable 태그를 만들고, 해당 태그로 문서를 작성한다음, 매 릴리즈마다 해당 태그를 업데이트?해주는 방안도 있을 것 같습니다!

**Comment by hexists** [comment]
@minhoryang (cc. @combacsa )
좋은 아이디어 감사합니다!
mecab 설치 외에도 konlpy 운영을 생각해보면, latest branch(또는 tag)를 만들어서 관리하는 것이 더 좋아보이네요^^;
readthedocs도 살펴봤지만, tag를 변수로 넘겨서 설정하는 방법을 잘 모르겠습니다ㅠ

혹시, 이렇게 하는 것은 어떨까요?

```
- release branch 생성
- master branch -> 버전 배포
- master branch -> release branch -> 버전 배포

#mecab과 같이 스크립트에 branch가 포함되는 경우

$ bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/release/scripts/mecab.sh)
```

일단 이렇게 작업해서 pr 남겨보겠습니다.
다른 의견이나 수정이 필요하다면 의견 부탁드립니다.

감사합니다.

**Comment by hexists** [comment]
#399 에서 해당 이슈를 처리하여 close 합니다.
