### ISSUE TITLE
문법 오류 제보 '한바탕'

### ISSUE THREAD

**Issue by wtf-omg-bh** [konlpy/konlpy#410]
"드높은 하늘을 보자 한바탕 웃는 용기가 생겼다"에서 '한바탕'은
수 관형사 '한-' + 명사 '바탕'  => '한바탕'인데 한국어 형태소 분석기들을 모두 테스트 해본 결과 하나의 일반부사로 처리하고 있습니다.  심지어 okt로는 명사로 나옵니다.

**Comment by hexists** [comment]
@wtf-omg-bh 
안녕하세요.
형태소 분석 오류는 각 형태소 분석기 개발하는 곳에 제보 부탁드립니다.
konlpy는 형태소 분석기를 wrapping해서 제공하고 있어 분석 오류 수정이 어렵습니다.

참고로 각 형태소 분석기의 바이너리 경로를 남겨놓습니다.
https://github.com/konlpy/konlpy/tree/master/konlpy/java
