### ISSUE TITLE
Hannanum 사용자사전 추가 방법 문의

### ISSUE THREAD

**Issue by gloriakim-arch** [konlpy/konlpy#412]
Hannanum 분석기에 특정 단어를 하나의 명사로 추출하고 싶은데 방법이 있을까요?
dic_user.txt 파일에 단어와 품사를 추가했지만 분석 시 적용되지 않았습니다.

**Comment by hexists** [comment]
@gloriakim-arch 
안녕하세요~
같이 문제를 살펴보고 싶은데요.
어떤 예제에서 문제가 있었는지 공유 부탁드립니다.

**Comment by hexists** [comment]
@gloriakim-arch 

참고로 아래와 같은 예제에서는 잘 등록됩니다.

1) user_dic.txt에 '허니제이	ncn' 등록

2) test code
``` python3
#!/usr/bin/env python3

from pprint import pprint

from konlpy.tag import Hannanum
hannanum = Hannanum()

sample = '허니제이 공식입장'  # user_dic.txt 추가 전, 허니제, 공식입장
pos = hannanum.pos(sample)
nouns = hannanum.nouns(sample)

print(f'sample: {sample}\npos: {pos}\nnouns: {nouns}')
```

3) 결과
user_dic.txt에 추가전에는 '허니제'가 출력됨

``` bash
sample: 허니제이 공식입장
pos: [('허니제', 'N'), ('이', 'J'), ('공식입장', 'N')]
nouns: ['허니제', '공식입장']
```

**Comment by gloriakim-arch** [comment]
말씀해주신 같은 예제로 말씀 드리면, 허니제이 앞에 다른 단어가 있을 경우에 '허니제이'가 단독으로 잡히지 않습니다. 띄어쓰기 전처리를 한 번 했지만 완전하지 않아서 사용자사전 구축으로 해당 단어가 추출되고 했었습니다.

1. 코드
```
from konlpy.tag import Hannanum
hannanum = Hannanum()

sample = '예쁜허니제이 공식입장 발표'  
pos = hannanum.pos(sample)

print(pos)
```

2. 결과
`[('예쁜허니제', 'N'), ('이', 'J'), ('공식입장', 'N'), ('발표', 'N')]`

**Comment by hexists** [comment]
@gloriakim-arch 

설명해주신 예제를 실행해보니 잘 안되네요.
이 문제는 **hannanum 형태소 분석기의 오류**로 생각됩니다.

비슷한 이슈가 2016년에 있었던 것 같습니다.
https://github.com/haven-jeon/HanNanum-Analyzer/issues/4

konlpy는 여러 형태소 분석기의 wrapper로 분석기 내부에 대해서는 다루지 않고 있어 해당 이슈는 hannanum 쪽에 이슈를 남기는 것이 좋을 것 같습니다만, 현재 hananum 형태소 분석기를 관리하는 곳이 따로 없는 것 같네요 ㅠ

혹시 도움이 될까 싶어서 가이드 문서 찾은 것 남겨놓습니다.
https://www.sketchengine.eu/wp-content/uploads/Original-HanNanum-manual.pdf

본 글 확인하시면 이슈 닫겠습니다. 감사합니다.

**Comment by gloriakim-arch** [comment]
감사합니다:)
