### ISSUE TITLE
ModuleNotFoundError: No module named 'konlpy.tag'; 'konlpy' is not a package

### ISSUE THREAD

**Issue by mirseo** [konlpy/konlpy#423]
# ModuleNotFoundError: No module named 'konlpy.tag'; 'konlpy' is not a package

from konlpy.tag import Kkma
from konlpy.utils import pprint
코드를 실행하게 되면 위와 같은 오류가 발생합니다. 이와 같은 오류가 이전에 #issue159에서 발생하였으나
재설치 후에도 동일한 오류가 발생하여 남기게 되었습니다

이 외에는 관련한 이슈에 대한 답을 다른 플랫폼에서 찾을 수 없어 남깁니다.

환경
conda3 / env + python 3.8

**Comment by hexists** [comment]
@arisia-nia 
안녕하세요~
남겨주신 메세지로는 konlpy가 제대로 설치되지 않은 것 같습니다.
좀 더 자세한 정보를 남겨주시면 좋을 것 같아요.
추가로 `conda list`에 konlpy가 포함되어 있는지도 확인해보시면 좋을 것 같습니다.

**Comment by mirseo** [comment]
@hexists 
konlpy                    0.6.0                    pypi_0    pypi
jpype1                    1.4.1                    pypi_0    pypi
konlypy와 JDK , Jpype1 설치 되어있습니다 혹시 어떤 부분을 확인해야 할까요?

전체 오류 내역입니다
Traceback (most recent call last):
  File "c:\Users\star\Music\DEV PROJECT\stock_analysis_block\konlpy.py", line 1, in <module>
    from konlpy.tag import Kkma
  File "c:\Users\star\Music\DEV PROJECT\stock_analysis_block\konlpy.py", line 1, in <module>
    from konlpy.tag import Kkma
ModuleNotFoundError: No module named 'konlpy.tag'; 'konlpy' is not a package

//코드
from konlpy.tag import Kkma
from konlpy.utils import pprint

**Comment by mirseo** [comment]
자바는 다음 버전 사용하고 있습니다
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)

**Comment by mirseo** [comment]
@hexists
다른 설정해야 할 옵션이 있을까요? 설치는 konlpy 페이지를 참조했습니다

**Comment by hexists** [comment]
> @hexists konlpy 0.6.0 pypi_0 pypi jpype1 1.4.1 pypi_0 pypi konlypy와 JDK , Jpype1 설치 되어있습니다 혹시 어떤 부분을 확인해야 할까요?
> 
> 전체 오류 내역입니다 Traceback (most recent call last): File "c:\Users\star\Music\DEV PROJECT\stock_analysis_block\konlpy.py", line 1, in from konlpy.tag import Kkma File "c:\Users\star\Music\DEV PROJECT\stock_analysis_block\konlpy.py", line 1, in from konlpy.tag import Kkma ModuleNotFoundError: No module named 'konlpy.tag'; 'konlpy' is not a package
> 
> //코드 from konlpy.tag import Kkma from konlpy.utils import pprint

@arisia-nia 
전체 오류 내역을 보니, konlpy.py로 파일 이름을 설정한 것으로 보이는데요.
먼저 파일 이름 변경이 필요합니다. package보다 현재 경로의 konlpy.py를 참조하고 있습니다.
확인해보시고 공유 부탁드립니다.

**Comment by mirseo** [comment]
@hexists 
문제 해결했습니다. 감사합니다!
jupyter 로 올려서 하니 잘 되네요 아마 파일 명 문제가 맞았던 거 같습니다. 감사합니다!

**Comment by mirseo** [comment]
@hexists 
파일 명 문제가 맞았던 거 같습니다! 변경하니 문제 해결되었습니다 감사합니다!

**Comment by mirseo** [comment]
# 혹시라도 저와 동일한 문제가 발생하신다면
=> 파일 명을 konlpy.py 대신 다른 이름으로 변경하고 시도해보세요!

**Comment by hexists** [comment]
@arisia-nia 
잘 해결됐다니 다행이네요. 공유 감사합니다.
