### ISSUE TITLE
komoran 사용자 사전 관련 질문 드립니다.

### ISSUE THREAD

**Issue by choyongkyun1** [konlpy/konlpy#424]
user_dict.txt 내용에 **[단어] [\t] [품사]** 형태로 입력했을 땐 사전 설정이 잘 되는데,
**[분석대상어절] [\t] [형태소1/품사1] [ ] [형태소2/품사2] [ ]...** 형태로 입력하면 사전 설정이 안 됩니다.
이렇게 사전 설정을 하고 아래 코드를 실행하면 

     from konlpy.tag import Komoran
     komoran = Komoran(userdic = 'user_dict.txt')

java.lang.NullPointerException 오류가 나오구요.

[[링크]](https://komorandocs.readthedocs.io/ko/latest/manual/manual.html)에 있는 방법대로 해본 것인데요.
komoran에서 두 번째 형태처럼 사전 설정을 하려면 어떻게 하면 될 지 도와주시면 감사하겠습니다.

**Comment by hexists** [comment]
@choyongkyun1 
안녕하세요~
링크를 확인해보니 **기분석사전**에 대해 입력했을 때 사전 설정이 안되고 java.lang.NullPointerException 오류가 발생한 것으로 예상됩니다.
konlpy에서 제공중인 komoran 버전은 3.0으로 가이드에 있는 버전과 차이가 있어 보입니다.

참고로, konlpy에 있는 Komoran user_dict 가이드에는 `단어 \t 품사` 형태만 안내되고 있습니다.

최신 버전의 komoran을 직접 설치해서 **기분석사전** 기능이 되는지 먼저 테스트 해보시길 추천드립니다.

그럼 진행사항 공유 부탁드립니다. 감사합니다.

**Comment by choyongkyun1** [comment]
답변 감사드립니다. 단어 \t 품사 형태의 사전 등록은 잘 되지만 기분석사전 기능은 안 됩니다..ㅠㅠ

그리고 제가 링크한 내용이 PyKomoran에 대한 내용이길래, 혹여나 PyKomoran으로 다시 설치해보았으나 여전히 기분석사전 기능은 안되네요..ㅠㅠ 해결 방법이 없을까요?

konlpy에서의 Komoran, PyKomoran에서의 Komoran 모두 기분석사전 기능이 안 되네요..ㅠㅠ

**Comment by hexists** [comment]
@choyongkyun1 
안녕하세요.
pykomoran에서도 안된다면 해당 github을 통해 문의해보시는 것이 좋을 것 같습니다.
konlpy 이슈는 아니여서 해당 이슈는 종료하겠습니다. 감사합니다.
