### ISSUE TITLE
Kkma()등 분석기 객체 생성시에 파이썬 종료 오류.

### ISSUE THREAD

**Issue by dlsrnsi** [konlpy/konlpy#44]
실행환경 : Python 3.4 win32, JDK,JRE 1.8, window8.1 64bit

tag안에 있는 어떤 NLP분석기들의 객체를 생성해봐도, 파이썬 자체가 실행이 멈춰버립니다.

JVM같은경우에는 jpype.getDefaultJVMPath()를 사용하여 확인했을때, 실제 jvm.dll이 존재하는것을 확인하였구요.

![default](https://cloud.githubusercontent.com/assets/7012023/6200022/aa0cd720-b4a7-11e4-8a1a-5cfbd770891f.JPG)

그리고 jar파일들은 모두 실행이 되는것을 확인하였습니다.

혹시라도 해결방법을 아신다면, 알려주시면 감사하겠습니다

**Comment by dlsrnsi** [comment]
jpype.getDefaultJVMPath()에서 표시되는 JVM이 64bit 용 JVM이었네요..
JAVA_HOME을 python과 같은 32bit JVM의 위치로 바꾸었더니 실행이 되었습니다.

**Comment by e9t** [comment]
잘 해결되었다니 다행입니다! 문제 제기해주셔서 감사합니다 :)

**Comment by JITOO** [comment]
저도 같은오류인데...상세하게 오류 해결법 알려주실수있나요?

**Comment by simhoonnam** [comment]
같은 오류가 있는데 dlsrnsi님이 말씀하시는 JAVA_HOME을 python과 같은 32bit JVM의 위치로 바꾸었더니 다는 것이 어느부분을 바꾸었다는건가요?

**Comment by dlsrnsi** [comment]
python도 32bit용 64bit용이 따로 있고, 자바도 32bit 용 64bit용이 따로 있는데요. 제 오류가 발생했던 이유는 python은 32bit용인데 자바는 64bit용을 써서 발생했던 오류였습니다. 버전을 통일하니 문제가 해결되었어요
