### ISSUE TITLE
ubuntu pip install konlpy  에러가 납니다.

### ISSUE THREAD

**Issue by choikyongho** [konlpy/konlpy#45]
ubuntu버전은 14.10이고  pip install konlpy 단계에서 에러가 납니다.
에러메시지는
error: could not create '/usr/local/lib/python2.7/dist-packages/konlply': Permission denied
입니다.
제 파이썬 버전은 2.7입니다. 문제가 뭔지 모르겠습니다, 감사합니다.

**Comment by e9t** [comment]
권한 문제인듯 합니다.

sudo pip install konlpy

또는 sudoing 권한이 없는 경우 (관리자 권한이 없는 경우)

virtualenv 하에서 설치해보시기 바랍니다.

**Comment by choikyongho** [comment]
정말 감사합니다,.
안그래도 이미 비슷한 사례가 있는 것 같아서 sudo를 붙였더니
문제없이 잘 설치되었습니다,
 
 
-----Original Message-----
