### ISSUE TITLE
JPype1‑0.5.7‑cp27‑none‑win32.whl is not a supported wheel on this platform (설치오류)

### ISSUE THREAD

**Issue by chinjongmin** [konlpy/konlpy#53]
konlpy 설치전 JPype1을 설치하기 위해서
pip install JPype1‑0.5.7‑cp27‑none‑win32.whl 을 실행하면 아래와 같은 오류 메세지가 나옵니다.
  'JPype1‑0.5.7‑cp27‑none‑win32.whl is not a supproted wheel on this platform

![1](https://cloud.githubusercontent.com/assets/11676328/6863994/739cc5bc-d49e-11e4-8290-a04caa64f252.png)

위와 같이 업데이트 시도 후 다시해봐도 안되네요.
인터넷을 뒤져봐도 해결책이 잘 안나와서 여쭤봅니다.

**Comment by littmus** [comment]
사용하시는 파이썬 버전에 맞는 걸 설치하셔야 할거에요
64bit 파이썬을 쓰시는것 같네요

**Comment by e9t** [comment]
@littmus 님 감사합니다 :)

**Comment by jjussen** [comment]
윈도우 7, 파이썬3.4를 사용하고 있습니다.
cp34의 64비트,32비트 다 인스톨 해봤지만 위와 똑같이 not a supported wheel on this platform라고 뜹니다 ㅜㅜ 도움부탁드립니다.
![default](https://cloud.githubusercontent.com/assets/19574384/15545626/fd3eae24-22d7-11e6-9e10-f6c68006a733.PNG)

**Comment by cruishin** [comment]
cp34는 CPython 3.4를 의미합니다. 파이썬 버전은 맞게 쓰신 것 같은데, 파이썬 버전이 32bit 버전인지 확인 하시기 바랍니다. win32는 파이썬 버전과 맞아야 하는 것입니다. 윈도우버전과 맞는것이 아니라...

**Comment by jjussen** [comment]
윈도우 64비트에 파이썬 아나콘다 전부 64비트로 설치했늡니다....ㅜ 위 사진에  첫번째는 64비트 버전 whl실행한 사진이구요... 그래도 플랫폼이 맞지않다네요ㅜ

**Comment by moonsunmi** [comment]
저도 비슷한 문제가 있었는데 stackoverflow에서 아래의 내용을 보고 해결했습니다.
--------------------------------------------------------------------------------------------
I realized that amd64 is not about my Windows, but about the Python version. Actually, I am using a 32 bit Python on a 64 bit Windows. Installing the following file solved the issue:
--------------------------------------------------------------------------------------------
jjussen님이 올리신 실행화면 중에서 win32 버전의 경우는 파일이 없는데 실행하여 생긴 오류로 보입니다. 파일 이름을 잘못 입력하면, 노란 글자 오류 메시지뿐 아니라 빨간 글자 오류 메시지도 함께 뜹니다.

64bit 윈도우를 사용하더라도 amd64가 안 되면 win32를 시도해 보는 게 좋을 거 같습니다.
