### ISSUE TITLE
TypeError: Package kr.lucypark.kkma.KkmaInterface is not Callable

### ISSUE THREAD

**Issue by Joonghee** [konlpy/konlpy#57]
konlpy을 이용한 형태소 분석을 하는 상황에서 오류가 나타나 질문을 드립니다. 
이전에 이슈가 되었던 부분을 검토하고 수정했지만, 다음과 같은 오류가 출력됩니다.

현재 운영체제는 Mac 매버릭스 x64, 파이썬 2.7.9로 터미널상에서 작업하고 있습니다. 

<pre>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yoon/anaconda/lib/python2.7/site-packages/konlpy/tag/_kkma.py", line 82, in __init__
    self.jki = KkmaInterfaceJavaClass() # Java instance
  File "/Users/yoon/anaconda/lib/python2.7/site-packages/JPype1-0.6.0-py2.7-macosx-10.5-x86_64.egg/jpype/_jpackage.py", line 55, in __call__
    raise TypeError("Package {0} is not Callable".format(self.__name))
TypeError: Package kr.lucypark.kkma.KkmaInterface is not Callable
</pre>

**Comment by e9t** [comment]
혹시 Kkma에서만 해당 문제가 발생하나요?
다른 분석기(ex: Twitter)를 사용했을 때도 같은 문제가 발생하는지 확인해주실 수 있나요?

**Comment by KangMinSuc** [comment]
저도 위의 분과 같은 문제가 발생하여 해결하기 위한 방법을 찾고 있습니다만, 쉽지 않네요.
저의 경우에는 Kkma에서 해당 문제가 발생하였습니다.

**Comment by KangMinSuc** [comment]
File "testcook.py", line 27, in <module>
    kkma=Kkma()
  File "/Library/Python/2.7/site-packages/konlpy/tag/_kkma.py", line 87, in __init__
    self.jki = KkmaInterfaceJavaClass() # Java instance
  File "/Library/Python/2.7/site-packages/jpype/_jpackage.py", line 55, in __call__
    raise TypeError("Package {0} is not Callable".format(self.__name))
TypeError: Package kr.lucypark.kkma.KkmaInterface is not Callable

위와 같은 문제가 발생하고 있습니다. 해결책을 강구중인지만, 이에 대해 아시는 바가 있다면 조언좀 부탁드립니다.

**Comment by e9t** [comment]
@KangMinSuc 님, Kkma에서만 문제가 발생하고 Twitter, Komoran 등을 사용할 때는 문제가 발생하지 않는지 확인해주시면 감사하겠습니다.

만일 Kkma만 문제가 있는거라면, Kkma가 로딩하는 사전의 사이즈가 크기 때문에 메모리상에서 발생하는 문제일 수도 있습니다.

참고로, 예전에도 맥에서 유사한 에러가 발생한 적이 있는데 (https://github.com/konlpy/konlpy/issues/6), 당시에도 적절한 힙 메모리 할당으로 문제를 해결한 바 있습니다.

**Comment by KangMinSuc** [comment]
@e9t 님, 다행히 문제를 해결했습니다. Kkma에서만 문제가 발생하였는데, java를 8 version 으로 올림과 동시에, #6  의 힙 메모리 할당으로 해결했습니다. 할당된 힙메모리 영역이 부족하여 발생한 일인듯 합니다. 도움 주셔서 감사합니다.

**Comment by e9t** [comment]
잘 해결되었다니 다행이네요. 이슈를 닫도록 하겠습니다. 감사합니다 :)

**Comment by widian** [comment]
안녕하세요, 저도 같은 문제가 발생하고 있는데 제 경우에는 Kkma뿐 아니라 Twitter, Komoran에서도 발생하고 있습니다. 기존에 맥에서 여러 개의 JVM을 사용중이어서 강제로 JVM 위치를 지정해준 다음에 실행하려고 했지만, init_jvm함수를 정상적으로 실행하지 않고 jpype.JPackage가 있는 블록으로 들어가는 것 같습니다. 혹시 해당 부분을 확인하기 위해서는 어떤 곳을 확인해봐야하는지 알고싶습니다. 

OS는 Mac 10.11 El Capitan 
jdk는 1.8.0 64bit를 쓰고있습니다. 
JPype 버전은 0.6.1입니다. 
Python 버전은 2.7.10 입니다.
