### ISSUE TITLE
global name 'jpype' is not defined in Kkma()

### ISSUE THREAD

**Issue by gnuchoi** [konlpy/konlpy#59]
- Environment: MacOS, Python 2.7, JPype 0.6.0 (or 0.5.7), python and the majority of modules were installed by Anaconda.

Hi, I had this error message when I try to initiate Kkma()
    NameError: global name 'jpype' is not defined
, on the line82 of _kkma.py, where the init function checks jpype.isJVMStarted()

It doesn't throw any error when I manually import jpype in the interpreter. But It fails to import jpype in the _kkma.py, which was confirmed by adding an error message in the *italic* except statement at the beginning of _kkma.py. I also tried to fix it by adding the path of jpype.egg before it imports jpype, still doesn't work. It may be my problem, not konlpy's, but do you have any idea? 

Cheers,
Keunwoo

**Comment by e9t** [comment]
Do the other analyzers -- Komoran, Mecab, Twitter, Hannanum -- return the same error?

**Comment by gnuchoi** [comment]
Thanks! Finally turned out that it was JPype1 problem, which I'm not sure yet since I failed to reproduce the same problem. I removed and installed modules (which I did before thou), the it became another problem, throwing an error message including "__ZNSs4_Rep11_S_terminalE". 

It doesn't seem to be a frequent issue. For those who have a similar problem, please refer to https://github.com/originell/jpype/issues/109, or just try as below on Terminal:
> $ env CXX="clang++ -stdlib=libstdc++" python setup.py install seems to solve the problem.
> (or $ CXX="clang++ -stdlib=libstdc++" if you don't use virtualenv)
(It seems to fix c++ compiler problem.)

Now it's working like a charm.

**Comment by e9t** [comment]
Happy to hear all is well!
