### ISSUE TITLE
konlpy 설치 시 InsecurePlatformWarning 발생

### ISSUE THREAD

**Issue by kimyoungkeun** [konlpy/konlpy#62]
안녕하세요

konlpy 설치 시 99%에서 process 가 kill됩니다

[azureuser@francisco5t2 800_python]$ sudo pip install konlpy
Collecting konlpy
/usr/lib/python2.6/site-packages/pip-7.0.3-py2.6.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading konlpy-0.4.3-py2.py3-none-any.whl (22.4MB)
    99% |████████████████████████████████| 22.4MB 5.1MB/s eta 0:00:01[azureuser@francisco5t2 800_python]$

############
[azureuser@francisco5t2 800_python]$ uname -r
2.6.32-504.12.2.el6.x86_64
[azureuser@francisco5t2 800_python]$ python --version
Python 2.6.6

확인 해 주시면 감사드리겠습니다..

**Comment by e9t** [comment]
이건 pip 쪽 문제 같네요. http://stackoverflow.com/a/29202163/1054939 이렇게 해보시면 어떨까 싶습니다.
(혹시 문제가 해결되시면 이슈 닫아주시기 바랍니다!)

**Comment by e9t** [comment]
안녕하세요. 문제를 해결하신 것으로 간주하고 이슈를 닫도록 하겠습니다.
혹시 문제가 재발되시면 다시 이슈를 열어주시기 바랍니다.
