### ISSUE TITLE
NameError: global name 'jpype' is not defined

### ISSUE THREAD

**Issue by min6053** [konlpy/konlpy#63]
<pre>
>>> from konlpy.tag import Kkma
>>> from konlpy.utils import pprint
>>> kkma = Kkma()

Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    kkma = Kkma()
  File "C:\Python27\lib\site-packages\konlpy\tag\_kkma.py", line 83, in __init__
    jvm.init_jvm(jvmpath)
  File "C:\Python27\lib\site-packages\konlpy\jvm.py", line 21, in init_jvm
    if jpype.isJVMStarted():
NameError: global name 'jpype' is not defined
</pre>

위와 같은 에러가 발생합니다.

환경은 Windows7 32bit / Python 2.7입니다. 그리고 JPype1-0.6.0-cp27-none-win32로 다운받아 설치하였습니다.

**Comment by e9t** [comment]
안녕하세요. 혹시 Komoran, Hannanum, 또는 Twitter를 실행했을 때도 같은 오류가 나나요?
ex:

    from konlpy.tag import Twitter
    twitter = Twitter()

**Comment by krkhnh** [comment]
저도 같은 문제를 겪고있습니다. 그리고 Komoran, Hannanum, 또는 Twitter를 실행했을 때에도 같은 문제가 나옵니다.(하단 코드 참고)

그런데 동일한 코드로 Anaconda가 설치된 interpreter를 이용하면 돌아삽니다. 하지만 virtualenv를 이용하니 오류가 발생합니다. 물론 virtualenv에도 JPype를 설치했습니다.
```
# coding=utf-8
from __future__ import division
from __future__ import unicode_literals
from konlpy.tag import Hannanum, Twitter, Komoran


class KoNLP:
    def __init__(self):
        pass

    @staticmethod
    def word_count(text):
        # h = Hannanum()
        # nouns = h.nouns(text)
        # t = Twitter()
        # nouns = t.nouns(text)
        ko = Komoran()
        nouns = ko.nouns(text)
        return nouns


if __name__ == '__main__':
    konlp = KoNLP()
    tags = konlp.word_count('''그리스 사태가 어디로 흐를지, 불확실성이 커지면서 금융시장은 불안한 모습입니다.

주가, 유가는 떨어졌고 금값은 올랐습니다.

뉴욕 이언주 특파원입니다.

◀ 리포트 ▶

그리스 채권 최대 보유국인 독일 증시는 1.5%, 2위 보유국인 프랑스 증시는 2% 밀렸습니다.

장중 백 포인트 이상 떨어지며 출렁였던 뉴욕 다우지수는 지난 주말보다 46포인트 하락한 17,683으로 마감됐습니다.

등락을 거듭했던 나스닥 지수는 0.34%, S&P 지수는 0.39% 하락했습니다.

그리스 국민투표 이후 구제금융 재협상이 어떻게 전개될지 불확실성이 커지면서 투자 심리가 위축된 탓입니다.

유로존 경기 침체 우려로 국제유가도 하락해, 8월 인도분 서부 텍사스산 원유는 지난 주말보다 7.7% 떨어진 배럴당 52.53 달러로 지난 4월 이후 최저치를 기록했습니다.

반면 안전 자산인 금값은 온스당 1,173달러로 1% 가까이 올랐습니다.

[엘르 케플란/경제분석가]
"너무 많은 불확실성 때문에 세계적으로 주식을 매도하고 있습니다. 반면 안전 자산으로 몰리고 있습니다."

국제통화기금, IMF는 "그리스 상황을 면밀하게 관찰하고 있으며, 지원 요청이 오면 도울 준비가 돼있다"고 밝혔습니다.

또, 미국 백악관은 그리스가 경제 성장의 길을 걸으면서 유로존을 탈퇴하지 않도록 타협할 것을 그리스와 유럽연합 지도부에 촉구했습니다.

뉴욕에서 MBC뉴스 이언주입니다. ''')

    for tag in tags:
        print(tag)
```

**Comment by krkhnh** [comment]
이유를 찾아냈고 고쳤습니다.

패키지를 하나씩 지워가며 확인한 결과, `numpy`가 없으면 해당 에러가 발생하였습니다. 이를 설치하고나면 `NameError: global name 'jpype' is not defined` 에러가 사라집니다.

이유는 모르겠지만, `numpy`를 `konlpy`의 dependency로 추가하시는 것을 고려해주시면 감사하겠습니다.

**Comment by e9t** [comment]
@krkhnh님, 안녕하세요.
일단 numpy는 jpype나 konlpy의 dependency는 아닙니다만, jpype 설치시에 C 컴파일러가 필요합니다.
따라서 C 컴파일러에 대한 환경변수나 적절한 path 지정이 안된 경우 jpype가 정상적으로 동작하지 않을 수 있는데, numpy를 설치함으로써 아마 그 문제가 해결되지 않았나 생각합니다.

dependency는 가급적이면 줄이는게 좋고, numpy는 konlpy와 무관한 패키지이기 때문에 dependency로 추가하는 것이 가장 바람직한 해결책은 아닐 것 같습니다만, 같은 에러가 발생하는 경우 누구든 시도해볼만한 좋은 work-around라고 생각합니다.

원인 확인과 문제 해소 방법을 알려주셔서 감사합니다 :)

**Comment by krkhnh** [comment]
그럼 혹시 말씀하신대로 path지정이 문제가 된걸까요? 정확한 문제가 궁금해집니다.

**Comment by e9t** [comment]
현재로서는 가장 가능성 높은 옵션인 것 같습니다만, 동일한 현상을 replication 시킬 수 있어야 원인을 명확히 규명할 수 있을 것 같습니다.

**Comment by e9t** [comment]
@krkhnh 님, 다시 한번 말씀해주신 덕분에 원인이 무엇일지 다시 찾아봤습니다.
제가 잘못 알고 있던 부분이 있는데, [numpy가 JPype1의 dependency](https://github.com/originell/jpype/blob/master/setup.py#L188)라고 하네요.

만일 말씀하신대로 numpy를 설치하고 나서 문제가 해결됐다면, jpype 설치 모듈에 잡지 못한 boundary condition이 있을지도 모르겠네요. 일단 konlpy의 직접적인 문제는 아니니 jpype 팀이 해결해주길 바라며 이슈는 닫도록 하겠습니다.
하지만 간접적으로 영향을 주는 이슈이니만큼 말씀하신대로 documentation에 명시하는 것도 좋다고 생각합니다.
