### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005) 종료 발생

### ISSUE THREAD

**Issue by JITOO** [konlpy/konlpy#67]
``` python
from konlpy.tag import Twitter
twitter = Twitter(jvmpath=None)
print(twitter.morphs(u'단독입찰보다 복수입찰의 경우'))
```

간단한 예제를 해봤는데 정상 실행 되지않고 Process finished with exit code -1073741819 (0xC0000005) 이렇게 종료가 되네요. 이유를 알수 있을까요

**Comment by JITOO** [comment]
한달 전에 문제 없이 됐었는데 갑자기 안되서 JPype 문제 인거 같아서 찾아봤는데 해결이 되질 않네요

**Comment by e9t** [comment]
안녕하세요. 말씀하신 것과 같이 JPype가 JVM을 구동하다가 메모리 관련 이슈로 프로세스가 죽은 것 같네요.

혹시 위에서 보여주신 코드를 한 줄 씩 파이썬 interpreter에서 실행을 해보셨나요? 그 때 2번째 줄에서 crash되고 있는 것이 맞나요? 만일 그렇다면 interpreter에서 `import jpype; jpype.startJVM()`만 실행했을 때도 마찬가지 원인으로 crash하나요?
한달 전에 문제 없이 작동했는데 지금 작동하지 않는다고 하셨는데, 혹시 여러번 실행해도 계속 같은 메세지로 프로세스가 죽나요? (즉, 문제에 randomness가 없나요?)

만일 crash report 전체를 같이 올려주실 수 있으면, 같이 debugging해볼 수 있을 것 같습니다.
일단은 [이 질답](http://stackoverflow.com/questions/19325242/exception-access-violation-0xc0000005)이 도움이 될 수 있을 것 같습니다. (만일 이 질답에서 다루는 것과 같은 문제라면, 해결법은 아니더라도 사용해볼만한 우회법이 나와 있는 것 같네요.)

**Comment by sipall** [comment]
저도 같은 오류가 생기는데 여러곳에서 찾아본 결과 jpype-0.6.0 버전에서의 문제라고 해서 jpype-0.5.7버전을 다시 설치를 하였지만 오류가 해결되지 않네요

**Comment by JITOO** [comment]
interpreter 에서 import jpype; jpype.startJVM() 실행해봤을때 역시 crash 하고, 여러번 실행해도 매번 같은 결과가 나옵니다.....

**Comment by lgj9172** [comment]
저도 이 문제 때문에 하루종일 고생하다가 결국에 해결했습니다.

파이썬을 32비트로 깔았으면 jvm도 32비트여야 하고 jpype도 32비트로 맞춰주셔야 합니다.

하나라도 다른비트로 하면 저런 오류가 나더군요.

**Comment by widian** [comment]
해당 레포지토리에서 생긴 이슈는 아니지만, @lgj9172 님의 글에서 힌트를 얻어 해결했기 때문에 글타래 남깁니다..

Mac OSX에서 jpype의 getDefaultJVMPath() 가 32bit libjvm.dylib을 가리키고 있는 것으로 보여집니다. 그래서 이를 해결하기 위해 Oracle에서 정상적으로 Java SDK 1.8.0 64bit를 받은 뒤에, 해당 dylib을 가리키도록 하였더니 정상작동되었습니다.

제가 startJVM 실행 시에 사용한 루트는 다음과 같습니다. "/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/server/libjvm.dylib"

JVM을 64bit 으로 사용하기 위해 jpype를 64bit환경에서 재빌드하였습니다.

**Comment by e9t** [comment]
지난 몇 달에 걸쳐 이 문제에 대한 리포팅이 꾸준히 들어왔습니다:

- https://github.com/konlpy/konlpy/issues/54
- https://github.com/konlpy/konlpy/issues/55
- https://groups.google.com/d/msg/konlpy/FLFX2ka3esQ/SXAO5nb6BQAJ
- https://groups.google.com/d/msg/konlpy/igl1_Uh7YTg/dZlPAokfCwAJ

공통적으로, 프로그램들의 비트 수가 맞지 않는 경우 파이썬이 crash하는 증상이 나타났고,
프로그램들을 운영체제 비트수에 맞게 재설치하는 것으로 해결되었습니다.
앞으로는 다른 유저들이 이 문제를 피할 수 있도록 문서에 경고문을 추가하는 것이 좋을듯합니다.

문제를 발견하고 해결법을 멋지게 찾아주신 많은 분들께 진심으로 감사드립니다 :+1:
