### ISSUE TITLE
Error occurred during initialization of VM Unable to load native library: Can't find dependent libraries

### ISSUE THREAD

**Issue by HwangYongHa** [konlpy/konlpy#68]
Konlpy 패키지를 사용해 간단한 예제를 만들었었는데 갑자기 Konlpy 패키지가 작동되지않습니다. 
처음엔 JVM PATH 문제가 발생해서 해결했는데 위 제목과같은 오류가 뜨네요~~ 도와주세요

**Comment by e9t** [comment]
혹시 예제를 만드신 이후 JDK를 업그레이드 한 적이 있으신가요?
[이 질답](http://stackoverflow.com/questions/2516890/error-occurred-during-initialization-of-vm)에 따라 환경변수 `PATH`에 Java 바이너리들이 정상적으로 들어가있는지 확인해보시면 좋을 것 같습니다.

**Comment by e9t** [comment]
@HwangYongHa 님, 이 문제는 해결하셨나요?
혹시 해결하셨다면 해결하신 방법을 간략하게나마 말씀해주시면 다른 분들에게도 많은 도움이 될 거라고 생각합니다.

**Comment by e9t** [comment]
이슈를 닫도록 하겠습니다. 문제가 재발하는 경우 다시 이슈를 열어주세요.
