### ISSUE TITLE
Python 형태소 질문입니다. Konlpy 및 오픈한글 API 를 이용해 문장의 긍정/부정을 수치값으로 표현하였는데요.

### ISSUE THREAD

**Issue by HwangYongHa** [konlpy/konlpy#70]
Python 형태소 질문입니다. Konlpy 및 오픈한글 API 를 이용해 문장의 긍정/부정을 수치값으로 표현하였는데요. 한글 형태소는 명사,형용사,동사,부사 등 있지만 이러한 값으로 문장의 분위기를 추출 할때
문장의 빠르기, 즉 문장의 긴장/평온 을 표현할 알고리즘 설계에 어려움을 겪고있습니다. 
긍정/부정 은 오픈한글 API 를 이용해 쉽게 수치화 하였지만 문장의 빠르기를 수치화하는데 부사를 이용해야할것같습니다. 하지만 임의로 부사에 점수를 주면 신뢰성이 떨어지는 알고리즘이 됩니다. 
유용한 API 이나 알고리즘 설계 방법을 알고계시면 꼭좀 부탁드립니다. 
사진은 대략적인 알고리즘 설계를 사진으로 나타낸것입니다.

**Comment by HwangYongHa** [comment]
사진입니다

**Comment by e9t** [comment]
안녕하세요.
재미있는 연구를 하고 계신 것 같습니다만, 본 프로젝트와 관련이 없는 질문이므로 이슈는 닫도록 하겠습니다.
아마 말씀하신 질문은 https://www.facebook.com/groups/babelPish/ 와 같은 커뮤니티에서 더 많은 분들께서 적극적으로 해결해주실 것 같네요 :) 좋은 결과 있기를 바랍니다!
