### ISSUE TITLE
ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.

### ISSUE THREAD

**Issue by Kwon-joo-hyun** [konlpy/konlpy#71]
<pre> File "C:\Python33\lib\site-packages\konlpy\__init__.py", line 15, in <module>
    from . import tag
  File "C:\Python33\lib\site-packages\konlpy\tag\__init__.py", line 11, in <module>
    from ._twitter import Twitter
  File "C:\Python33\lib\site-packages\konlpy\tag\_twitter.py", line 4, in <module>
    import jpype
  File "C:\Python33\lib\site-packages\jpype\__init__.py", line 18, in <module>
    from ._jpackage import *
  File "C:\Python33\lib\site-packages\jpype\_jpackage.py", line 18, in <module>
    import _jpype
ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.
</pre>

안녕하세요. 아래와 같은 환경에서 구축을 하고 예제 프로그램 실행을 했는데 에러가 발생이 됩니다.
- 환경 : python 3.3
- 설치 파일 : konlpy, jsonlib_python3-1.6.1-cp33-none-win_amd64.whl
- java version : java version "1.8.0_31"

예제소스

<pre>
from konlpy.tag import Kkma
from konlpy.utils import pprint

kkma = Kkma(jvmpath='C:/Program Files/Java/jre1.8.0_31/bin/server/jvm.dll')
pprint(kkma.sentences('네, 안녕하세요. 반갑습니다.'))
</pre>

**Comment by e9t** [comment]
안녕하세요! 혹시 파이썬 인터프리터에서 `import jpype`만 해도 같은 오류가 뜨나요?
만일 그렇다면 konlpy의 dependency인 jpype가 정상적으로 설치가 안된 것일 수 있습니다.
3.3 쓰시니 `pip3 install JPype1-py3` 로 인스톨 하시거나, 윈도우 OS 사용하신다면 https://github.com/konlpy/konlpy/issues/35 에서와 같이 Windows binaries를 사용해 설치해보시면 어떨까 싶습니다.

**Comment by e9t** [comment]
이슈를 닫도록 하겠습니다. 혹시 문제가 해결되신 것이 아니라면 이슈를 다시 열어주시기 바랍니다.

**Comment by daewonyoon** [comment]
window 64 / python 3.5.1 64bit / konlpy 0.4.4 / jpype1 0.6.1 ( windows binary 를 다운받아 pip 로 설치)

이런 환경에서 동일한 문제가 발생했습니다. 처음 설치할 때에는 jdk 설치/설정을 하지 않아 그 문제라고 생각했지만, jdk 를 설치/설정한 후에도 동일한 문제가 발생하였습니다.

확인해 보니, site-packages\_jpype.cp35-win_amd64.pyd 가 MSVCP140.dll 디펜던시를 가지고 있어서 문제가 발생했었습니다.

visual c++ redistributable for visual studio 2015 을 깔아주면 해결될 듯 합니다.
(해당 재배포패키지를 언인스톨하고 테스트하면 문제 재현이 가능할 것 같아요.)
