### ISSUE TITLE
'Kkma().nouns' raises 'jpype._jexception.java.lang.OutOfMemoryErrorPyRaisable' on a weird sentence

### ISSUE THREAD

**Issue by krkhnh** [konlpy/konlpy#73]
```
from konlpy.tag import Kkma

text = '@ninsho111 ㄴ슫ㅋㅋㄱㅋㄷㄷㄱㄱㄷㄱㅋ아진ㄴㄴ자거위님ㅁㅁ넘유쾤ㄱ핵ㅋㄱㅋㄷㄱㄱㅋㄱㅋㄱㄱㅋㅅ후..저..자야조..eㅎㅇㄱㄱ.....ㄹ오늘ㄹ은ㅁ샐라고한거아닌ㄴ데...츄우기....거위님ㅁ보니가치킨ㄴ먹ㄱ고싶어요...꿈ㅁ에서 네네치킨ㄴ먹ㄱ을래욛...(기절'

nouns = Kkma().nouns(text)
```

위 `text`를 `Kkma().nouns(text)`식으로 수행하면 에러가 발생할 때까지 CPU와 메모리 리소스를 최대한으로 사용합니다. 그리고 몇 분 뒤에 `jpype._jexception.java.lang.OutOfMemoryErrorPyRaisable`에러가 발생하면서 종료됩니다.

다른 NLP는 문제가 없습니다.

**Comment by e9t** [comment]
중요한 버그를 발견하셨네요. 올려주신 예시에는 띄어쓰기가 없는데, 꼬꼬마가 그런 긴 텍스트에 취약한 것 같습니다. 버그리포팅 감사합니다. :+1: 말씀해주신 사항은 KoNLPy에서 해결할 수 없는 문제이기 때문에, 문서에 관련 내용을 추가하고, 이슈는 닫도록 하겠습니다.
