### ISSUE TITLE
Mac (Yosemite 10.10.4) 에서 실행 시 자바 런타임을 찾을 수 없는 문제

### ISSUE THREAD

**Issue by suminb** [konlpy/konlpy#76]
맥에서 `konlpy` 를 설치하고 `kkma.nouns()` 를 호출하면 다음과 같은 오류 메세지와 함께 자바 6를 설치하라는 안내 창이 뜹니다.

~~~
No Java runtime present, requesting install.
~~~

<img width="532" alt="screen shot 2015-09-06 at 1 56 13 am" src="https://cloud.githubusercontent.com/assets/136119/9700350/81662794-543a-11e5-96f5-4dcfcc9f3fc1.png">

현재 시스템에는 자바 7이 설치되어있습니다.
~~~
$ java -version             
java version "1.7.0_51"                                         
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)            
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode) 
~~~

JRE뿐만 아니라 JDK도 설치 되어있습니다.
~~~
$ javac -version
javac 1.7.0_51
~~~

**Comment by e9t** [comment]
제 맥북에서는 같은 문제가 재현이 안되는데, 혹시 사용하신 konlpy의 버젼을 확인해주실 수 있나요?
또, `kkma.nouns()`에만 해당 문제가 발생하나요? (예를 들어 `kkma.pos()`, `twitter.nouns()`는 정상 작동 하나요?)

**Comment by suminb** [comment]
konlpy 버전은 0.4.3 입니다.

    >>> konlpy.__version__
    '0.4.3'

처음에 잘못 말씀드린 부분이 있는데, `kkma.nouns()` 를 호출할 때 자바 런타임 설치 창이 뜨는 것이 아니라 다음과 같이 `Kkma` 인스턴스를 생성할 때 그런 창이 뜹니다.

    kkma = Kkma()

**Comment by yooncobra** [comment]
인스턴스에 대해 잘 모르지만 저도 비슷한 문제인 거 같습니다.

>>> from konlpy.tag import Kkma
>>> from konlpy.utils import pprint
>>> kkma = Kkma()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/konlpy/tag/_kkma.py", line 83, in __init__
    jvm.init_jvm(jvmpath)
  File "/Library/Python/2.7/site-packages/konlpy/jvm.py", line 42, in init_jvm
    '-ea', '-Xmx768m')
  File "/Library/Python/2.7/site-packages/jpype/_core.py", line 50, in startJVM
    _jpype.startup(jvm, tuple(args), True)
RuntimeError: Unable to load DLL [/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib], error = dlopen(/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib, 9): no suitable image found.  Did find:
	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib: mach-o, but wrong architecture at native/common/include/jp_platform_linux.h:45

참고로 python 2.7.10이고 
java version "1.8.0_60"입니다.
이상 하게도 파이썬에서 konlpy버전은 확인 되지 않습니다.

**Comment by uptown** [comment]
안녕하세요 살포시 thread에 껴봅니다 ...
>>> from konlpy.tag import Kkma
>>> from konlpy.utils import pprint
>>> kkma = Kkma()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/konlpy/tag/_kkma.py", line 83, in
__init__
    jvm.init_jvm(jvmpath)
  File "/Library/Python/2.7/site-packages/konlpy/jvm.py", line 42, in
init_jvm
    '-ea', '-Xmx768m')
  File "/Library/Python/2.7/site-packages/jpype/_core.py", line 50, in
startJVM
    _jpype.startup(jvm, tuple(args), True)
RuntimeError: Unable to load DLL
[/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib],
error =
dlopen(/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib,
9): no suitable image found.  Did find:
/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib:
mach-o, but wrong architecture at
native/common/include/jp_platform_linux.h:45

pip로 설치했고, Java7이 있는데 Java6깔라고해서 깐상황입니다.


2015-09-22 15:50 GMT+09:00 Yoonsang Soh <notifications@github.com>:

> 인스턴스에 대해 잘 모르지만 저도 비슷한 문제인 거 같습니다.
>
> from konlpy.tag import Kkma
> from konlpy.utils import pprint
> kkma = Kkma()
> Traceback (most recent call last):
> File "", line 1, in
> File "/Library/Python/2.7/site-packages/konlpy/tag/*kkma.py", line 83, in
> __init_*
> jvm.init_jvm(jvmpath)
> File "/Library/Python/2.7/site-packages/konlpy/jvm.py", line 42, in
> init_jvm
> '-ea', '-Xmx768m')
> File "/Library/Python/2.7/site-packages/jpype/_core.py", line 50, in
> startJVM
> _jpype.startup(jvm, tuple(args), True)
> RuntimeError: Unable to load DLL
> [/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib],
> error =
> dlopen(/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib,
> 9): no suitable image found. Did find:
> /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib:
> mach-o, but wrong architecture at
> native/common/include/jp_platform_linux.h:45
>
> 참고로 python 2.7.10이고
> java version "1.8.0_60"입니다.
> 이상 하게도 파이썬에서 konlpy버전은 확인 되지 않습니다.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/konlpy/konlpy/issues/76#issuecomment-142195846>.
>



-- 
Lee, Juyoung
T: +82 10 7534 4758
E: mail@juyoung.me, lee.juyoung04@gmail.com
S: Blog <http://juyoung.me/>, Facebook <https://www.facebook.com/uptownlee>
, Google+ <https://plus.google.com/u/0/114403518756952136463>

**Comment by sunghyunzz** [comment]
저도 같은 문제가 있네요.

    $ java -version
    java version "1.8.0_60"
    Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
    Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

Java 8이 설치된 상황에서, Legacy Java6 설치를 요구하여 이를 설치하였습니다.

그리고 다시 실행시켜보니 위와 동일한 Traceback이 출력되네요.

    Traceback (most recent call last):
      File "test.py", line 4, in <module>
        kkma = Kkma()
      File "/Users/sunghyunzz/dev/tmp/env/lib/python3.5/site-packages/konlpy/tag/_kkma.py", line 83, in __init__
        jvm.init_jvm(jvmpath)
      File "/Users/sunghyunzz/dev/tmp/env/lib/python3.5/site-packages/konlpy/jvm.py", line 42, in init_jvm
        '-ea', '-Xmx768m')
      File "/Users/sunghyunzz/dev/tmp/env/lib/python3.5/site-packages/jpype/_core.py", line 50, in startJVM
        _jpype.startup(jvm, tuple(args), True)
    RuntimeError: Unable to load DLL [/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib], error = dlopen(/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib, 9): no suitable image found.  Did find:
        /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib: mach-o, but wrong architecture at native/common/include/jp_platform_linux.h:45

**Comment by mwkang** [comment]
http://stackoverflow.com/questions/15029760/jpype-wont-compile-properly
여기와 비슷한 문제는 아닐까요?
JAVA_HOME이 잘못 설정되었다는 것 같은데..

**Comment by shaynekang** [comment]
확인해보니 konlpy의 문제는 아닌 것 같고, [MacOS에서 자바 레거시 버전(1.6)을 지원하는 설치 파일](https://support.apple.com/kb/DL1572?locale=en_US)의 문제 + jpype가 최신 버전의 libjvm.dylib을 찾아주지 못하는 문제 같습니다.

파이썬 콘솔(터미널에서 python을 입력)에서
```python
>> import jpype

>> jpype.getDefaultJVMPath()
>> jpype.startJVM(jpype.getDefaultJVMPath())

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shaynekang/.pyenv/versions/2.7.10/lib/python2.7/site-packages/jpype/_core.py", line 50, in startJVM
    _jpype.startup(jvm, tuple(args), True)
RuntimeError: Unable to load DLL [/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib], error = dlopen(/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib, 9): no suitable image found.  Did find:
  /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib: mach-o, but wrong architecture at native/common/include/jp_platform_linux.h:45
```

와 같은 에러가 나오면 비슷한 문제라고 보시면 될 것 같고, 터미널에서 libjvm.dylib의 아키텍쳐를 살펴봤을 때(제 컴퓨터 기준```lipo -info /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib```) 결과값이 x86_64가 아닌 i386이 나오면 마찬가지로 비슷한 문제라고 보시면 될 것 같습니다.

제가 해결한 방법은

1. 최신 버전의 Java를 설치합니다: [설치 페이지](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)에서 Mac OS X x64 최신 버전(제 경우는 jdk-8u60-macosx-x64.dmg)을 다운받고 설치합니다.
1. 터미널에서 ```export JAVA_HOME=$(/usr/libexec/java_home)``` 을 실행합니다.
1. 파이썬 콘솔에서 libjvm.dylib를 잘 찾아오는지 테스트합니다.

```
```python
>> import jpype
>> jpype.getDefaultJVMPath()
>> jpype.startJVM(jpype.getDefaultJVMPath())
```

아무런 에러가 없으면 잘 해결되었다고 볼 수 있고, 마지막으로 ~/.bash_profile에 ```export JAVA_HOME=$(/usr/libexec/java_home)```을 입력해주시면 됩니다.

**Comment by e9t** [comment]
많은 분들의 기여 감사합니다.
일단 @shaynekang 님의 말씀대로 [Java 1.8](https://bugs.openjdk.java.net/browse/JDK-7131356)의 버그인 것으로 확인했고, 원칙적으로는 JPype에서 해결하면 좋은 문제이긴 합니다.

하지만 KoNLPy 단에서도 조치를 취할 수 있는 방법이 있어 패치를 해두었으니, 문제가 있으신 분들은 0.4.4로 버전업해주시면 감사하겠습니다.

**Comment by shaynekang** [comment]
:+1:

**Comment by suminb** [comment]
@shaynekang 님 말씀대로 JDK 최신 버전 설치하고 `JAVA_HOME` 환경 변수 설정하니까 문제가 해결 되었습니다. 패치해주신 @e9t 님께도 감사드립니다.

**Comment by jangxyz** [comment]
@shaynekang 감사합니다.

**Comment by noeul** [comment]
@shaynekang 저도 같은 문제가 있었는데 이 글 덕분에 해결했습니다. 감사합니다.

**Comment by Luthiel** [comment]
같은 문제가 발생했었는데, python terminal에서는 해결되었으나, jupyter ( ipython notebook ) 에서는 해결되지 않았습니다. (konlpy버전은 0.4.4입니다.) 제 생각에 ipython notebook IDE자체가 어떤 이유로인해 jvm의 path를 잘 받아오지 못해서 생기는 문제인것 같습니다. 약간 무식한 방법이지만, 저는 konlpy 패키지의 jvm.py 파일에서 jvmpath의 기본값을 최신 jdk 폴더로 바꾸어서 해결하였습니다. 혹시나 비슷한 문제를 겪었는데 jupyter 사용자 분들께서 참고하시면 좋을것 같습니다.

**Comment by XoDNr** [comment]
저도 같은 방법으로 해결은 했으나.. 다음과 같은 에러가 발생하네요

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "konlpy/tag/_kkma.py", line 91, in __init__
    self.jki = KkmaInterfaceJavaClass()  # Java instance
  File "/usr/local/lib/python2.7/site-packages/jpype/_jpackage.py", line 55, in __call__
    raise TypeError("Package {0} is not Callable".format(self.__name))
TypeError: Package kr.lucypark.kkma.KkmaInterface is not Callable

ㅠ_ㅠ...

**Comment by seungilyou** [comment]
제 경우는 info.plist 를 수정하는 것으로 해결했습니다. (Legacy java6 는 깔지 않았습니다.)

http://stackoverflow.com/questions/26847411/to-open-eclipse-you-need-to-install-the-legacy-java-se-6-runtime

**Comment by juice500ml** [comment]
@e9t 님, Java 1.7에서도 동일한 문제가 발생하는 것 같습니다. Commit 1f9f419924d03cdd64fafd98f37d38078619912f 에서 Line 44를 삭제하는건 어떨까요?

**Comment by onlymytho** [comment]
같은 문제인 TypeError: Package kr.lucypark.kkma.KkmaInterface is not Callable 오류를 겪고 있습니다.
사용 환경은 다음과 같습니다.
```
OS : macOS Sierra 10.12.3 버전
konlpy : 0.4.4 버전
Java : Legacy Java6 (실행 중에 설치하라고 한 버전을 설치)
```

위에서 @shaynekang 님이 말씀해주신 아래 코드를 파이썬에서 실행해보면 오류없이 잘 작동하는데, 여전히 오류를 겪고 있습니다.
```
import jpype
jpype.startJVM(jpype.getDefaultJVMPath())
```

어떤 조치를 취해야할까요?

**Comment by onlymytho** [comment]
자문자답합니다. 결국 @shaynekang 님의 답변을 통해 해결했는데요, 위에서 말한대로
```
import jpype
jpype.startJVM(jpype.getDefaultJVMPath())
```
이 부분은 에러가 없었지만, 

```
터미널에서 libjvm.dylib의 아키텍쳐를 살펴봤을 때(제 컴퓨터 기준lipo -info /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib) 결과값이 x86_64가 아닌 i386이 나오면 마찬가지로 비슷한 문제라고 보시면 될 것 같습니다.

제가 해결한 방법은

최신 버전의 Java를 설치합니다: 설치 페이지에서 Mac OS X x64 최신 버전(제 경우는 jdk-8u60-macosx-x64.dmg)을 다운받고 설치합니다.
터미널에서 export JAVA_HOME=$(/usr/libexec/java_home) 을 실행합니다.
파이썬 콘솔에서 libjvm.dylib를 잘 찾아오는지 테스트합니다.

아무런 에러가 없으면 잘 해결되었다고 볼 수 있고, 마지막으로 ~/.bash_profile에 export JAVA_HOME=$(/usr/libexec/java_home)을 입력해주시면 됩니다.
```
이 부분을 그냥 진행해봤는데, 해결이 되었습니다. 감사합니다. (비록 다른 문제가 터졌지만ㅜㅡㅜ)

**Comment by insmile** [comment]
OS : windows7 64bit
jdk : 1.8.0_144
python : 3.6.2
konlpy : 0.4.4
위 환경에서 동다일한 문제가 발생 하셨습니다.

제 경우는 JAVA_HOME 도 이상이 없었지만
path 맨 앞 부분에  "%JAVA_HOME%\bin;"  를 추가하고 나니 해결이 되었습다. ^^ 
혹시 도움이 될까 해서 적어 봅았습니다.

**Comment by hyojunmoon** [comment]
Mac high sierra
jdk 1.8
python 3.6
konlpy: 0.4.4

터미널 파이썬에서는 작동되고, 주피터 노트북에서만 작동되지 않는 경우가 있습니다.

---------------------------------터미널---------------------------------
>>> import jpype
>>> jpype.getDefaultJVMPath()
'/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/jli/libjli.dylib'
---------------------------------터미널---------------------------------

---------------------------------주피터---------------------------------
In [24]:
jpype.getDefaultJVMPath()
Out[24]:
'/System/Library/Frameworks/JavaVM.framework/JavaVM'
---------------------------------터미널---------------------------------

볼 수 있다시피 JVMPath를 다르게 잡습니다. 

jvmfinder에 문제가 있는 것인데, 

첫 번째 해결방법은 조금 무식하게, 사용하려는 라이브러리 파이썬 파일에 들어가서 __init__ 함수의
jvmpath = None -> 을 터미널의 jpype.getDefaultJVMPath() 리턴값을 바꿔주는 방법입니다.

두 번째 해결방법은 JVM 폴더에 접근해서, 아나콘다의 파이썬 -> site_packages -> JPype 폴더에 들어가서
_darwin.py를 찾아
if current >= StrictVersion('10.6') and current < StrictVersion('10.9'): <- 이 부분을 바꿔주면 되는 것 같습니다.

10.9 -> 10.15정도로 바꾸면 해결되더군요

**Comment by leedh** [comment]
저도 비슷한 오류가 뜨는데 해결방법을 못 찾겠네요. :(

개발환경
- macOS Sierra 10.12.5
- python 3.6.5 anaconda
- konlpy 0.4.5
- java 1.8.0_171

<img width="1001" alt="screen shot 2018-08-13 at 12 28 47 pm" src="https://user-images.githubusercontent.com/29495950/44011621-903e8812-9ef4-11e8-8bdc-a369b507e67a.png">

**Comment by insmile** [comment]
환경 OS : Windows10
        java version : java version "10.0.2" 2018-07-17

저의 경우는 
1.jdk 버젼을 최신걸로 올렸어요
2.C:\Program Files\Java\jdk-10.0.2\bin\ 및에 client 폴더가 없어서 임의로 만들고 jvm.dll 을 여기에 넣어주니 해결이 되었습니다.
