### ISSUE TITLE
windows7 32bit + python2.7 + pip 7.1.2 + JPype1‑0.6.1‑cp27‑none‑win32.whl + konlpy 설치

### ISSUE THREAD

**Issue by likerainsun** [konlpy/konlpy#83]
<pre>
>>> from konlpy.tag import Kkma
ImportError: numpy.core.multiarray failed to
>>> from konlpy.tag import Kkma
>>> Kkma()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\konlpy\
    jvm.init_jvm(jvmpath)
  File "C:\Python27\lib\site-packages\konlpy\
    if jpype.isJVMStarted():
NameError: global name 'jpype' is not defined
</pre>

안녕하세요 위처럼 jpype가 제대로 설정이 안된 것 같은데 버전이 문제일까요?
0.5.7버전을 안깔아서 문제인 걸까요?
이 버전은  github에  whl은 없고 소스파일로 있던데...이걸 설치해야하는건지..
윈도우즈로 하려니 복잡하네요.

**Comment by e9t** [comment]
안녕하세요. jpype가 제대로 설치되지 않아 생기는 문제인듯합니다.
이 문제인지 확인해보기 위해서는 파이썬 쉘에서 `import jpype`를 입력해보시면 됩니다.

말씀하신 환경 하에서는 [KoNLPy 설치 방법](http://konlpy.org/ko/v0.4.4/install/#id2) 중 4번에 나와 있는대로 [이 링크](http://www.lfd.uci.edu/~gohlke/pythonlibs/#jpype)에 있는 `JPype1‑0.6.1‑cp27‑none‑win32.whl`를 다운로드 받은 후, `pip install JPype1‑0.6.1‑cp27‑none‑win32.whl`를 입력하시면 jpype를 설치하실 수 있습니다. 그 이후 다시 한 번 실행해보시기 바랍니다.
