### ISSUE TITLE
flask(웹서버)에서 konlpy를 사용하려고 할 때 에러가 뜹니다.

### ISSUE THREAD

**Issue by rudvlf0413** [konlpy/konlpy#85]
<img width="691" alt="2015-11-29 5 41 43" src="https://cloud.githubusercontent.com/assets/6302455/11456120/81438acc-96c0-11e5-98df-278a449c9a3c.png">

konlpy.tag.Twitter()를 사용할 때 이 에러가 떴습니다.
아마 jpype의 문제일듯 싶은데요
이를 어떻게 해결해야할지 모르겠습니다...

**Comment by chuckgu** [comment]
전 django로 사용하는데 같은 에러가 나네요..

방법이 없을까요?

**Comment by seviyorm** [comment]
아 이글을 올린지 오래되었는데 이 글 올리고 며칠뒤에 해결했습니다!

jpype 문제인것 같습니다.

routing하는 코드에다가 jpype.attachThreadToJVM() 함수를 붙이면 해결이되더군요
konlpy가 java virtual machine으로 wrapper를 이용한것 같더라구요. 그래서 jvm을 위해 위와 같은 코드가 필요 한 것 같습니다.(jvm과의 쓰레드를 추가하는 함수인 것 같습니다만 자세히는 모르겠습니다 ㅠㅠ)

예를들어 저는 다음과 같이 했습니다.
@app.route('/sentimentWord/<word>')
def determineWord(word):
	jpype.attachThreadToJVM()

**Comment by blissray** [comment]
감사합니다. 옛날 이야기지만 곤란한 일에서 벗어 났네요 :)

**Comment by e9t** [comment]
django나 flask 등 여러 개의 쓰레드를 돌리는 웹서버를 사용하시는 분들은 위에서 @seviyorm 께서 말씀해주신대로 `jpype.attachThreadToJVM()`를 코드에 추가해보시기 바랍니다. (@seviyorm 님 감사합니다!)

추가적으로, 멀티쓰레드를 다루시는 분들은 [이 이슈](https://github.com/originell/jpype/issues/84)와 [이 예시](http://konlpy.org/en/latest/examples/multithreading/)를 참고해주시기 바랍니다.

**Comment by yoonkt200** [comment]
ghost 감사합니다 ㅎㅎ 덕분에 해결됐네요

**Comment by rudvlf0413** [comment]
엇 계정을 통합했더니 하나가 ghost로 뜨네요ㅠㅠ 몇분이 해결하셨다니 다행이네요! :D

**Comment by gilgarad** [comment]
Thread 안에서 konlpy를 호출할 경우에는 먹히지 않습니다. 
Thread 밖에서 클래스를 호출한 뒤에 스레드에서 해당 클래스 오브젝트를 사용해야 되는 것 같습니다.
Thread 안에서 konlpy 클래스를 호출하고ㅅ싶은데 어떻게 해야할까요?

**Comment by rudvlf0413** [comment]
@gilgarad 음 멀티쓰레딩 같은 경우는 안해봤는데요, (Python GIL 때문에 잘 안써서...)
멀티프로세싱 같은 경우는 방금 테스트 코드로 해봤는데 잘 되는것 같더라구요!
제 코드 참조하셔서 안되시면 말씀해주세요~ 

```
from multiprocessing import Process

def test():
    from konlpy.tag import Twitter
    tag = Twitter()
    print(tag.pos("안녕하세요"))


if __name__ == '__main__':
    workers = [Process(target=test) for _ in range(2)]

    for worker in workers:
        worker.start()

    for worker in workers:
        worker.join()
        
```

<img width="499" alt="2018-01-31 3 02 40" src="https://user-images.githubusercontent.com/6302455/35607540-022a20b2-0698-11e8-8079-4d0372031e0b.png">

**Comment by gilgarad** [comment]
@rudvlf0413  답신 늦어 죄송합니다. 해당 해결 방법은 알려주신대로 사용해 보고 잘 되는 것을 확인했지만, 해결방안으로는 적절하지 못하다는 판단을 내렸습니다. 왜냐하면 시스템적 관점에서는 프로세스를 자주 띄우는 것은 결코 좋지 못하기 때문입니다.. 

따라서 테스트만 해보고 거의 바로 해당 해결방법을 고려하지 않아 깜빡 답신을 잊고 있었스니다. 아무튼 답변 감사합니다.
