### ISSUE TITLE
Add userdic

### ISSUE THREAD

**Issue by e9t** [konlpy/konlpy#87]

**Comment by j-min** [comment]
어떻게 진행되고 있는지 알 수 있을까요? 혹은 아래 첫번째 mecab-ko-dic 파일들이 아래 두번째 konlpy 파일들로 어떻게 변환되었는지 알 수 있을까요? 감사합니다.

```
AUTHORS         Hanja.csv    NNB.csv            Place.csv        XR.csv        install-sh*
COPYING         IC.csv       NNBC.csv           Preanalysis.csv  XSA.csv       left-id.def
ChangeLog       INSTALL      NNG.csv            README           XSN.csv       matrix.def
CoinedWord.csv  Inflect.csv  NNP.csv            Symbol.csv       XSV.csv       missing*
EC.csv          J.csv        NP.csv             VA.csv           autogen.sh*   model.def
EF.csv          MAG.csv      NR.csv             VCN.csv          char.def      pos-id.def
EP.csv          MAJ.csv      NorthKorea.csv     VCP.csv          clean*        rewrite.def
ETM.csv         MM.csv       Person-actor.csv   VV.csv           configure*    right-id.def
ETN.csv         Makefile.am  Person.csv         VX.csv           configure.ac  tools/
Foreign.csv     Makefile.in  Place-address.csv  Wikipedia.csv    dicrc         unk.def
Group.csv       NEWS         Place-station.csv  XPN.csv          feature.def   user-dic/
```

```
char.bin  left-id.def  model.bin   rewrite.def   sys.dic
dicrc     matrix.bin   pos-id.def  right-id.def  unk.dic
```

**Comment by e9t** [comment]
@j-min 님, 사용자 사전에 관해서는 아직 진행된 바 없습니다. 말씀하신 "아래 두번째 konlpy 파일들"은, https://bitbucket.org/eunjeon/mecab-ko-dic/ 이 컴파일 될 때 생성된 파일들입니다. 설치 스크립트에서 [이 부분](https://github.com/konlpy/konlpy/blob/master/scripts/mecab.sh#L40-L59)을 봐주세요.

**Comment by e9t** [comment]
This is an issue of highest priority.

- Issue regarding MeCab: https://github.com/konlpy/konlpy/issues/114
- PR regarding Komoran: https://github.com/konlpy/konlpy/pull/113

**Comment by dlsrb6342** [comment]
[mecab.sh](https://github.com/konlpy/konlpy/blob/master/scripts/mecab.sh)를 통해서 설치하셨다면 /tmp/mecab-ko-dic-2.0.1-20150920 에 mecab-ko-dic이 설치되어있고 이 폴더 내에서 #114 에서 말씀하신 것처럼 진행하면 사용자 사전 추가가 가능합니다. 

사용자 사전 추가하는 것은 가능한데 긴 글에서 자신이 추가한 단어들만 뽑아내는 기능에 대해 어떻게 생각하시나요?

**Comment by e9t** [comment]
Resolved by https://github.com/konlpy/konlpy/pull/198.

The above PR introduced userdics into Komoran.
Other backend analyzers should have dedicated issues if a userdic is needed.
(Mecab has one in #114)
