### ISSUE TITLE
윈도우7 + cygwin 환경에서 java 오류

### ISSUE THREAD

**Issue by ironskull** [konlpy/konlpy#88]
안녕하세요, 윈도우7에 cygwin 설치한 환경에서 konlpy를 사용하려 하는데, 설치는 정상적으로 되었으나 실행시 아래와 같은 오류가 발생합니다.

Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object

구글링해보니 윈도우와 cygwin 간 classpath 형식의 차이 때문에 발생하는 오류 같습니다.
jvm.py 에서 classpath를 수정하면 될 것 같은데, 어떻게 수정해야 할 지 제안해 주실 수 있으신가요?
감사합니다.

**Comment by mwkang** [comment]
jvmpath 라는 파라미터로 자바가 설치된 폴더 경로를 알려줄 수 있네요.
cygwin에서 자바가 설치된 경로를 찾으신 다음에 해당 경로를 파라미터로 전달해주시면 될 것 같습니다.
아니면 자바 환경 변수를 profile에 설정해두는 방법도 있을 것 같습니다.

**Comment by e9t** [comment]
jvm.py를 따로 수정하지 않고, @mwkang 님께서 말씀해주신 방법대로 jvmpath를 파라미터로 전달해주시면 됩니다. 다음 이슈에서 사용 예시를 보실 수 있습니다: https://github.com/konlpy/konlpy/issues/8
