### ISSUE TITLE
Python.exe has stopped working 윈도우즈 7

### ISSUE THREAD

**Issue by YINALCO** [konlpy/konlpy#90]
Hello,
안녕하세요~

Whenever I try an example Python stops working in Windows 7, for example :
제가 koNLPy 웹사이트에서 찾은 보기를 윈도우즈7에서 시도할 때마다 Python가 안 뜨고 닫아져요. 예를 들어 이 코드를 써서 :

<pre>
> #! /usr/bin/python3.5
> # -*- coding: utf-8 -*-
> 
> from collections import Counter
> 
> from konlpy.tag import Hannanum
> hannanum = Hannanum()
> print(hannanum.analyze(u'롯데마트의 흑마늘 양념 치킨이 논란이 되고 있다.'))
> [[[('롯데마트', 'ncn'), ('의', 'jcm')], [('롯데마트의', 'ncn')], [('롯데마트', 'nqq'), ('의', 'jcm')], [('롯데마트의', 'nqq')]], [[('흑마늘', 'ncn')], [('흑마늘', 'nqq')]], [[('양념', 'ncn')]], [[('치킨', 'ncn'), ('이', 'jcc')], [('치킨', 'ncn'), ('이', 'jcs')], [('치킨', 'ncn'), ('이', 'ncn')]], [[('논란', 'ncpa'), ('이', 'jcc')], [('논란', 'ncpa'), ('이', 'jcs')], [('논란', 'ncpa'), ('이', 'ncn')]], [[('되', 'nbu'), ('고', 'jcj')], [('되', 'nbu'), ('이', 'jp'), ('고', 'ecc')], [('되', 'nbu'), ('이', 'jp'), ('고', 'ecs')], [('되', 'nbu'), ('이', 'jp'), ('고', 'ecx')], [('되', 'paa'), ('고', 'ecc')], [('되', 'paa'), ('고', 'ecs')], [('되', 'paa'), ('고', 'ecx')], [('되', 'pvg'), ('고', 'ecc')], [('되', 'pvg'), ('고', 'ecs')], [('되', 'pvg'), ('고', 'ecx')], [('되', 'px'), ('고', 'ecc')], [('되', 'px'), ('고', 'ecs')], [('되', 'px'), ('고', 'ecx')]], [[('있', 'paa'), ('다', 'ef')], [('있', 'px'), ('다', 'ef')]], [[('.', 'sf')], [('.', 'sy')]]]
> print(hannanum.morphs(u'롯데마트의 흑마늘 양념 치킨이 논란이 되고 있다.'))
> ['롯데마트', '의', '흑마늘', '양념', '치킨', '이', '논란', '이', '되', '고', '있', '다', '.']
> print(hannanum.nouns(u'다람쥐 헌 쳇바퀴에 타고파'))
> ['다람쥐', '쳇바퀴', '타고파']
> print(hannanum.pos(u'웃으면 더 행복합니다!'))
> [('웃', 'P'), ('으면', 'E'), ('더', 'M'), ('행복', 'N'), ('하', 'X'), ('ㅂ니다', 'E'), ('!', 'S')]
</pre>

Does anyone know why ? (I'm a new user of python, I might have missed something)
어떤 문제인지 아실 분 계신가요? (제가 Python를 처음 사용해봐서 뭘 까먹은 건가요?)
Thank you all !
감사합니다

**Comment by e9t** [comment]
Please check if https://github.com/konlpy/konlpy/issues/55 helps.

**Comment by YINALCO** [comment]
It did help, thank you e9t
(the JDK version I had installed was for 32bits Windows systems)

**Comment by e9t** [comment]
Great to hear the issue was solved.
Happy coding!
