### ISSUE TITLE
문서 탐색하기 : "Top 20 frequent morphemes"

### ISSUE THREAD

**Issue by YINALCO** [konlpy/konlpy#91]
하이요~ 제가 이 웹페이지(http://konlpy.org/en/v0.4.4/examples/explore/)의 코드를 사용하면 아래와 같은 결과만 나오는데 어떤 문제일까요?

> nchars  : 18884
> ntokens : 4178
> nmorphs : 1499
> 
> Top 20 frequent morphemes:
> [Traceback (most recent call last):
>   File "C:\Users\Joon\AppData\Local\Programs\Python\Python35\Lib\site-packages\k
> onlpy\test-exploration.py", line 27, in <module>
>     print('\nTop 20 frequent morphemes:'); pprint(cnt.most_common(20))
>   File "C:\Users\Joon\AppData\Local\Programs\Python\Python35\lib\pprint.py", lin
> e 53, in pprint
>     printer.pprint(object)
>   File "C:\Users\Joon\AppData\Local\Programs\Python\Python35\lib\pprint.py", lin
> e 139, in pprint
>     self._format(object, self._stream, 0, 0, {}, 0)
>   File "C:\Users\Joon\AppData\Local\Programs\Python\Python35\lib\pprint.py", lin
> e 167, in _format
>     p(self, object, stream, indent, allowance, context, level + 1)
>   File "C:\Users\Joon\AppData\Local\Programs\Python\Python35\lib\pprint.py", lin
> e 210, in _pprint_list
>     context, level)
>   File "C:\Users\Joon\AppData\Local\Programs\Python\Python35\lib\pprint.py", lin
> e 389, in _format_items
>     context, level)
>   File "C:\Users\Joon\AppData\Local\Programs\Python\Python35\lib\pprint.py", lin
> e 176, in _format
>     stream.write(rep)
>   File "C:\Users\Joon\AppData\Local\Programs\Python\Python35\lib\encodings\cp850
> .py", line 19, in encode
>     return codecs.charmap_encode(input,self.errors,encoding_map)[0]
> UnicodeEncodeError: 'charmap' codec can't encode character '\uc758' in position
> 3: character maps to \<undefined\>

**추가 정보:**
윈도우즈 7, 64bits
파이썬 3.5

감사합니다~

**Comment by e9t** [comment]
안녕하세요, 해당 문제는 konlpy가 아니라 파이썬 인코딩 문제인 것 같네요.
에러 메세지로 검색해보시면 다양한 답변을 찾으실 수 있습니다. 예를 들어:
http://stackoverflow.com/questions/14630288/unicodeencodeerror-charmap-codec-cant-encode-character-maps-to-undefined
