### ISSUE TITLE
형태소 분석에서, 부정부사만 가져오기

### ISSUE THREAD

**Issue by Kcrong** [konlpy/konlpy#92]
`안 MAG,성분부사/부정부사,T,안,*,*,*,*`

mecab 으로 형태소 분석한 일부분입니다.
문장에서 부정부사만 가져오는 방법이 있을까요?

**Comment by e9t** [comment]
안녕하세요, KoNLPy 관련 이슈가 아니니 이슈를 닫도록 하겠습니다.
