### ISSUE TITLE
꼬꼬마에서 java.lang.OutOfMemoryError가 뜨네요

### ISSUE THREAD

**Issue by jinhyun95** [konlpy/konlpy#93]
Windows 10에서 Anaconda(Python 3.5, jvm 1.7)로 문장별로 꼬꼬마 POS-tagging을 실행할 때, 일부분 되다가 `java.lang.OutOfMemoryErrorPyRaisable: java.lang.OutOfMemoryError: Java heap space`라는 에러문과 함께 멈추게 됩니다.
이전 issue를 보니 Mac에서도 같은 문제가 있었는데 해결이 되었다고 봤는데 왜인지 안되네요. 어떻게 해결할 수 있을까요?

**Comment by mwkang** [comment]
Java heap space 에러는 메모리 부족인데..
실행하실때 java 옵션을 주어서 메모리를 조금 더 할당해보실 수 있나요?
ex) `-Xms512M -Xmx1024M` 옵션을 주는 것입니다.

#72 와 비슷한 이슈 같은데 꼬꼬마가 긴 텍스트 처리에 취약해서 발생한다고 되어 있고 Konlpy에서는 해결 할 수 없는 오류라고 합니다.

**Comment by jinhyun95** [comment]
답변 감사합니다! 긴 텍스트에서는 힘들수도 있을 것같아서 일부러 짧은걸로 여러번 돌렸는데 그래도 안되더군요ㅠㅠ 그래도 답변해주신데로 java max heap size를 2GB로 수정해서 돌리니까 잘 돌아갔습니다! 나중에 더 큰 데이터로 할때에 또 문제가 발생한다면 다른 태거를 사용하거나 해야겠군요...

**Comment by keisunghoon** [comment]
너무 초보스러운 질문이라 죄송하기는 한데요...
힙 메모리 수정은 어떻게 하는 건가요..?

**Comment by e9t** [comment]
Thank you @jinhyun95 for the issue and @johnarmstrong, @mwkang for the helpful replies.
@combacsa has attempted to work around this issue before (https://github.com/konlpy/konlpy/pull/13), but as @mwkang pointed out, it wasn't an actual solution. You can always try using other taggers when you confront a problem.

**Comment by zidane100e** [comment]
위에서 설명한대로 메모리를 좀 더 할당해보고 싶은데,
어떻게 실행하는지 설명 해주실 수 있을까요?
-Xms512M -Xmx1024M

**Comment by ekhc** [comment]
저도 설명좀. MacOS, Jupyter notebook에서 돌리는데

```
import
os.environ['JAVA_OPTS'] = 'Xmx4096M'
```
도 해봤고

```
import subprocess
subprocess.call(['java', '-jar', 'temp.jar', '-Xmx4096M', '-Xms256m'])
```

도 해봤는데 두다 안되고, -Xmx16g로 바꿔도 안되네요. 뭘 잘못하고 있는지는 잘 모르겠네요

hannanum, mecab, okt, kkma다 사용해봤는데

제가 필요한것에서는 kkma밖에 유의미한 형태소분석 안 나오네요. 몇단어 없을때는 kkma가 돌아가긴 하는데, 조금만 단어가 늘어나도 안 돌아가고, chunk로 하면 java.lang.OutofMemoryError가 뜨고. 답답하네요.

**Comment by ehsong** [comment]
안녕하세요 저도 지금 계속 에러 메세지에서 막혀서 분석을 진행 못하고 있는데요 어떻게 하면 메모리 늘릴 수 있나요? 터미널에서 -java -Xmx1024M 하면 되는건가요?

**Comment by sangwook236** [comment]
> 안녕하세요 저도 지금 계속 에러 메세지에서 막혀서 분석을 진행 못하고 있는데요 어떻게 하면 메모리 늘릴 수 있나요? 터미널에서 -java -Xmx1024M 하면 되는건가요? 터미널에서 실행하면 다음과 같이 나오는데, 실행 되는것 같지 않아서요:
> 
> ```
> (base) Eunhous-MacBook-Pro:~ eunhousong$ java -Xms512M -Xmx1024M
> Usage: java [-options] class [args...]
>            (to execute a class)
>    or  java [-options] -jar jarfile [args...]
>            (to execute a jar file)
> where options include:
>     -d32	  use a 32-bit data model if available
>     -d64	  use a 64-bit data model if available
>     -server	  to select the "server" VM
>                   The default VM is server,
>                   because you are running on a server-class machine.
> 
> 
>     -cp <class search path of directories and zip/jar files>
>     -classpath <class search path of directories and zip/jar files>
>                   A : separated list of directories, JAR archives,
>                   and ZIP archives to search for class files.
>     -D<name>=<value>
>                   set a system property
>     -verbose:[class|gc|jni]
>                   enable verbose output
>     -version      print product version and exit
>     -version:<value>
>                   Warning: this feature is deprecated and will be removed
>                   in a future release.
>                   require the specified version to run
>     -showversion  print product version and continue
>     -jre-restrict-search | -no-jre-restrict-search
>                   Warning: this feature is deprecated and will be removed
>                   in a future release.
>                   include/exclude user private JREs in the version search
>     -? -help      print this help message
>     -X            print help on non-standard options
>     -ea[:<packagename>...|:<classname>]
>     -enableassertions[:<packagename>...|:<classname>]
>                   enable assertions with specified granularity
>     -da[:<packagename>...|:<classname>]
>     -disableassertions[:<packagename>...|:<classname>]
>                   disable assertions with specified granularity
>     -esa | -enablesystemassertions
>                   enable system assertions
>     -dsa | -disablesystemassertions
>                   disable system assertions
>     -agentlib:<libname>[=<options>]
>                   load native agent library <libname>, e.g. -agentlib:hprof
>                   see also, -agentlib:jdwp=help and -agentlib:hprof=help
>     -agentpath:<pathname>[=<options>]
>                   load native agent library by full pathname
>     -javaagent:<jarpath>[=<options>]
>                   load Java programming language agent, see java.lang.instrument
>     -splash:<imagepath>
>                   show splash screen with specified image
> See http://www.oracle.com/technetwork/java/javase/documentation/index.html for more details.
> ```

안녕하세요
시간이 상당히 지나 이미 문제를 해결하셨을 것 같긴 하지만 ...
혹시나 해서 도움이 될 만한 사항을 올립니다.

konlpy.jvm.init_jvm(jvmpath=None, max_heap_size=1024)

koonlpy에서 JVM을 초기화하는 함수 init_jvm을 제공하고 있습니다.
두번째 인자인 max_heap_size를 증가시키면 out of memory 현상이 좀 완화되는 것 같아요.

겪으신 문제에 적용가능할지 모르겠지만 ...
도움이 됐으면 하는 마음에 글 올립니다.
