### ISSUE TITLE
한글 소개 페이지인 http://konlpy.org/ko/ 이 이상합니다.

### ISSUE THREAD

**Issue by dialektike** [konlpy/konlpy#96]
한글 내용을 확인하려고 다음 링크로 들어갔는데, 페이지가 안 나옵니다.
http://konlpy.org/ko/
참고로 다음 영어 링크도 페이지가 안 나옵니다.
http://konlpy.org/en/

**Comment by widian** [comment]
한글 내용 확인은 http://konlpy.org/ko/latest/ 여기서 해주세요. 
영문 내용 확인은 http://konlpy.org/en/latest/ 여기서 해주세요. 링크가 깨진듯 합니다.

**Comment by e9t** [comment]
@dialektike 의 이슈 리포팅 감사드리며, @widian 님 답변 감사합니다.

Readthedocs 쪽에서 원래 [redirection을 지원해주고 있는데](http://read-the-docs.readthedocs.io/en/latest/automatic-redirects.html#supported-top-level-redirects), 이상하게 동작이 안되고 있었네요. 일단은 Exact Redirect 룰을 추가함으로써 해당 문제를 해결하였습니다.
