### ISSUE TITLE
Shell restarts after assigning Kkma() to variable

### ISSUE THREAD

**Issue by PrettyCities** [konlpy/konlpy#97]
Hi there!

I'm using Python 2.7.11 on Windows 10.
I am trying to run the example code.
`from konlpy.tag import Kkma` works fine.
But `kkma = Kkma()` restarts the shell without throwing any error.

Any idea what this issue may be? I'm thinking something with jpype, because the shell flashes after I run the code (that is, the window loses focus and then regains it).

**Comment by pointe77** [comment]
같은 이슈가 떠요. 저도 Python 2.7.11 / Windows 10 입니다. 
I have a same issue. My environment is Python 2.7.11 on Windows 10

**Comment by PrettyCities** [comment]
I wound up resolving my issue. The issue was that I installed the wrong
version of JDK. Unfortunately, I am currently not on my home computer. So,
I cannot tell you which version to try installing. For now, I would suggest
installing the opposite version than you currently have installed (ie: if
you have 64 bit installed, replaced that with 32 bit and vice versa).

When I get home, I'll update my answer with the correct version. But, I
wanted to get a basic response out there now just in case you problem was
time sensitive.


결국엔 제가 이 문제를 해결했어요. 문제는 잘못된 JDK 버전을 설치한 것이었어요. 불행하게도 지금은 제가 집 컴퓨터에 떨어져서 어떤
버전이였는지 알려드릴 수 없어요. 일단 반대 버전을 설치하는 걸 제안해요. 예를 들어서 지금 64bit 버전이 설치하는 상태이라면
32bit 버전을 설치해 보세요.

제가 집에 가면 이 대답은 맞은 버전으로 업데이트를 할게요. 당신의 상황은 급한지 몰라서 일단 어떤 대답을 꺼내고 싶어요.

**Comment by e9t** [comment]
Hi @PrettyCities!
Good to hear your issue was resolved. As you've already mentioned, it is important that your computer's architecture - 32 bit or 64 bit - matches that of your JVM in order to run JPype, a dependency of KoNLPy.
