### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)에러에 대해서...

### ISSUE THREAD

**Issue by LeekeunJe** [konlpy/konlpy#98]
현재 파이썬 3.5버젼 설치해서 pycharm으로 막 예제코딩 시작한 초심자입니다.

konlpy, Jpype 모듈 모두 설치해서 간단한 코드를 작성해서 테스트해봤는데

Process finished with exit code -1073741819 (0xC0000005)라는 에러가 뜨네요..

```
from konlpy.tag import Kkma
from konlpy.utils import pprint

kkma = Kkma() 
pprint(kkma.sentences(u'네, 안녕하세요 반갑습니다.')) 
```

여기서 Kkma()를 선언해주는 부분에서 에러가 나는 것 같은데...

무슨 에러인지 알 수 있을까요??

**Comment by e9t** [comment]
안녕하세요. 이슈 https://github.com/konlpy/konlpy/issues/67 와 중복이므로 이 이슈는 닫도록 하겠습니다.
혹시 위 이슈에서 거론된 방법으로 해결이 안된다면 해당 쓰레드에서 계속 논의를 해주시면 감사하겠습니다 :)
